/* L13_dmma -- L = 13 on one A100.
 *
 * Round gpu_r3 adds the small-batch plane-split path: at batch <= 8 the transform
 * is ONE plain launch of 13*B blocks -- each block does dense per-output z+y DFTs of
 * one x-plane into a plan-owned scratch, all blocks join at a software grid barrier
 * (arrive-and-spin on a plan-owned monotonic u64 counter; single plain launch beats
 * cudaLaunchCooperativeKernel by ~1.4 us and a second launch by ~1.6 us), then each
 * block computes one output kx-plane with block-uniform broadcast twiddles.
 * Adopted from L17_dmma round gpu_r2 (their soft-barrier design, ported; epoch
 * counter, co-residency check in create() and two-launch-free fallback included).
 * B=1: 7.86 -> 6.78 us. The fused kernel and its __stcs selection are unchanged
 * from gpu_r2 and still carry all batched points.
 *
 * Round gpu_r2 added ONE production change: the final store is issued with __stcs
 * (evict-first) whenever the working set (in+out = 2*B*35152 B) is L2-resident, so
 * the output stream does not evict the input from L2 between the driver's timed
 * calls (adopted from L8_blockfused round gpu_r1). B=477: 28.4 -> 21.6 us/call.
 * The other kernels in this file (loadz, fused2, split, fusedx, wcp) are measured
 * dead ends kept behind L13_FORCE_* env knobs for future A/B work -- numbers in
 * strategies/L13_dmma.md; none is ever selected by default.
 *
 * Technique (round gpu_r1): fused single kernel, one 13^3 volume per block in shared
 * memory (35,152 B, natural stride 13 is odd so every pass is bank-conflict-free), one
 * thread per 13-point line, three axis passes separated by __syncthreads(), one global
 * read + one global write per volume. The line transform is the conjugate-symmetric
 * folded dense matvec from the CPU phase's L13_direct winner:
 *
 *     u_j = x_j + x_{13-j},  v_j = x_j - x_{13-j}            (j = 1..6)
 *     P_k = x_0 + sum_j cos(2 pi k j/13) u_j
 *     S_k =       sum_j sin(2 pi k j/13) v_j                 (k = 1..6)
 *     X_0 = x_0 + sum_j u_j,   X_k = P_k - i S_k,   X_{13-k} = P_k + i S_k
 *
 * ~29 real flop/point/axis: at B_HBM the arithmetic sits at ~0.6x the HBM floor on the
 * vanilla FP64 pipe, so DMMA (the entry's namesake) is held in reserve -- see the
 * strategy record for the arithmetic and the conditions under which it would pay.
 *
 * The x-axis pass reads shared and writes its results directly to global (coalesced:
 * fixed k, consecutive threads hit consecutive complex doubles), saving one full
 * shared-memory round trip of the volume.
 */
#include <cuda_runtime.h>
#include <cuda_pipeline.h>
#include <stdlib.h>

#include "../fft3d_gpu_api.h"

#define NPT   2197   /* 13^3 */
#define NLINE 169    /* 13^2 lines per axis */
#define TPB   192    /* 6 warps; 169 compute, all 192 load */

/* cos/sin(2 pi k j / 13), k,j = 1..6, folded through the residue (k*j mod 13) so
 * identical coefficients are bit-identical. Generated by numpy at 17 digits. */
static __constant__ double CT[6][6] = {
    {+8.85456025653209911e-01, +5.68064746731155923e-01, +1.20536680255323006e-01, -3.54604887042535455e-01, -7.48510748171101192e-01, -9.70941817426052012e-01},
    {+5.68064746731155923e-01, -3.54604887042535455e-01, -9.70941817426052012e-01, -7.48510748171101192e-01, +1.20536680255323006e-01, +8.85456025653209911e-01},
    {+1.20536680255323006e-01, -9.70941817426052012e-01, -3.54604887042535455e-01, +8.85456025653209911e-01, +5.68064746731155923e-01, -7.48510748171101192e-01},
    {-3.54604887042535455e-01, -7.48510748171101192e-01, +8.85456025653209911e-01, +1.20536680255323006e-01, -9.70941817426052012e-01, +5.68064746731155923e-01},
    {-7.48510748171101192e-01, +1.20536680255323006e-01, +5.68064746731155923e-01, -9.70941817426052012e-01, +8.85456025653209911e-01, -3.54604887042535455e-01},
    {-9.70941817426052012e-01, +8.85456025653209911e-01, -7.48510748171101192e-01, +5.68064746731155923e-01, -3.54604887042535455e-01, +1.20536680255323006e-01},
};
static __constant__ double ST[6][6] = {
    {+4.64723172043768507e-01, +8.22983865893656352e-01, +9.92708874098053973e-01, +9.35016242685414833e-01, +6.63122658240795193e-01, +2.39315664287557683e-01},
    {+8.22983865893656352e-01, +9.35016242685414833e-01, +2.39315664287557683e-01, -6.63122658240795193e-01, -9.92708874098053973e-01, -4.64723172043768507e-01},
    {+9.92708874098053973e-01, +2.39315664287557683e-01, -9.35016242685414833e-01, -4.64723172043768507e-01, +8.22983865893656352e-01, +6.63122658240795193e-01},
    {+9.35016242685414833e-01, -6.63122658240795193e-01, -4.64723172043768507e-01, +9.92708874098053973e-01, -2.39315664287557683e-01, -8.22983865893656352e-01},
    {+6.63122658240795193e-01, -9.92708874098053973e-01, +8.22983865893656352e-01, -2.39315664287557683e-01, -4.64723172043768507e-01, +9.35016242685414833e-01},
    {+2.39315664287557683e-01, -4.64723172043768507e-01, +6.63122658240795193e-01, -8.22983865893656352e-01, +9.35016242685414833e-01, -9.92708874098053973e-01},
};

/* One 13-point line: read src[0..12]*S, write dst[0..12]*S. Fold on load so only
 * u, v, x0 and four accumulators are live -- the register budget for 4 blocks/SM.
 * STREAM=true issues the stores with __stcs (evict-first): used on the final
 * global write when the working set is L2-resident, so the output stream does not
 * evict the input from L2 between the driver's timed calls. */
template <int S, bool STREAM = false>
__device__ __forceinline__ void dft13(const double2 *__restrict__ src,
                                      double2 *__restrict__ dst)
{
    double ur[6], ui[6], vr[6], vi[6];
    const double2 x0 = src[0];
#pragma unroll
    for (int j = 1; j <= 6; ++j) {
        const double2 a = src[j * S];
        const double2 b = src[(13 - j) * S];
        ur[j - 1] = a.x + b.x;
        ui[j - 1] = a.y + b.y;
        vr[j - 1] = a.x - b.x;
        vi[j - 1] = a.y - b.y;
    }
    double ar = x0.x, ai = x0.y;
#pragma unroll
    for (int j = 0; j < 6; ++j) { ar += ur[j]; ai += ui[j]; }
    if (STREAM) __stcs(dst, make_double2(ar, ai));
    else        dst[0] = make_double2(ar, ai);
#pragma unroll
    for (int k = 1; k <= 6; ++k) {
        double pr = x0.x, pi = x0.y, sr = 0.0, si = 0.0;
#pragma unroll
        for (int j = 0; j < 6; ++j) {
            pr = fma(CT[k - 1][j], ur[j], pr);
            pi = fma(CT[k - 1][j], ui[j], pi);
            sr = fma(ST[k - 1][j], vr[j], sr);
            si = fma(ST[k - 1][j], vi[j], si);
        }
        if (STREAM) {
            __stcs(dst + k * S,        make_double2(pr + si, pi - sr));
            __stcs(dst + (13 - k) * S, make_double2(pr - si, pi + sr));
        } else {
            dst[k * S]        = make_double2(pr + si, pi - sr);
            dst[(13 - k) * S] = make_double2(pr - si, pi + sr);
        }
    }
}

template <bool STREAM>
__global__ void __launch_bounds__(TPB, 4)
fft13_fused(const double2 *__restrict__ in, double2 *__restrict__ out)
{
    __shared__ double2 s[NPT];
    const int t = threadIdx.x;
    const size_t vbase = (size_t)blockIdx.x * NPT;

    /* Stage the volume through shared with the classic interleaved-coalesced pattern
     * (per-thread contiguous z-line reads measured 8% slower end-to-end: 1244 GB/s
     * against 1355 GB/s at B_HBM -- sector waste against a 28 KB L1). 169 threads x
     * 13 unrolled iterations covers 2197 exactly: no bounds check, 13 loads in flight. */
    if (t < NLINE) {
#pragma unroll
        for (int k = 0; k < 13; ++k) s[t + k * NLINE] = in[vbase + t + k * NLINE];
    }
    __syncthreads();

    if (t < NLINE) dft13<1>(s + t * 13, s + t * 13);           /* z: stride 1   */
    __syncthreads();
    if (t < NLINE) {                                           /* y: stride 13  */
        double2 *p = s + (t / 13) * 169 + (t % 13);
        dft13<13>(p, p);
    }
    __syncthreads();
    if (t < NLINE)                                             /* x: stride 169, write global */
        dft13<169, STREAM>(s + t, out + vbase + t);
}

/* L2-resident variant: the z-pass reads each thread's contiguous 208 B global
 * z-line directly into registers (no staging pass, no staging barrier, one shared
 * round trip fewer). At B_HBM this pattern lost 8% (half-used 32 B sectors against
 * DRAM); when the input is L2-resident the sector re-reads are absorbed by L2,
 * which ncu shows only 50% busy in the stall-bound B_L2 regime. */
template <bool STREAM>
__global__ void __launch_bounds__(TPB, 4)
fft13_fused_loadz(const double2 *__restrict__ in, double2 *__restrict__ out)
{
    __shared__ double2 s[NPT];
    const int t = threadIdx.x;
    const size_t vbase = (size_t)blockIdx.x * NPT;

    if (t < NLINE) {
        double2 r[13];
#pragma unroll
        for (int j = 0; j < 13; ++j) r[j] = in[vbase + t * 13 + j];
        dft13<1>(r, r);                                        /* z in registers */
#pragma unroll
        for (int j = 0; j < 13; ++j) s[t * 13 + j] = r[j];
    }
    __syncthreads();

    if (t < NLINE) {                                           /* y: stride 13  */
        double2 *p = s + (t / 13) * 169 + (t % 13);
        dft13<13>(p, p);
    }
    __syncthreads();
    if (t < NLINE)                                             /* x: stride 169, write global */
        dft13<169, STREAM>(s + t, out + vbase + t);
}

/* Pass-reordered kernel (x, y, z instead of z, y, x): the staging load's round k
 * for thread t is in[vbase + k*169 + t] -- which is precisely element k of the
 * stride-169 x-line (y,z) = t. So the x-pass happens in registers DURING the
 * (identical, perfectly coalesced) staging load: one shared round trip and one
 * barrier fewer than the z-first kernel. The price is the final z-pass's global
 * store: thread t writes 13 consecutive double2 at out + t*13 -- scattered per
 * instruction (32 lanes hit 32 distinct 32 B sectors) but full-coverage per
 * warp (32 x 208 B = one contiguous 6656 B span), so L2 merges the sectors and
 * DRAM still sees pure sequential writes. Unlike the failed loadz global READ
 * of the same shape, stores have no latency/replay cost to eat. */
template <bool STREAM>
__global__ void __launch_bounds__(TPB, 4)
fft13_fusedx(const double2 *__restrict__ in, double2 *__restrict__ out)
{
    __shared__ double2 s[NPT];
    const int t = threadIdx.x;
    const size_t vbase = (size_t)blockIdx.x * NPT;

    if (t < NLINE) {
        double2 r[13];
#pragma unroll
        for (int k = 0; k < 13; ++k) r[k] = in[vbase + t + k * NLINE];
        dft13<1>(r, r);                                        /* x in registers */
#pragma unroll
        for (int k = 0; k < 13; ++k) s[t + k * NLINE] = r[k];
    }
    __syncthreads();

    if (t < NLINE) {                                           /* y: stride 13  */
        double2 *p = s + (t / 13) * 169 + (t % 13);
        dft13<13>(p, p);
    }
    __syncthreads();
    if (t < NLINE)                                             /* z: stride 1, write global */
        dft13<1, STREAM>(s + t * 13, out + vbase + t * 13);
}

/* Half-line worker for the small-batch split kernel: reads the whole 13-point
 * line (fold included), but emits only half the outputs -- H=0: X_0 and the
 * conjugate pairs k=1..3, H=1: pairs k=4..6. Two threads per line halve the
 * FMA dependency chain of a pass. Out-of-place (src != dst), so no barrier or
 * register parking is needed between the partners -- the round-1 two-half
 * attempt died on exactly that parking (11.0 us vs 7.9). */
template <int S, int H, bool STREAM = false>
__device__ __forceinline__ void dft13_half(const double2 *__restrict__ src,
                                           double2 *__restrict__ dst)
{
    double ur[6], ui[6], vr[6], vi[6];
    const double2 x0 = src[0];
#pragma unroll
    for (int j = 1; j <= 6; ++j) {
        const double2 a = src[j * S];
        const double2 b = src[(13 - j) * S];
        ur[j - 1] = a.x + b.x;
        ui[j - 1] = a.y + b.y;
        vr[j - 1] = a.x - b.x;
        vi[j - 1] = a.y - b.y;
    }
    if (H == 0) {
        double ar = x0.x, ai = x0.y;
#pragma unroll
        for (int j = 0; j < 6; ++j) { ar += ur[j]; ai += ui[j]; }
        if (STREAM) __stcs(dst, make_double2(ar, ai));
        else        dst[0] = make_double2(ar, ai);
    }
#pragma unroll
    for (int k = (H == 0 ? 1 : 4); k <= (H == 0 ? 3 : 6); ++k) {
        double pr = x0.x, pi = x0.y, sr = 0.0, si = 0.0;
#pragma unroll
        for (int j = 0; j < 6; ++j) {
            pr = fma(CT[k - 1][j], ur[j], pr);
            pi = fma(CT[k - 1][j], ui[j], pi);
            sr = fma(ST[k - 1][j], vr[j], sr);
            si = fma(ST[k - 1][j], vi[j], si);
        }
        if (STREAM) {
            __stcs(dst + k * S,        make_double2(pr + si, pi - sr));
            __stcs(dst + (13 - k) * S, make_double2(pr - si, pi + sr));
        } else {
            dst[k * S]        = make_double2(pr + si, pi - sr);
            dst[(13 - k) * S] = make_double2(pr - si, pi + sr);
        }
    }
}

/* Small-batch kernel: one volume per block, TWO threads per line, ping-pong
 * shared buffers (sA -> sB -> sA -> global) so the passes are out-of-place and
 * the two halves of a line never race. h = t/192 keeps the halves warp-aligned
 * (no intra-warp divergence except the l >= 169 idle lanes). 70,304 B dynamic
 * shared -- irrelevant to occupancy in the latency regime this kernel is for. */
template <bool STREAM>
__global__ void __launch_bounds__(384, 1)
fft13_split(const double2 *__restrict__ in, double2 *__restrict__ out)
{
    extern __shared__ double2 sp[];
    double2 *sA = sp, *sB = sp + NPT;
    const int t = threadIdx.x;
    const size_t vbase = (size_t)blockIdx.x * NPT;

#pragma unroll
    for (int k = 0; k < 5; ++k) sA[t + k * 384] = in[vbase + t + k * 384];
    if (t + 5 * 384 < NPT) sA[t + 5 * 384] = in[vbase + t + 5 * 384];
    __syncthreads();

    const int h = t / 192, l = t - h * 192;
    const bool act = (l < NLINE);
    if (act) {                                                          /* z */
        const int base = l * 13;
        if (h == 0) dft13_half<1, 0>(sA + base, sB + base);
        else        dft13_half<1, 1>(sA + base, sB + base);
    }
    __syncthreads();
    if (act) {                                                          /* y */
        const int base = (l / 13) * 169 + (l % 13);
        if (h == 0) dft13_half<13, 0>(sB + base, sA + base);
        else        dft13_half<13, 1>(sB + base, sA + base);
    }
    __syncthreads();
    if (act) {                                                          /* x */
        if (h == 0) dft13_half<169, 0, STREAM>(sA + l, out + vbase + l);
        else        dft13_half<169, 1, STREAM>(sA + l, out + vbase + l);
    }
}

/* V=2 variant: two volumes per 384-thread block (338 compute lines), 70,304 B
 * static shared, 2 blocks/SM -- same 24 warps/SM as V=1 but half the barriers per
 * volume (idea from L8_blockfused round gpu_r1, whose L2-point autotune picked
 * V=2 + __stcs). Tail block handles an odd batch with one volume. */
#define TPB2 384
template <bool STREAM>
__global__ void __launch_bounds__(TPB2, 2)
fft13_fused2(const double2 *__restrict__ in, double2 *__restrict__ out, int batch)
{
    /* 70,304 B > the 48 KB static limit: dynamic shared + the sm_80 opt-in. */
    extern __shared__ double2 s[];
    const int t = threadIdx.x;
    const size_t vbase = (size_t)blockIdx.x * 2 * NPT;
    const int nv = min(2, batch - 2 * blockIdx.x);   /* 2, or 1 in an odd tail */

    if (nv == 2) {
#pragma unroll
        for (int k = 0; k < 11; ++k) s[t + k * TPB2] = in[vbase + t + k * TPB2];
        const int i = t + 11 * TPB2;
        if (i < 2 * NPT) s[i] = in[vbase + i];
    } else if (t < NLINE) {
#pragma unroll
        for (int k = 0; k < 13; ++k) s[t + k * NLINE] = in[vbase + t + k * NLINE];
    }
    __syncthreads();

    const int v = t / NLINE, l = t - v * NLINE;      /* volume 0/1, line 0..168 */
    const bool act = (t < 2 * NLINE) && (v < nv);
    if (act) dft13<1>(s + v * NPT + l * 13, s + v * NPT + l * 13);      /* z */
    __syncthreads();
    if (act) {                                                          /* y */
        double2 *p = s + v * NPT + (l / 13) * 169 + (l % 13);
        dft13<13>(p, p);
    }
    __syncthreads();
    if (act)                                                            /* x */
        dft13<169, STREAM>(s + v * NPT + l, out + vbase + v * NPT + l);
}

/* ---------------- round gpu_r3: small-batch plane-split path ---------------- */

/* Full forward twiddle W[m] = exp(-2*pi*i*m/13), m = 0..12, assembled from the same
 * numpy-generated 17-digit cos/sin values as CT/ST (rows are cos/sin(2*pi*m/13) for
 * m = 1..6; m = 7..12 by symmetry), so identical constants stay bit-identical. */
#define C13_1 8.85456025653209911e-01
#define C13_2 5.68064746731155923e-01
#define C13_3 1.20536680255323006e-01
#define C13_4 (-3.54604887042535455e-01)
#define C13_5 (-7.48510748171101192e-01)
#define C13_6 (-9.70941817426052012e-01)
#define S13_1 4.64723172043768507e-01
#define S13_2 8.22983865893656352e-01
#define S13_3 9.92708874098053973e-01
#define S13_4 9.35016242685414833e-01
#define S13_5 6.63122658240795193e-01
#define S13_6 2.39315664287557683e-01
#define W13_INIT { \
    {1.0, 0.0}, \
    {C13_1, -S13_1}, {C13_2, -S13_2}, {C13_3, -S13_3}, \
    {C13_4, -S13_4}, {C13_5, -S13_5}, {C13_6, -S13_6}, \
    {C13_6, +S13_6}, {C13_5, +S13_5}, {C13_4, +S13_4}, \
    {C13_3, +S13_3}, {C13_2, +S13_2}, {C13_1, +S13_1}, \
}
/* Phase 1 reads the table lane-divergently (kz/ky vary across lanes): a global
 * array via __ldg, NOT constant memory -- divergent constant reads replay 32-way
 * (L17_dmma round gpu_r1 finding #3). Phase 2's kx is block-uniform: broadcast
 * from __constant__ is the right home there. */
static __device__   double2 g_W13[13] = W13_INIT;
static __constant__ double2 c_W13[13] = W13_INIT;

/* Small-batch kernel: ONE plain launch of 13*B blocks, joined mid-kernel by a
 * software grid barrier (adopted from L17_dmma round gpu_r2: plain launch + soft
 * barrier measured 7.74 us vs 11.88 cooperative vs 10.50 two-launch at their B=1).
 *
 * Phase 1 (block = volume b, plane x = p): stage the contiguous 169-element plane
 * into shared, dense per-output z-DFT (thread = (y,kz)), dense per-output y-DFT
 * (thread = (ky,kz)), write the plane to scratch -- all loads/stores coalesced.
 * Barrier: each block's thread 0 does __threadfence + atomicAdd(+1) on a plan-owned
 * MONOTONIC u64 counter, then spins until it reaches epoch*gridDim (target passed
 * as an argument, so back-to-back calls on one stream cannot confuse epochs).
 * Legal only because create() verified the whole 13*B-block grid co-resident.
 * Phase 2 (block = volume b, output plane kx): thread t = (ky,kz) sums the 13
 * scratch planes at stride 169 (coalesced across the warp per x) against
 * block-uniform c_W13[kx*x mod 13] and stores the contiguous output plane.
 * Dense per-output arithmetic is ~2x the folded matvec's flops -- irrelevant at
 * B<=12 where the whole grid is latency- and launch-bound. */
__global__ void __launch_bounds__(TPB)
fft13_planes(const double2 *__restrict__ in, double2 *__restrict__ out,
             double2 *__restrict__ scratch,
             unsigned long long *__restrict__ ctr, unsigned long long target)
{
    __shared__ double2 s[NLINE], s2[NLINE];
    const int t = threadIdx.x;
    const int b = blockIdx.x / 13, p = blockIdx.x - 13 * b;
    const size_t vbase = (size_t)b * NPT;

    if (t < NLINE) s[t] = in[vbase + p * NLINE + t];
    __syncthreads();

    if (t < NLINE) {                       /* z: thread (y,kz), row y is contiguous */
        const int y = t / 13, kz = t - 13 * y;
        double xr = 0.0, xi = 0.0;
        int m = 0;
#pragma unroll
        for (int z = 0; z < 13; ++z) {
            const double2 v = s[y * 13 + z];
            const double2 w = __ldg(&g_W13[m]);
            xr = fma(v.x, w.x, fma(-v.y, w.y, xr));
            xi = fma(v.x, w.y, fma( v.y, w.x, xi));
            m += kz; if (m >= 13) m -= 13;
        }
        s2[t] = make_double2(xr, xi);
    }
    __syncthreads();

    if (t < NLINE) {                       /* y: thread (ky,kz), column stride 13 (odd) */
        const int ky = t / 13, kz = t - 13 * ky;
        double xr = 0.0, xi = 0.0;
        int m = 0;
#pragma unroll
        for (int y = 0; y < 13; ++y) {
            const double2 v = s2[y * 13 + kz];
            const double2 w = __ldg(&g_W13[m]);
            xr = fma(v.x, w.x, fma(-v.y, w.y, xr));
            xi = fma(v.x, w.y, fma( v.y, w.x, xi));
            m += ky; if (m >= 13) m -= 13;
        }
        scratch[vbase + p * NLINE + t] = make_double2(xr, xi);
    }

    /* Software grid barrier: release = __syncthreads + __threadfence before the
     * arrive; acquire = __threadfence after the spin + __syncthreads. */
    __syncthreads();
    if (t == 0) {
        __threadfence();
        atomicAdd(ctr, 1ULL);
        while (*(volatile unsigned long long *)ctr < target) { }
        __threadfence();
    }
    __syncthreads();

    {                                      /* x: block = kx-plane, broadcast twiddles */
        const int kx = p;
        if (t < NLINE) {
            double xr = 0.0, xi = 0.0;
            int m = 0;
#pragma unroll
            for (int x = 0; x < 13; ++x) {
                const double2 v = scratch[vbase + x * NLINE + t];
                const double2 w = c_W13[m];
                xr = fma(v.x, w.x, fma(-v.y, w.y, xr));
                xi = fma(v.x, w.y, fma( v.y, w.x, xi));
                m += kx; if (m >= 13) m -= 13;
            }
            out[vbase + kx * NLINE + t] = make_double2(xr, xi);
        }
    }
}

/* Warp-chunked cp.async staging fused into the z-pass (idea from L17_raderfused
 * round gpu_r2, where it bought -2.3% at their HBM point): warp w's 32 z-lines
 * cover exactly the contiguous elements [416w, 416w+416), so each warp cp.asyncs
 * its OWN chunk, waits on its own group, __syncwarp()s, and starts its z lines
 * while other warps' loads are still in flight -- deletes the load->z
 * __syncthreads. Kept behind L13_FORCE_WCP: measured a LOSS here (numbers in the
 * strategy record) -- L8_blockfused r2's warning that a per-warp-contiguous read
 * order loses to the flat interleaved order at the DRAM wall wins the tug-of-war
 * at L=13's 4-blocks/SM de-phased residency. */
template <bool STREAM>
__global__ void __launch_bounds__(TPB, 4)
fft13_fused_wcp(const double2 *__restrict__ in, double2 *__restrict__ out)
{
    __shared__ double2 s[NPT];
    const int t = threadIdx.x;
    const int lane = t & 31, w = t >> 5;
    const size_t vbase = (size_t)blockIdx.x * NPT;
    const int base = 416 * w;

#pragma unroll
    for (int r = 0; r < 13; ++r) {
        const int idx = base + r * 32 + lane;
        if (idx < NPT)
            __pipeline_memcpy_async(&s[idx], &in[vbase + idx], sizeof(double2));
    }
    __pipeline_commit();
    __pipeline_wait_prior(0);
    __syncwarp();

    if (t < NLINE) dft13<1>(s + t * 13, s + t * 13);           /* z: own-warp chunk only */
    __syncthreads();
    if (t < NLINE) {                                           /* y: stride 13  */
        double2 *p = s + (t / 13) * 169 + (t % 13);
        dft13<13>(p, p);
    }
    __syncthreads();
    if (t < NLINE)                                             /* x: stride 169, write global */
        dft13<169, STREAM>(s + t, out + vbase + t);
}

struct fft3d_gpu_plan {
    int L; int batch; int stream_store; int loadz; int v2; int split; int fusedx;
    int wcp;                       /* forced A/B knob only */
    int planes;                    /* small-batch soft-barrier path active */
    double2 *scratch;              /* planes path: B*2197 double2 */
    unsigned long long *ctr;       /* planes path: monotonic arrive counter */
    unsigned long long epoch;      /* host-side call count for the barrier target */
};

extern "C" const char *fft3d_gpu_name(void) { return "L13_dmma"; }
extern "C" const char *fft3d_gpu_description(void)
{ return "fused block-per-volume in shared, conj-folded dense-13 lines; __stcs store when L2-resident; soft-barrier single-launch plane-split at batch<=8"; }
extern "C" int fft3d_gpu_supports(int L) { return L == 13; }

extern "C" fft3d_gpu_plan *fft3d_gpu_create(int L, int batch)
{
    if (L != 13 || batch < 1) return NULL;
    /* 4 blocks/SM wants 4 x 35,152 B resident: ask for the full shared carveout. */
    cudaFuncSetAttribute(fft13_fused<false>, cudaFuncAttributePreferredSharedMemoryCarveout, 100);
    cudaFuncSetAttribute(fft13_fused<true>,  cudaFuncAttributePreferredSharedMemoryCarveout, 100);
    fft3d_gpu_plan *p = (fft3d_gpu_plan *)malloc(sizeof *p);
    if (!p) return NULL;
    p->L = L;
    p->batch = batch;
    /* Evict-first (__stcs) final store when the working set is L2-resident, so the
     * output stream does not evict the input between timed calls (adopted from
     * L8_blockfused round gpu_r1: -43% at their B_L2, -1% at B_HBM, hence the
     * per-batch selection). in+out = 2*B*35152 B against the 40 MiB L2. */
    p->stream_store = ((size_t)batch * 2u * NPT * sizeof(double2) <= (40u << 20));
    p->v2 = 0;
    p->split = 0;   /* measured: 7.90 vs 7.84 us at B=1 -- no gain, kept for A/B only */
    p->fusedx = 0;
    p->wcp = 0;
    p->planes = 0;
    p->scratch = NULL;
    p->ctr = NULL;
    p->epoch = 0;
    /* Small-batch plane-split path (round gpu_r3): one plain launch joined by a
     * software grid barrier. Crossover measured on the leased SXM4: planes wins
     * through B=8 (7.63 vs 8.41 us), fused takes over at B=10 (9.17 vs 8.47).
     * The spin barrier is legal only if all 13*B blocks are co-resident: verify
     * with the occupancy query x 108 SMs; anything short falls back to the fused
     * kernel automatically. */
    {
        int planes_max_b = 8;
        const char *e = getenv("L13_PLANES_MAX_B");
        if (e) planes_max_b = atoi(e);
        if (batch <= planes_max_b) {
            int nb = 0, sm = 0, dev = 0;
            cudaGetDevice(&dev);
            cudaDeviceGetAttribute(&sm, cudaDevAttrMultiProcessorCount, dev);
            cudaOccupancyMaxActiveBlocksPerMultiprocessor(&nb, fft13_planes, TPB, 0);
            if ((long long)nb * sm >= 13LL * batch &&
                cudaMalloc(&p->scratch, (size_t)batch * NPT * sizeof(double2)) == cudaSuccess) {
                if (cudaMalloc(&p->ctr, sizeof(unsigned long long)) == cudaSuccess &&
                    cudaMemset(p->ctr, 0, sizeof(unsigned long long)) == cudaSuccess) {
                    p->planes = 1;
                } else {
                    if (p->ctr) { cudaFree(p->ctr); p->ctr = NULL; }
                    cudaFree(p->scratch); p->scratch = NULL;
                }
            }
        }
    }
    {   /* A/B override for lease experiments; scoring runs never set these. */
        const char *e = getenv("L13_FORCE_LOADZ");
        p->loadz = (e && *e == '1');
        e = getenv("L13_FORCE_STCS");
        if (e) p->stream_store = (*e == '1');
        e = getenv("L13_FORCE_V2");
        if (e) p->v2 = (*e == '1');
        e = getenv("L13_FORCE_SPLIT");
        if (e) p->split = (*e == '1');
        e = getenv("L13_FORCE_FUSEDX");
        if (e) p->fusedx = (*e == '1');
        e = getenv("L13_FORCE_WCP");
        if (e) p->wcp = (*e == '1');
        if (p->wcp) {
            cudaFuncSetAttribute(fft13_fused_wcp<false>, cudaFuncAttributePreferredSharedMemoryCarveout, 100);
            cudaFuncSetAttribute(fft13_fused_wcp<true>,  cudaFuncAttributePreferredSharedMemoryCarveout, 100);
        }
    }
    if (p->fusedx) {
        cudaFuncSetAttribute(fft13_fusedx<false>, cudaFuncAttributePreferredSharedMemoryCarveout, 100);
        cudaFuncSetAttribute(fft13_fusedx<true>,  cudaFuncAttributePreferredSharedMemoryCarveout, 100);
    }
    if (p->split) {
        cudaFuncSetAttribute(fft13_split<false>, cudaFuncAttributePreferredSharedMemoryCarveout, 100);
        cudaFuncSetAttribute(fft13_split<true>,  cudaFuncAttributePreferredSharedMemoryCarveout, 100);
        cudaFuncSetAttribute(fft13_split<false>, cudaFuncAttributeMaxDynamicSharedMemorySize, 2 * NPT * (int)sizeof(double2));
        cudaFuncSetAttribute(fft13_split<true>,  cudaFuncAttributeMaxDynamicSharedMemorySize, 2 * NPT * (int)sizeof(double2));
    }
    if (p->v2) {
        cudaFuncSetAttribute(fft13_fused2<false>, cudaFuncAttributePreferredSharedMemoryCarveout, 100);
        cudaFuncSetAttribute(fft13_fused2<true>,  cudaFuncAttributePreferredSharedMemoryCarveout, 100);
        cudaFuncSetAttribute(fft13_fused2<false>, cudaFuncAttributeMaxDynamicSharedMemorySize, 2 * NPT * (int)sizeof(double2));
        cudaFuncSetAttribute(fft13_fused2<true>,  cudaFuncAttributeMaxDynamicSharedMemorySize, 2 * NPT * (int)sizeof(double2));
    }
    if (p->loadz) {
        cudaFuncSetAttribute(fft13_fused_loadz<false>, cudaFuncAttributePreferredSharedMemoryCarveout, 100);
        cudaFuncSetAttribute(fft13_fused_loadz<true>,  cudaFuncAttributePreferredSharedMemoryCarveout, 100);
    }
    return p;
}

extern "C" void fft3d_gpu_execute(fft3d_gpu_plan *p, const double2 *in, double2 *out)
{
    if (p->planes && !p->fusedx && !p->split && !p->v2 && !p->loadz && !p->wcp) {
        const unsigned int grid = 13u * (unsigned int)p->batch;
        p->epoch += 1;
        fft13_planes<<<grid, TPB>>>(in, out, p->scratch, p->ctr,
                                    p->epoch * (unsigned long long)grid);
    } else if (p->wcp) {
        if (p->stream_store) fft13_fused_wcp<true><<<p->batch, TPB>>>(in, out);
        else                 fft13_fused_wcp<false><<<p->batch, TPB>>>(in, out);
    } else if (p->fusedx) {
        if (p->stream_store) fft13_fusedx<true><<<p->batch, TPB>>>(in, out);
        else                 fft13_fusedx<false><<<p->batch, TPB>>>(in, out);
    } else if (p->split) {
        const int shm = 2 * NPT * (int)sizeof(double2);
        if (p->stream_store) fft13_split<true><<<p->batch, 384, shm>>>(in, out);
        else                 fft13_split<false><<<p->batch, 384, shm>>>(in, out);
    } else if (p->v2) {
        const int nb = (p->batch + 1) / 2;
        const int shm = 2 * NPT * (int)sizeof(double2);
        if (p->stream_store) fft13_fused2<true><<<nb, TPB2, shm>>>(in, out, p->batch);
        else                 fft13_fused2<false><<<nb, TPB2, shm>>>(in, out, p->batch);
    } else if (p->loadz) {
        if (p->stream_store) fft13_fused_loadz<true><<<p->batch, TPB>>>(in, out);
        else                 fft13_fused_loadz<false><<<p->batch, TPB>>>(in, out);
    } else {
        if (p->stream_store) fft13_fused<true><<<p->batch, TPB>>>(in, out);
        else                 fft13_fused<false><<<p->batch, TPB>>>(in, out);
    }
}

extern "C" void fft3d_gpu_destroy(fft3d_gpu_plan *p)
{
    if (!p) return;
    if (p->scratch) cudaFree(p->scratch);
    if (p->ctr) cudaFree(p->ctr);
    free(p);
}
