cd /workdir/dev && python3 - <<'EOF'
src = open('gen.py').read()
old = """HDR = r'''// AUTO-GENERATED -- batched iterated 3D DFT specialized kernels"""
new = """HDR = r'''// AUTO-GENERATED by dev/gen.py -- batched iterated 3D complex-FFT kernels,
// fully specialized for cube sizes L in {6,8,13,17,23,36,45,64}.
//
// All transform arithmetic is our own (no FFT library):
//   - data is held in split re/im form; every kernel operates on 8-lane
//     AVX-512 vectors (gcc vector extensions), vectorizing across 8
//     independent 1D transforms (8 volumes for small L, 8 z/y-columns for
//     large L).
//   - 1D DFT cores: PFA(2x3) for 6, Cooley-Tukey(4x2) for 8, symmetric
//     "half-matrix" real-coefficient forms for primes 13/17/23 (k-quad
//     register blocking), PFA(4x9) for 36, PFA(9x5) for 45, CT(8x8) for 64,
//     with exact-twiddle tables rounded from long-double.
//   - iteration z = FFT3(x)+c ; x = z/(1+|z|) is fused: the final axis pass
//     applies +c and the pointwise map in its store stage. 1/(1+sqrt(s)) is
//     computed by vsqrtpd + rcp14+Newton or by rsqrt14/rcp14 Newton chains
//     (mixed per output to balance the divider and FMA ports); accuracy is
//     1-2 ulp, far inside the required tolerances.
//   - small L (6,8,13,17,23): SoA across 8 volumes, all m iterations run
//     L2-resident per group; remainder volumes fall back to a per-volume
//     slab scheme so tiny batches pay no lane waste.
//   - 36/64: square-CT "ping-pong" -- the x-axis FFT is split into two
//     radix-G stages fused around the (y,z) slab passes so each iteration
//     makes a single sweep over the volume (reads x and c once, writes x
//     once). 64's z-pass runs fully in registers (vertical fft8 stages +
//     one in-register 8x8 transpose, self-sorting).
//   - 45: the same idea with alternating PFA(9,5)/(5,9) factor order per
//     iteration (stage-2 output groups become the next iteration's stage-1
//     cosets).
// Only the natural-order complex128 ingest/extract touches the numpy
// buffers; everything in between lives in static padded split-format
// scratch that stays cache-resident across all m iterations of a volume."""
assert old in src
src = src.replace(old, new)
open('gen.py','w').write(src)
EOF
cat > README_dev.md <<'EOF'
# dev/ -- generator and tooling for implementation.c

- `gen.py`        : generates ../implementation.c (run from this directory: `python3 gen.py`).
                    Config via GENCFG env (JSON) overrides baked defaults.
- `codelets.py`   : straight-line small-DFT emitters (2,3,4,5,6,8,9 + halfmatrix + CT/PFA combiners),
                    exact twiddles from numpy longdouble.
- `kernels.py`    : looped/instanced column-FFT kernels with baked strides, fused pointwise stores,
                    square-CT stage kernels, in-register 64-point line FFT.
- `check.py`      : correctness harness vs /workdir/base.py (per-block gates).
- `tune.py`       : per-size ns/element-iteration benchmark via ctypes.
- `test_cores.py` : unit tests of DFT cores vs numpy.

implementation.c is committed; grading does not need to run the generator.
EOF
mv README_dev.md /workdir/dev/README.md && python3 gen.py && cd /workdir && rm -f implementation.so && gcc -O3 -march=native -shared -fPIC implementation.c -o implementation.so -lm && python3 dev/check.py | tail -1 && head -35 implementation.c