# Generates implementation.c
import codelets, kernels

SIZES = (6, 8, 13, 17, 23, 36, 45, 64)
import os, json
CONFIG = {'pw': {'13': 'alt', '17': 'alt', '23': 'sqrtnr', '45': 'sqrtnr', '6': 'alt', '8': 'alt'}, 'pf': {}, 'hu': {'13': '16', '17': '16', '23': '1'}, 'scheme': {}, 'hm2': {}, 'nt': {}, 'k3pf': {}, 'sqpw': {}, 'sqpar': {'36': '1', '45': '1'}, 'soathresh': {'6': '3', '8': '5', '13': '5', '17': '5', '23': '8'}}
if os.environ.get('GENCFG'):
    CONFIG.update(json.loads(os.environ['GENCFG']))
def cfg_pw(L): return CONFIG['pw'].get(str(L), 'sqrtnr')
def cfg_pf(L): return CONFIG['pf'].get(str(L), 0)
def cfg_hu(L): return int(CONFIG.get('hu', {}).get(str(L), 1))
def cfg_hm2(L): return int(CONFIG.get('hm2', {}).get(str(L), 0))
_SCHEME_DEFAULT = {6:'soa', 8:'soa', 13:'soa', 17:'soa', 23:'soa', 36:'sq', 45:'apfa2', 64:'sq'}
def cfg_scheme(L):
    return CONFIG.get('scheme', {}).get(str(L), _SCHEME_DEFAULT[L])
def r8(x): return (x + 7) // 8 * 8

HDR = r'''// AUTO-GENERATED by dev/gen.py -- batched iterated 3D complex-FFT kernels,
// fully specialized for cube sizes L in {6,8,13,17,23,36,45,64}.
//
// All transform arithmetic is our own (no FFT library):
//   - data is held in split re/im form; every kernel operates on 8-lane
//     AVX-512 vectors (gcc vector extensions), vectorizing across 8
//     independent 1D transforms (8 volumes for small L, 8 z/y-columns for
//     large L).
//   - 1D DFT cores: PFA(2x3) for 6, Cooley-Tukey(4x2) for 8, symmetric
//     "half-matrix" real-coefficient forms for primes 13/17/23 (k-quad
//     register blocking), PFA(4x9) for 36, PFA(9x5) for 45, CT(8x8) for 64,
//     with exact-twiddle tables rounded from long-double.
//   - iteration z = FFT3(x)+c ; x = z/(1+|z|) is fused: the final axis pass
//     applies +c and the pointwise map in its store stage. 1/(1+sqrt(s)) is
//     computed by vsqrtpd + rcp14+Newton or by rsqrt14/rcp14 Newton chains
//     (mixed per output to balance the divider and FMA ports); accuracy is
//     1-2 ulp, far inside the required tolerances.
//   - small L (6,8,13,17,23): SoA across 8 volumes, all m iterations run
//     L2-resident per group; remainder volumes fall back to a per-volume
//     slab scheme so tiny batches pay no lane waste.
//   - 36/64: square-CT "ping-pong" -- the x-axis FFT is split into two
//     radix-G stages fused around the (y,z) slab passes so each iteration
//     makes a single sweep over the volume (reads x and c once, writes x
//     once). 64's z-pass runs fully in registers (vertical fft8 stages +
//     one in-register 8x8 transpose, self-sorting).
//   - 45: the same idea with alternating PFA(9,5)/(5,9) factor order per
//     iteration (stage-2 output groups become the next iteration's stage-1
//     cosets).
// Only the natural-order complex128 ingest/extract touches the numpy
// buffers; everything in between lives in static padded split-format
// scratch that stays cache-resident across all m iterations of a volume.
#include <stdint.h>
#include <string.h>
#include <immintrin.h>
typedef double V __attribute__((vector_size(64), aligned(64)));
#define VC(x) ((V){(x),(x),(x),(x),(x),(x),(x),(x)})
static inline V vrsqrt14(V x){ return (V)_mm512_rsqrt14_pd((__m512d)x); }
static inline V vrcp14(V x){ return (V)_mm512_rcp14_pd((__m512d)x); }
static inline V vmaxv(V a, V b){ return (V)_mm512_max_pd((__m512d)a,(__m512d)b); }

static inline V vsqrtv(V x){ return (V)_mm512_sqrt_pd((__m512d)x); }
static inline __attribute__((always_inline)) V pw_sqrtnr(V zr, V zi){
  V s = zr*zr + zi*zi;
  V u = VC(1.0) + vsqrtv(s);
  V v = vrcp14(u);
  v = v + v*(VC(1.0) - u*v);
  v = v + v*(VC(1.0) - u*v);
  return v;
}
static inline __attribute__((always_inline)) V pw_newton(V zr, V zi){
  V s = zr*zr + zi*zi;
  s = vmaxv(s, VC(2.2250738585072014e-308));
  V r = vrsqrt14(s);
  V h = s * VC(0.5);
  r = r * (VC(1.5) - h*r*r);
  r = r * (VC(1.5) - h*r*r);
  V t = s * r;
  V u = VC(1.0) + t;
  V v = vrcp14(u);
  v = v + v*(VC(1.0) - u*v);
  v = v + v*(VC(1.0) - u*v);
  return v;
}

static inline __attribute__((always_inline)) void tr8x8(const V* a, V* b){
  V u0 = __builtin_shufflevector(a[0], a[1], 0, 8, 2, 10, 4, 12, 6, 14);
  V u1 = __builtin_shufflevector(a[0], a[1], 1, 9, 3, 11, 5, 13, 7, 15);
  V u2 = __builtin_shufflevector(a[2], a[3], 0, 8, 2, 10, 4, 12, 6, 14);
  V u3 = __builtin_shufflevector(a[2], a[3], 1, 9, 3, 11, 5, 13, 7, 15);
  V u4 = __builtin_shufflevector(a[4], a[5], 0, 8, 2, 10, 4, 12, 6, 14);
  V u5 = __builtin_shufflevector(a[4], a[5], 1, 9, 3, 11, 5, 13, 7, 15);
  V u6 = __builtin_shufflevector(a[6], a[7], 0, 8, 2, 10, 4, 12, 6, 14);
  V u7 = __builtin_shufflevector(a[6], a[7], 1, 9, 3, 11, 5, 13, 7, 15);
  V w0 = __builtin_shufflevector(u0, u2, 0, 1, 8, 9, 4, 5, 12, 13);
  V w1 = __builtin_shufflevector(u1, u3, 0, 1, 8, 9, 4, 5, 12, 13);
  V w2 = __builtin_shufflevector(u0, u2, 2, 3, 10, 11, 6, 7, 14, 15);
  V w3 = __builtin_shufflevector(u1, u3, 2, 3, 10, 11, 6, 7, 14, 15);
  V w4 = __builtin_shufflevector(u4, u6, 0, 1, 8, 9, 4, 5, 12, 13);
  V w5 = __builtin_shufflevector(u5, u7, 0, 1, 8, 9, 4, 5, 12, 13);
  V w6 = __builtin_shufflevector(u4, u6, 2, 3, 10, 11, 6, 7, 14, 15);
  V w7 = __builtin_shufflevector(u5, u7, 2, 3, 10, 11, 6, 7, 14, 15);
  b[0] = __builtin_shufflevector(w0, w4, 0, 1, 2, 3, 8, 9, 10, 11);
  b[1] = __builtin_shufflevector(w1, w5, 0, 1, 2, 3, 8, 9, 10, 11);
  b[2] = __builtin_shufflevector(w2, w6, 0, 1, 2, 3, 8, 9, 10, 11);
  b[3] = __builtin_shufflevector(w3, w7, 0, 1, 2, 3, 8, 9, 10, 11);
  b[4] = __builtin_shufflevector(w0, w4, 4, 5, 6, 7, 12, 13, 14, 15);
  b[5] = __builtin_shufflevector(w1, w5, 4, 5, 6, 7, 12, 13, 14, 15);
  b[6] = __builtin_shufflevector(w2, w6, 4, 5, 6, 7, 12, 13, 14, 15);
  b[7] = __builtin_shufflevector(w3, w7, 4, 5, 6, 7, 12, 13, 14, 15);
}
'''

def gen_soa(L, use_inst):
    THRESH = int(CONFIG.get('soathresh', {}).get(str(L), 5))
    K3PF = int(CONFIG.get('k3pf', {}).get(str(L), 0))
    pwfn_ = cfg_pw(L)
    if pwfn_ == 'alt':
        pwdef = '#define PW68SEL ((i & 1) ? pw_newton(zr, zi) : pw_sqrtnr(zr, zi))'
    else:
        pwdef = f'#define PW68SEL pw_{pwfn_}(zr, zi)'
    L2, L3 = L*L, L*L*L
    if use_inst:
        passz = f"f{L}_z(sr + y*{L}, si + y*{L}, sr + y*{L}, si + y*{L});"
        passy = f"f{L}_y(sr + z, si + z, sr + z, si + z);"
        passx = f"f{L}_x(soa{L}_xr + u, soa{L}_xi + u, soa{L}_xr + u, soa{L}_xi + u, soa{L}_cr + u, soa{L}_ci + u);"
    else:
        passz = f"fft{L}_core(sr + y*{L}, si + y*{L}, sr + y*{L}, si + y*{L}, 1, 1);"
        passy = f"fft{L}_core(sr + z, si + z, sr + z, si + z, {L}, {L});"
        pwbody = []
        for i in range(L):
            fn = ('pw_sqrtnr' if i % 2 == 0 else 'pw_newton') if cfg_pw(L) == 'alt' else 'pw_' + cfg_pw(L)
            pwbody.append(f"""          {{ long idx = u + {i}*{L2};
            V zr = tr[{i}] + soa{L}_cr[idx];
            V zi = ti[{i}] + soa{L}_ci[idx];
            V f = {fn}(zr, zi);
            soa{L}_xr[idx] = zr*f; soa{L}_xi[idx] = zi*f; }}""")
        pwb = chr(10).join(pwbody)
        passx = f"""{{
          V tr[{L}], ti[{L}];
          fft{L}_core(soa{L}_xr + u, soa{L}_xi + u, tr, ti, {L2}, 1);
{pwb}
        }}"""
    return f'''
{pwdef}
// ---------------- L={L} : SoA across 8 volumes ----------------
static V soa{L}_xr[{L3}], soa{L}_xi[{L3}], soa{L}_cr[{L3}], soa{L}_ci[{L3}];
static V soa{L}_or[{L3}], soa{L}_oi[{L3}];

static void soa{L}_grp(const double*restrict x0, const double*restrict c, long g0, int lanes, long m,
            double*restrict out1, double*restrict outm) {{
  {{
    for (long i = 0; i < {L3}; i++) {{
      V xr = VC(0.0), xi = VC(0.0), cr = VC(1.0), ci = VC(0.0);
      for (int l = 0; l < lanes; l++) {{
        long src = 2*((g0+l)*{L3} + i);
        xr[l] = x0[src]; xi[l] = x0[src+1];
        cr[l] = c[src];  ci[l] = c[src+1];
      }}
      soa{L}_xr[i] = xr; soa{L}_xi[i] = xi; soa{L}_cr[i] = cr; soa{L}_ci[i] = ci;
    }}
    for (long it = 0; it < m; it++) {{
      for (long x = 0; x < {L}; x++) {{
        V *sr = soa{L}_xr + x*{L2}, *si = soa{L}_xi + x*{L2};
        for (long y = 0; y < {L}; y++)
          {passz}
        for (long z = 0; z < {L}; z++)
          {passy}
      }}
      for (long u = 0; u < {L2}; u++) {{
        if ({K3PF} && (u & 7) == 0 && u + 8 < {L2}) {{
          for (long i = 0; i < {L}; i++) {{
            long a = u + 8 + i*{L2};
            __builtin_prefetch(soa{L}_xr + a, 1, 3); __builtin_prefetch(soa{L}_xi + a, 1, 3);
            __builtin_prefetch(soa{L}_cr + a, 0, 3); __builtin_prefetch(soa{L}_ci + a, 0, 3);
          }}
        }}
        {passx}
      }}
      if (it == 0) {{
        memcpy(soa{L}_or, soa{L}_xr, sizeof(soa{L}_or));
        memcpy(soa{L}_oi, soa{L}_xi, sizeof(soa{L}_oi));
      }}
    }}
    for (int l = 0; l < lanes; l++) {{
      double *d1 = out1 + 2*(g0+l)*{L3}, *dm = outm + 2*(g0+l)*{L3};
      for (long i = 0; i < {L3}; i++) {{
        d1[2*i] = soa{L}_or[i][l]; d1[2*i+1] = soa{L}_oi[i][l];
        dm[2*i] = soa{L}_xr[i][l]; dm[2*i+1] = soa{L}_xi[i][l];
      }}
    }}
  }}
}}

void run{L}(const double*restrict x0, const double*restrict c, long B, long m,
            double*restrict out1, double*restrict outm) {{
  long done = 0;
  while (B - done >= 8) {{ soa{L}_grp(x0, c, done, 8, m, out1, outm); done += 8; }}
  long rem = B - done;
  if (rem > 0) {{
    if (rem >= {THRESH})
      soa{L}_grp(x0, c, done, (int)rem, m, out1, outm);
    else
      for (long v = done; v < B; v++) slab{L}_one(x0, c, v, m, out1, outm);
  }}
}}
#undef PW68SEL
'''

def gen_slab(L):
    K3PF = int(CONFIG.get('k3pf', {}).get(str(L), 0))
    P1 = r8(L)
    P2 = L*P1 + (8 if L == 64 else 0)
    P1V, P2V = P1//8, P2//8
    NB = P1//8
    L3 = L*L*L
    return f'''
// ---------------- L={L} : per-volume slab scheme, always-natural (P1={P1}, P2={P2}) ----------------
static V slab{L}_xr[{L*P2V}], slab{L}_xi[{L*P2V}];
static V slab{L}_cer[{L*P2V}], slab{L}_cei[{L*P2V}];
static V slab{L}_1r[{L*P2V}], slab{L}_1i[{L*P2V}];
static V slab{L}_tsr[{P1*P1V}], slab{L}_tsi[{P1*P1V}];
static V slab{L}_br[2*{P1}], slab{L}_bi[2*{P1}];

static void slab{L}_iter(long m) {{
  for (long j = {L}; j < {P1}; j++) {{ slab{L}_br[j] = VC(0.0); slab{L}_bi[j] = VC(0.0);
    slab{L}_br[{P1}+j] = VC(0.0); slab{L}_bi[{P1}+j] = VC(0.0); }}
  for (long it = 0; it < m; it++) {{
    for (long x = 0; x < {L}; x++) {{
      V *sr = slab{L}_xr + x*{P2V}, *si = slab{L}_xi + x*{P2V};
      for (long cc = 0; cc < {NB}; cc++) {{
        V *br_ = slab{L}_br + (cc&1)*{P1}, *bi_ = slab{L}_bi + (cc&1)*{P1};
        f{L}_cb(sr + cc, si + cc, br_, bi_);
        for (long rb = 0; rb < {P1V}; rb++) {{
          V tb[8];
          tr8x8(br_ + rb*8, tb);
          for (int q = 0; q < 8; q++) slab{L}_tsr[(cc*8+q)*{P1V} + rb] = tb[q];
          tr8x8(bi_ + rb*8, tb);
          for (int q = 0; q < 8; q++) slab{L}_tsi[(cc*8+q)*{P1V} + rb] = tb[q];
        }}
      }}
      for (long cc = 0; cc < {NB}; cc++) {{
        V *br_ = slab{L}_br + (cc&1)*{P1}, *bi_ = slab{L}_bi + (cc&1)*{P1};
        f{L}_cb(slab{L}_tsr + cc, slab{L}_tsi + cc, br_, bi_);
        int lim = (int)({L} - cc*8); if (lim > 8) lim = 8;
        for (long rb = 0; rb < {P1V}; rb++) {{
          V tb[8];
          tr8x8(br_ + rb*8, tb);
          for (int q = 0; q < lim; q++) sr[(cc*8+q)*{P1V} + rb] = tb[q];
          tr8x8(bi_ + rb*8, tb);
          for (int q = 0; q < lim; q++) si[(cc*8+q)*{P1V} + rb] = tb[q];
        }}
      }}
    }}
    for (long o = 0; o < {L*P1V}; o++) {{
      if ({K3PF} && (o & 7) == 0 && o + 8 < {L*P1V}) {{
        for (long i = 0; i < {L}; i++) {{
          long a = o + 8 + i*{P2V};
          __builtin_prefetch(slab{L}_xr + a, 1, 3); __builtin_prefetch(slab{L}_xi + a, 1, 3);
          __builtin_prefetch(slab{L}_cer + a, 0, 3); __builtin_prefetch(slab{L}_cei + a, 0, 3);
        }}
      }}
      f{L}_k3(slab{L}_xr + o, slab{L}_xi + o, slab{L}_xr + o, slab{L}_xi + o,
              slab{L}_cer + o, slab{L}_cei + o);
    }}
    if (it == 0) {{
      memcpy(slab{L}_1r, slab{L}_xr, sizeof(slab{L}_1r));
      memcpy(slab{L}_1i, slab{L}_xi, sizeof(slab{L}_1i));
    }}
  }}
}}

static void slab{L}_extract(const V*restrict ar, const V*restrict ai, double*restrict dst) {{
  const double *r = (const double*)ar, *im = (const double*)ai;
  for (long x = 0; x < {L}; x++)
    for (long y = 0; y < {L}; y++) {{
      const long rowr = x*{P2} + y*{P1};
      double *d = dst + 2*((x*{L} + y)*{L});
      for (long z = 0; z < {L}; z++) {{
        d[2*z]   = r[rowr + z];
        d[2*z+1] = im[rowr + z];
      }}
    }}
}}

static void slab{L}_one(const double*restrict x0, const double*restrict c, long v, long m,
            double*restrict out1, double*restrict outm) {{
  double *xr = (double*)slab{L}_xr, *xi = (double*)slab{L}_xi;
  double *cer = (double*)slab{L}_cer, *cei = (double*)slab{L}_cei;
  {{
    const double *sx = x0 + 2*v*{L3}, *sc = c + 2*v*{L3};
    for (long x = 0; x < {L}; x++)
      for (long y = 0; y < {L}; y++) {{
        long row = x*{P2} + y*{P1};
        const double *px = sx + 2*((x*{L}+y)*{L});
        const double *pc = sc + 2*((x*{L}+y)*{L});
        for (long z = 0; z < {L}; z++) {{
          xr[row+z] = px[2*z]; xi[row+z] = px[2*z+1];
          cer[row+z] = pc[2*z]; cei[row+z] = pc[2*z+1];
        }}
        for (long z = {L}; z < {P1}; z++) {{
          xr[row+z] = 0.0; xi[row+z] = 0.0;
          cer[row+z] = 1.0; cei[row+z] = 0.0;
        }}
      }}
    slab{L}_iter(m);
    slab{L}_extract(slab{L}_1r, slab{L}_1i, out1 + 2*v*{L3});
    slab{L}_extract(slab{L}_xr, slab{L}_xi, outm + 2*v*{L3});
  }}
}}
'''





def gen_apfa2_45():
    PAR = int(CONFIG.get('sqpar', {}).get('45', 0))
    L = 45
    P1 = r8(L); P2 = L*P1
    P1V, P2V = P1//8, P2//8
    NB = P1//8
    L3 = L*L*L
    LP1V = L*P1V
    CRT = [ (10*k1 + 36*k2) % 45 for k1 in range(9) for k2 in range(5) ]   # CRT[k1*5+k2]
    TIN5 = [ (4*b) % 5 for b in range(5) ]
    TIN9 = [ (5*a) % 9 for a in range(9) ]
    IDXP = [ [ (5*a + 9*b) % 45 for a in range(9) ] for b in range(5) ]
    crt_tab = ",".join(str(v) for v in CRT)
    tin5 = ",".join(str(v) for v in TIN5)
    tin9 = ",".join(str(v) for v in TIN9)
    idxp_tab = ",".join(",".join(str(v) for v in row) for row in IDXP)
    return f"""
// ---------------- L=45 : alternating-PFA(9,5) single-sweep ping-pong ----------------
static const uint8_t a245_crt[45] = {{{crt_tab}}};
static const uint8_t a245_tin5[5] = {{{tin5}}};
static const uint8_t a245_tin9[9] = {{{tin9}}};
static const uint8_t a245_idxp[45] = {{{idxp_tab}}};
static V a245_sr[{L*P2V}], a245_si[{L*P2V}];   // A9 layout lives here
static V a245_dr[{L*P2V}], a245_di[{L*P2V}];   // natural / A5 layout
static V a245_cer[{L*P2V}], a245_cei[{L*P2V}];
static V a245_cor[{L*P2V}], a245_coi[{L*P2V}];
{f'static V a245_cer1[{L*P2V}], a245_cei1[{L*P2V}]; static V a245_cor1[{L*P2V}], a245_coi1[{L*P2V}];' if PAR else ''}
static V a245_1r[{L*P2V}], a245_1i[{L*P2V}];
static V a245_tr[{9*P2V}], a245_ti[{9*P2V}];
static V a245_buf_r[2*{P1}], a245_buf_i[2*{P1}];
static V a245ts_r[{P1*P1V}], a245ts_i[{P1*P1V}];

static void a245_yz(V* sr, V* si) {{
  for (long cc = 0; cc < {NB}; cc++) {{
    V *br_ = a245_buf_r + (cc&1)*{P1}, *bi_ = a245_buf_i + (cc&1)*{P1};
    f45_cb(sr + cc, si + cc, br_, bi_);
    for (long rb = 0; rb < {P1V}; rb++) {{
      V tb[8];
      tr8x8(br_ + rb*8, tb);
      for (int q = 0; q < 8; q++) a245ts_r[(cc*8+q)*{P1V} + rb] = tb[q];
      tr8x8(bi_ + rb*8, tb);
      for (int q = 0; q < 8; q++) a245ts_i[(cc*8+q)*{P1V} + rb] = tb[q];
    }}
  }}
{f'''  for (long cc = 0; cc < {NB}; cc++)
    f45_cbs(a245ts_r + cc, a245ts_i + cc, sr + cc, si + cc);
}}''' if PAR else f'''  for (long cc = 0; cc < {NB}; cc++) {{{{
    V *br_ = a245_buf_r + (cc&1)*{P1}, *bi_ = a245_buf_i + (cc&1)*{P1};
    f45_cb(a245ts_r + cc, a245ts_i + cc, br_, bi_);
    int lim = (int)({L} - cc*8); if (lim > 8) lim = 8;
    for (long rb = 0; rb < {P1V}; rb++) {{{{
      V tb[8];
      tr8x8(br_ + rb*8, tb);
      for (int q = 0; q < lim; q++) sr[(cc*8+q)*{P1V} + rb] = tb[q];
      tr8x8(bi_ + rb*8, tb);
      for (int q = 0; q < lim; q++) si[(cc*8+q)*{P1V} + rb] = tb[q];
    }}}}
  }}}}
}}'''}

void run45(const double*restrict x0, const double*restrict c, long B, long m,
           double*restrict out1, double*restrict outm) {{
  for (long j = {L}; j < {P1}; j++) {{ a245_buf_r[j] = VC(0.0); a245_buf_i[j] = VC(0.0);
    a245_buf_r[{P1}+j] = VC(0.0); a245_buf_i[{P1}+j] = VC(0.0); }}
  double *xr = (double*)a245_dr, *xi = (double*)a245_di;
  double *cer = (double*)a245_cer, *cei = (double*)a245_cei;
  double *cor = (double*)a245_cor, *coi = (double*)a245_coi;
  {f'double *cer1 = (double*)a245_cer1, *cei1 = (double*)a245_cei1; double *cor1 = (double*)a245_cor1, *coi1 = (double*)a245_coi1;' if PAR else ''}
  for (long v = 0; v < B; v++) {{
    const double *sx = x0 + 2*v*{L3}, *sc = c + 2*v*{L3};
    for (long x = 0; x < {L}; x++) {{
      long k1 = x % 9, k2 = x % 5;
      long xce = 5*k1 + k2;    // even-sweep c slot for logical slab x
      long xco = 9*k2 + k1;    // odd-sweep  c slot for logical slab x
      for (long y = 0; y < {L}; y++) {{
        long row = x*{P2} + y*{P1};
        long rowe = xce*{P2} + y*{P1}, rowo = xco*{P2} + y*{P1};
        const double *px = sx + 2*((x*{L}+y)*{L});
        const double *pc = sc + 2*((x*{L}+y)*{L});
        for (long z = 0; z < {L}; z++) {{
          xr[row+z] = px[2*z]; xi[row+z] = px[2*z+1];
          cer[rowe+z] = pc[2*z]; cei[rowe+z] = pc[2*z+1];
          cor[rowo+z] = pc[2*z]; coi[rowo+z] = pc[2*z+1];
          {f'cer1[xce*{P2} + z*{P1} + y] = pc[2*z]; cei1[xce*{P2} + z*{P1} + y] = pc[2*z+1]; cor1[xco*{P2} + z*{P1} + y] = pc[2*z]; coi1[xco*{P2} + z*{P1} + y] = pc[2*z+1];' if PAR else ''}
        }}
        for (long z = {L}; z < {P1}; z++) {{
          xr[row+z] = 0.0; xi[row+z] = 0.0;
          cer[rowe+z] = 1.0; cei[rowe+z] = 0.0;
          cor[rowo+z] = 1.0; coi[rowo+z] = 0.0;
          {f'cer1[rowe+z] = 1.0; cei1[rowe+z] = 0.0; cor1[rowo+z] = 1.0; coi1[rowo+z] = 0.0;' if PAR else ''}
        }}
      }}
    }}
    // prologue
    for (long s = 0; s < {L}; s++)
      a245_yz(a245_dr + s*{P2V}, a245_di + s*{P2V});
    for (long b = 0; b < 5; b++)
      f45o_s1(a245_dr, a245_di, a245_sr + b*{P2V}, a245_si + b*{P2V}, a245_idxp + 9*b);
    for (long t = 0; t < m-1; t++) {{
      if ((t & 1) == 0) {{
        for (long k1 = 0; k1 < 9; k1++) {{
          {f'const V *ecr = ((t+1) & 1) ? a245_cer1 : a245_cer, *eci = ((t+1) & 1) ? a245_cei1 : a245_cei;' if PAR else 'const V *ecr = a245_cer, *eci = a245_cei;'}
          f45e_s2(a245_sr + 5*k1*{P2V}, a245_si + 5*k1*{P2V}, ecr + 5*k1*{P2V}, eci + 5*k1*{P2V},
                  a245_tr, a245_ti, 0, {LP1V});
          if (t == 0) {{
            for (long k2 = 0; k2 < 5; k2++) {{
              long dst = (long)a245_crt[k1*5+k2];
              memcpy(a245_1r + dst*{P2V}, a245_tr + k2*{P2V}, {P2V}*sizeof(V));
              memcpy(a245_1i + dst*{P2V}, a245_ti + k2*{P2V}, {P2V}*sizeof(V));
            }}
          }}
          for (long k2 = 0; k2 < 5; k2++)
            a245_yz(a245_tr + k2*{P2V}, a245_ti + k2*{P2V});
          f45e_s1(a245_tr, a245_ti, a245_dr + ((2*k1) % 9)*{P2V}, a245_di + ((2*k1) % 9)*{P2V}, a245_tin5);
        }}
      }} else {{
        for (long k1p = 0; k1p < 5; k1p++) {{
          {f'const V *ocr = ((t+1) & 1) ? a245_cor1 : a245_cor, *oci = ((t+1) & 1) ? a245_coi1 : a245_coi;' if PAR else 'const V *ocr = a245_cor, *oci = a245_coi;'}
          f45o_s2(a245_dr + 9*k1p*{P2V}, a245_di + 9*k1p*{P2V}, ocr + 9*k1p*{P2V}, oci + 9*k1p*{P2V},
                  a245_tr, a245_ti, 0, {LP1V});
          for (long kq = 0; kq < 9; kq++)
            a245_yz(a245_tr + kq*{P2V}, a245_ti + kq*{P2V});
          f45o_s1(a245_tr, a245_ti, a245_sr + ((4*k1p) % 5)*{P2V}, a245_si + ((4*k1p) % 5)*{P2V}, a245_tin9);
        }}
      }}
    }}
    // epilogue for iteration m-1
    V *fr, *fi;
    if (((m-1) & 1) == 0) {{
      fr = a245_dr; fi = a245_di;
      {f'const V *ecr = (m & 1) ? a245_cer1 : a245_cer, *eci = (m & 1) ? a245_cei1 : a245_cei;' if PAR else 'const V *ecr = a245_cer, *eci = a245_cei;'}
      for (long k1 = 0; k1 < 9; k1++) {{
        f45e_s2(a245_sr + 5*k1*{P2V}, a245_si + 5*k1*{P2V}, ecr + 5*k1*{P2V}, eci + 5*k1*{P2V},
                a245_tr, a245_ti, 0, {LP1V});
        for (long k2 = 0; k2 < 5; k2++) {{
          long dst = (long)a245_crt[k1*5+k2];
          memcpy(fr + dst*{P2V}, a245_tr + k2*{P2V}, {P2V}*sizeof(V));
          memcpy(fi + dst*{P2V}, a245_ti + k2*{P2V}, {P2V}*sizeof(V));
        }}
      }}
    }} else {{
      fr = a245_sr; fi = a245_si;
      {f'const V *ocr = (m & 1) ? a245_cor1 : a245_cor, *oci = (m & 1) ? a245_coi1 : a245_coi;' if PAR else 'const V *ocr = a245_cor, *oci = a245_coi;'}
      for (long k1p = 0; k1p < 5; k1p++) {{
        f45o_s2(a245_dr + 9*k1p*{P2V}, a245_di + 9*k1p*{P2V}, ocr + 9*k1p*{P2V}, oci + 9*k1p*{P2V},
                a245_tr, a245_ti, 0, {LP1V});
        for (long kq = 0; kq < 9; kq++) {{
          long dst = (long)a245_crt[kq*5+k1p];
          memcpy(fr + dst*{P2V}, a245_tr + kq*{P2V}, {P2V}*sizeof(V));
          memcpy(fi + dst*{P2V}, a245_ti + kq*{P2V}, {P2V}*sizeof(V));
        }}
      }}
    }}
    {f'slab45x_extractp(m > 1 ? a245_1r : fr, m > 1 ? a245_1i : fi, out1 + 2*v*{L3}, 1);' if PAR else f'slab45x_extract(m > 1 ? a245_1r : fr, m > 1 ? a245_1i : fi, out1 + 2*v*{L3});'}
    {f'slab45x_extractp(fr, fi, outm + 2*v*{L3}, (int)(m & 1));' if PAR else f'slab45x_extract(fr, fi, outm + 2*v*{L3});'}
  }}
}}
"""

def gen_apfa45():
    PAR = 0
    L, P, Q = 45, 9, 5          # stage1 = 9pt over a ; stage2 = 5pt over b
    P1 = r8(L); P2 = L*P1
    P1V, P2V = P1//8, P2//8
    NB = P1//8
    L3 = L*L*L
    LP1V = L*P1V
    CRT = [ (10*k1 + 36*k2) % 45 for k1 in range(9) for k2 in range(5) ]   # [k1*5+k2]
    IDXS = [ (5*a) % 9 for a in range(9) ]
    IDXP = [ [ (5*a + 9*b) % 45 for a in range(9) ] for b in range(5) ]
    crt_tab = ",".join(str(v) for v in CRT)
    idxs_tab = ",".join(str(v) for v in IDXS)
    idxp_tab = ",".join(",".join(str(v) for v in row) for row in IDXP)
    return f"""
// ---------------- L=45 : asymmetric PFA(9,5) ping-pong (P1={P1}, P2={P2}) ----------------
static const uint8_t ap45_crt[45] = {{{crt_tab}}};
static const uint8_t ap45_idxs[9] = {{{idxs_tab}}};
static const uint8_t ap45_idxp[45] = {{{idxp_tab}}};
static V ap45_sr[{L*P2V}], ap45_si[{L*P2V}];
static V ap45_dr[{L*P2V}], ap45_di[{L*P2V}];
static V ap45_cr[{L*P2V}], ap45_ci[{L*P2V}];
static V ap45_1r[{L*P2V}], ap45_1i[{L*P2V}];
static V ap45_tr[{5*P2V}], ap45_ti[{5*P2V}];
static V ap45_buf_r[2*{P1}], ap45_buf_i[2*{P1}];
static V ap45ts_r[{P1*P1V}], ap45ts_i[{P1*P1V}];

static void ap45_yz(V* sr, V* si) {{
  for (long cc = 0; cc < {NB}; cc++) {{
    V *br_ = ap45_buf_r + (cc&1)*{P1}, *bi_ = ap45_buf_i + (cc&1)*{P1};
    f45_cb(sr + cc, si + cc, br_, bi_);
    for (long rb = 0; rb < {P1V}; rb++) {{
      V tb[8];
      tr8x8(br_ + rb*8, tb);
      for (int q = 0; q < 8; q++) ap45ts_r[(cc*8+q)*{P1V} + rb] = tb[q];
      tr8x8(bi_ + rb*8, tb);
      for (int q = 0; q < 8; q++) ap45ts_i[(cc*8+q)*{P1V} + rb] = tb[q];
    }}
  }}
  for (long cc = 0; cc < {NB}; cc++) {{
    V *br_ = ap45_buf_r + (cc&1)*{P1}, *bi_ = ap45_buf_i + (cc&1)*{P1};
    f45_cb(ap45ts_r + cc, ap45ts_i + cc, br_, bi_);
    int lim = (int)({L} - cc*8); if (lim > 8) lim = 8;
    for (long rb = 0; rb < {P1V}; rb++) {{
      V tb[8];
      tr8x8(br_ + rb*8, tb);
      for (int q = 0; q < lim; q++) sr[(cc*8+q)*{P1V} + rb] = tb[q];
      tr8x8(bi_ + rb*8, tb);
      for (int q = 0; q < lim; q++) si[(cc*8+q)*{P1V} + rb] = tb[q];
    }}
  }}
}}

void run45(const double*restrict x0, const double*restrict c, long B, long m,
           double*restrict out1, double*restrict outm) {{
  for (long j = {L}; j < {P1}; j++) {{ ap45_buf_r[j] = VC(0.0); ap45_buf_i[j] = VC(0.0);
    ap45_buf_r[{P1}+j] = VC(0.0); ap45_buf_i[{P1}+j] = VC(0.0); }}
  double *xr = (double*)ap45_dr, *xi = (double*)ap45_di;
  double *cr = (double*)ap45_cr, *ci = (double*)ap45_ci;
  for (long v = 0; v < B; v++) {{
    const double *sx = x0 + 2*v*{L3}, *sc = c + 2*v*{L3};
    for (long x = 0; x < {L}; x++) {{
      long k1 = x % 9, k2 = x % 5;
      long xc = 5*k1 + k2;             // c slot for logical slab x
      for (long y = 0; y < {L}; y++) {{
        long row = x*{P2} + y*{P1};
        long rowc = xc*{P2} + y*{P1};
        const double *px = sx + 2*((x*{L}+y)*{L});
        const double *pc = sc + 2*((x*{L}+y)*{L});
        for (long z = 0; z < {L}; z++) {{
          xr[row+z] = px[2*z]; xi[row+z] = px[2*z+1];
          cr[rowc+z] = pc[2*z]; ci[rowc+z] = pc[2*z+1];
          {f'c1r[xc*{P2} + z*{P1} + y] = pc[2*z]; c1i[xc*{P2} + z*{P1} + y] = pc[2*z+1];' if PAR else ''}
        }}
        for (long z = {L}; z < {P1}; z++) {{
          xr[row+z] = 0.0; xi[row+z] = 0.0;
          cr[rowc+z] = 1.0; ci[rowc+z] = 0.0;
          {f'c1r[row+z] = 1.0; c1i[row+z] = 0.0;' if PAR else ''}
        }}
      }}
    }}
    // prologue: yz all natural slabs in D, stage1 cosets D -> S
    for (long s = 0; s < {L}; s++)
      ap45_yz(ap45_dr + s*{P2V}, ap45_di + s*{P2V});
    for (long b = 0; b < 5; b++)
      f45_s1(ap45_dr, ap45_di, ap45_sr + b*{P2V}, ap45_si + b*{P2V}, ap45_idxp + 9*b);
    for (long t = 0; t < m-1; t++) {{
      for (long k1 = 0; k1 < 9; k1++) {{
        f45_s2d(ap45_sr + 5*k1*{P2V}, ap45_si + 5*k1*{P2V}, ap45_cr + 5*k1*{P2V}, ap45_ci + 5*k1*{P2V},
                ap45_dr + k1*{P2V}, ap45_di + k1*{P2V}, 0, {LP1V});
        if (t == 0) {{
          for (long k2 = 0; k2 < 5; k2++) {{
            long dst = (long)ap45_crt[k1*5+k2];
            memcpy(ap45_1r + dst*{P2V}, ap45_dr + (9*k2+k1)*{P2V}, {P2V}*sizeof(V));
            memcpy(ap45_1i + dst*{P2V}, ap45_di + (9*k2+k1)*{P2V}, {P2V}*sizeof(V));
          }}
        }}
        for (long k2 = 0; k2 < 5; k2++)
          ap45_yz(ap45_dr + (9*k2+k1)*{P2V}, ap45_di + (9*k2+k1)*{P2V});
      }}
      for (long b = 0; b < 5; b++)
        f45_s1(ap45_dr + 9*((4*b) % 5)*{P2V}, ap45_di + 9*((4*b) % 5)*{P2V},
               ap45_sr + b*{P2V}, ap45_si + b*{P2V}, ap45_idxs);
    }}
    // epilogue: stage2+pw -> T, scatter to natural D
    for (long k1 = 0; k1 < 9; k1++) {{
      f45_s2t(ap45_sr + 5*k1*{P2V}, ap45_si + 5*k1*{P2V}, ap45_cr + 5*k1*{P2V}, ap45_ci + 5*k1*{P2V},
              ap45_tr, ap45_ti, 0, {LP1V});
      for (long k2 = 0; k2 < 5; k2++) {{
        long dst = (long)ap45_crt[k1*5+k2];
        memcpy(ap45_dr + dst*{P2V}, ap45_tr + k2*{P2V}, {P2V}*sizeof(V));
        memcpy(ap45_di + dst*{P2V}, ap45_ti + k2*{P2V}, {P2V}*sizeof(V));
      }}
    }}
    slab45x_extract(m > 1 ? ap45_1r : ap45_dr, m > 1 ? ap45_1i : ap45_di, out1 + 2*v*{L3});
    slab45x_extract(ap45_dr, ap45_di, outm + 2*v*{L3});
  }}
}}
"""


def gen_sq_extractp(L):
    P1 = r8(L)
    P2 = L*P1 + (8 if L == 64 else 0)
    return f"""
static void slab{L}_extractp(const V*restrict ar, const V*restrict ai, double*restrict dst, int parity) {{
  const double *r = (const double*)ar, *im = (const double*)ai;
  for (long x = 0; x < {L}; x++)
    for (long y = 0; y < {L}; y++) {{
      const long rowr = x*{P2} + (parity ? y : y*{P1});
      const long step = parity ? {P1} : 1;
      double *d = dst + 2*((x*{L} + y)*{L});
      for (long z = 0; z < {L}; z++) {{
        d[2*z]   = r[rowr + z*step];
        d[2*z+1] = im[rowr + z*step];
      }}
    }}
}}
"""

def gen_sq_extract(L):
    P1 = r8(L)
    P2 = L*P1 + (8 if L == 64 else 0)
    L3 = L*L*L
    return f"""
static void slab{L}_extract(const V*restrict ar, const V*restrict ai, double*restrict dst) {{
  const double *r = (const double*)ar, *im = (const double*)ai;
  for (long x = 0; x < {L}; x++)
    for (long y = 0; y < {L}; y++) {{
      const long rowr = x*{P2} + y*{P1};
      double *d = dst + 2*((x*{L} + y)*{L});
      for (long z = 0; z < {L}; z++) {{
        d[2*z]   = r[rowr + z];
        d[2*z+1] = im[rowr + z];
      }}
    }}
}}
"""

def gen_sq(L, G):
    FZ64 = int(CONFIG.get('fz64', '0'))
    PAR = int(CONFIG.get('sqpar', {}).get(str(L), 0))
    PFON = int(CONFIG.get('sqpf',{}).get(str(L), 1))
    SLICE = (L * r8(L)//8) // G
    DPF = int(CONFIG.get('dpf', {}).get(str(L), 0))
    DPF_ON = 1 if DPF else 0
    DPF = DPF if DPF else 64
    P1 = r8(L)
    P2 = L*P1 + (8 if L == 64 else 0)
    P1V, P2V = P1//8, P2//8
    NB = P1//8
    L3 = L*L*L
    LP1V = L*P1V
    from codelets import tw, hexf
    twr = []; twi = []
    for g in range(G):
        for k1 in range(G):
            c, s = tw(g*k1, L)
            twr.append(c); twi.append(s)
    twtabs = (f"static const double sq{L}_twr[{G*G}] = {{{','.join(hexf(v) for v in twr)}}};\n"
              f"static const double sq{L}_twi[{G*G}] = {{{','.join(hexf(v) for v in twi)}}};\n")
    if L == 64:
        twtabs += f'''static void sq64_yz(V* sr, V* si) {{
  for (long y = 0; y < 64; y++)
    f64_zline(sr + y*{P1V}, si + y*{P1V});
  for (long cc = 0; cc < {P1V}; cc++)
    f64_ycol(sr + cc, si + cc, sr + cc, si + cc);
}}
#define SQ64_YZ_DEFINED
'''
    return twtabs + f"""
// ---------------- L={L} : square-CT fused ping-pong (G={G}, P1={P1}, P2={P2}) ----------------
static V sq{L}_ar[{L*P2V}], sq{L}_ai[{L*P2V}];
static V sq{L}_br[{L*P2V}], sq{L}_bi[{L*P2V}];
static V sq{L}_cr[{L*P2V}], sq{L}_ci[{L*P2V}];
{f'static V sq{L}_c1r[{L*P2V}], sq{L}_c1i[{L*P2V}];' if PAR else ''}
static V sq{L}_1r[{L*P2V}], sq{L}_1i[{L*P2V}];
static V sq{L}_tr[{2*G*P2V}], sq{L}_ti[{2*G*P2V}];
static V sq{L}_buf_r[2*{P1}], sq{L}_buf_i[2*{P1}];

#ifndef SQ64_YZ_DEFINED
static void sq{L}_yz(V* sr, V* si) {{
  for (long cc = 0; cc < {NB}; cc++) {{
    V *br_ = sq{L}_buf_r + (cc&1)*{P1}, *bi_ = sq{L}_buf_i + (cc&1)*{P1};
    f{L}_cb(sr + cc, si + cc, br_, bi_);
    for (long rb = 0; rb < {P1V}; rb++) {{
      V tb[8];
      tr8x8(br_ + rb*8, tb);
      for (int q = 0; q < 8; q++) slabts{L}_r[(cc*8+q)*{P1V} + rb] = tb[q];
      tr8x8(bi_ + rb*8, tb);
      for (int q = 0; q < 8; q++) slabts{L}_i[(cc*8+q)*{P1V} + rb] = tb[q];
    }}
  }}
{("  for (long cc = 0; cc < " + str(NB) + "; cc++)" + chr(10) + "    f" + str(L) + "_cbs(slabts" + str(L) + "_r + cc, slabts" + str(L) + "_i + cc, sr + cc, si + cc);") if PAR else f"""  for (long cc = 0; cc < {NB}; cc++) {{{{
    V *br_ = sq{L}_buf_r + (cc&1)*{P1}, *bi_ = sq{L}_buf_i + (cc&1)*{P1};
    f{L}_cb(slabts{L}_r + cc, slabts{L}_i + cc, br_, bi_);
    int lim = (int)({L} - cc*8); if (lim > 8) lim = 8;
    for (long rb = 0; rb < {P1V}; rb++) {{{{
      V tb[8];
      tr8x8(br_ + rb*8, tb);
      for (int q = 0; q < lim; q++) sr[(cc*8+q)*{P1V} + rb] = tb[q];
      tr8x8(bi_ + rb*8, tb);
      for (int q = 0; q < lim; q++) si[(cc*8+q)*{P1V} + rb] = tb[q];
    }}}}
  }}}}"""}
}}
#endif
#undef SQ64_YZ_DEFINED

void run{L}(const double*restrict x0, const double*restrict c, long B, long m,
            double*restrict out1, double*restrict outm) {{
  for (long j = {L}; j < {P1}; j++) {{ sq{L}_buf_r[j] = VC(0.0); sq{L}_buf_i[j] = VC(0.0);
    sq{L}_buf_r[{P1}+j] = VC(0.0); sq{L}_buf_i[{P1}+j] = VC(0.0); }}
  double *xr = (double*)sq{L}_ar, *xi = (double*)sq{L}_ai;
  double *cr = (double*)sq{L}_cr, *ci = (double*)sq{L}_ci;
  {f'double *c1r = (double*)sq{L}_c1r, *c1i = (double*)sq{L}_c1i;' if PAR else ''}
  for (long v = 0; v < B; v++) {{
    const double *sx = x0 + 2*v*{L3}, *sc = c + 2*v*{L3};
    for (long x = 0; x < {L}; x++) {{
      long xc = (x % {G})*{G} + (x / {G});   // c permuted: phys G*g+k2 holds logical G*k2+g
      for (long y = 0; y < {L}; y++) {{
        long row = x*{P2} + y*{P1};
        long rowc = xc*{P2} + y*{P1};
        const double *px = sx + 2*((x*{L}+y)*{L});
        const double *pc = sc + 2*((x*{L}+y)*{L});
        for (long z = 0; z < {L}; z++) {{
          xr[row+z] = px[2*z]; xi[row+z] = px[2*z+1];
          cr[rowc+z] = pc[2*z]; ci[rowc+z] = pc[2*z+1];
          {f'c1r[xc*{P2} + z*{P1} + y] = pc[2*z]; c1i[xc*{P2} + z*{P1} + y] = pc[2*z+1];' if PAR else ''}
        }}
        for (long z = {L}; z < {P1}; z++) {{
          xr[row+z] = 0.0; xi[row+z] = 0.0;
          cr[rowc+z] = 1.0; ci[rowc+z] = 0.0;
          {f'c1r[row+z] = 1.0; c1i[row+z] = 0.0;' if PAR else ''}
        }}
      }}
    }}
    // prologue: yz on all slabs (natural), then stage1 cosets (strided) -> B
    for (long s = 0; s < {L}; s++)
      sq{L}_yz(sq{L}_ar + s*{P2V}, sq{L}_ai + s*{P2V});
    for (long s = 0; s < {G}; s++)
      f{L}_s1p(sq{L}_ar + s*{P2V}, sq{L}_ai + s*{P2V}, sq{L}_br + s*{P2V}, sq{L}_bi + s*{P2V},
               sq{L}_twr + s*{G}, sq{L}_twi + s*{G});
    V *srcr = sq{L}_br, *srci = sq{L}_bi, *dstr = sq{L}_ar, *dsti = sq{L}_ai;
    V *TAr = sq{L}_tr, *TAi = sq{L}_ti, *TBr = sq{L}_tr + {G*P2V}, *TBi = sq{L}_ti + {G*P2V};
    for (long t = 0; t < m-1; t++) {{
      for (long g = 0; g < {G}; g++) {{
        {f'const V *pwcr = ((t+1) & 1) ? sq{L}_c1r : sq{L}_cr;' if PAR else f'const V *pwcr = sq{L}_cr;'}
        {f'const V *pwci = ((t+1) & 1) ? sq{L}_c1i : sq{L}_ci;' if PAR else f'const V *pwci = sq{L}_ci;'}
        {f'''if ({FZ64} && t > 0) {{{{
          f64_s2z(srcr + g*{G}*{P2V}, srci + g*{G}*{P2V}, pwcr + g*{G}*{P2V}, pwci + g*{G}*{P2V}, TAr, TAi);
          for (long k2 = 0; k2 < {G}; k2++)
            for (long cc = 0; cc < {P1V}; cc++)
              f64_ycol(TAr + k2*{P2V} + cc, TAi + k2*{P2V} + cc, TAr + k2*{P2V} + cc, TAi + k2*{P2V} + cc);
        }}}} else {{{{
          f{L}_s2(srcr + g*{G}*{P2V}, srci + g*{G}*{P2V}, pwcr + g*{G}*{P2V}, pwci + g*{G}*{P2V},
                  TAr, TAi, 0, {LP1V});
          if (t == 0) {{{{
            for (long k2 = 0; k2 < {G}; k2++) {{{{
              memcpy(sq{L}_1r + ({G}*k2+g)*{P2V}, TAr + k2*{P2V}, {P2V}*sizeof(V));
              memcpy(sq{L}_1i + ({G}*k2+g)*{P2V}, TAi + k2*{P2V}, {P2V}*sizeof(V));
            }}}}
          }}}}
          for (long k2 = 0; k2 < {G}; k2++)
            sq{L}_yz(TAr + k2*{P2V}, TAi + k2*{P2V});
        }}}}''' if L == 64 else f'''f{L}_s2(srcr + g*{G}*{P2V}, srci + g*{G}*{P2V}, pwcr + g*{G}*{P2V}, pwci + g*{G}*{P2V},
                TAr, TAi, 0, {LP1V});
        if (t == 0) {{{{
          for (long k2 = 0; k2 < {G}; k2++) {{{{
            memcpy(sq{L}_1r + ({G}*k2+g)*{P2V}, TAr + k2*{P2V}, {P2V}*sizeof(V));
            memcpy(sq{L}_1i + ({G}*k2+g)*{P2V}, TAi + k2*{P2V}, {P2V}*sizeof(V));
          }}}}
        }}}}
        for (long k2 = 0; k2 < {G}; k2++)
          sq{L}_yz(TAr + k2*{P2V}, TAi + k2*{P2V});'''}
        f{L}_s1(TAr, TAi, dstr + g*{P2V}, dsti + g*{P2V}, sq{L}_twr + g*{G}, sq{L}_twi + g*{G});
      }}
      V *tmp;
      tmp = srcr; srcr = dstr; dstr = tmp;
      tmp = srci; srci = dsti; dsti = tmp;
    }}
    // epilogue: stage2 + pw -> natural into dst
    for (long g = 0; g < {G}; g++)
      f{L}_s2e(srcr + g*{G}*{P2V}, srci + g*{G}*{P2V},
               {f'((m & 1) ? sq{L}_c1r : sq{L}_cr)' if PAR else f'sq{L}_cr'} + g*{G}*{P2V},
               {f'((m & 1) ? sq{L}_c1i : sq{L}_ci)' if PAR else f'sq{L}_ci'} + g*{G}*{P2V},
               dstr + g*{P2V}, dsti + g*{P2V}, 0, {LP1V});
    slab{L}_extract{'p' if PAR else ''}(m > 1 ? sq{L}_1r : dstr, m > 1 ? sq{L}_1i : dsti, out1 + 2*v*{L3}{', 1' if PAR else ''});
    slab{L}_extract{'p' if PAR else ''}(dstr, dsti, outm + 2*v*{L3}{', (int)(m & 1)' if PAR else ''});
  }}
}}
"""

def main():
    kernels.reset()
    parts = [HDR]
    for L in SIZES:
        if cfg_scheme(L) == 'soa':
            P1 = r8(L); P2 = L*P1
            parts.append(kernels.gen_inst(L, f"f{L}_cb", P1//8, 1, False))
            parts.append(kernels.gen_inst(L, f"f{L}_k3", P2//8, P2//8, True, pwfn="pw_"+("sqrtnr" if cfg_pw(L) in ("sqrtnr","newton") else "alt")))
            parts.append(gen_slab(L))
            if L in (13, 17, 23, 36, 45, 64):
                parts.append(kernels.gen_halfmatrix2_inst(L, f"f{L}_z", 1, 1, False) if cfg_hm2(L) else kernels.gen_inst(L, f"f{L}_z", 1, 1, False, HU=cfg_hu(L)))
                parts.append(kernels.gen_halfmatrix2_inst(L, f"f{L}_y", L, L, False) if cfg_hm2(L) else kernels.gen_inst(L, f"f{L}_y", L, L, False, HU=cfg_hu(L)))
                parts.append(kernels.gen_halfmatrix2_inst(L, f"f{L}_x", L*L, L*L, True, pwfn="pw_"+cfg_pw(L)) if cfg_hm2(L) else kernels.gen_inst(L, f"f{L}_x", L*L, L*L, True, PF=cfg_pf(L), pwfn="pw_"+cfg_pw(L), HU=cfg_hu(L)))
                parts.append(gen_soa(L, True))
            else:
                code, _ = codelets.gen_core(L)
                parts.append(code)
                parts.append(gen_soa(L, False))
        elif cfg_scheme(L) == 'sq':
            G = {36:6, 64:8}[L]
            P1 = r8(L); P2 = L*P1 + (8 if L == 64 else 0)
            P1V, P2V = P1//8, P2//8
            parts.append(f"static V slabts{L}_r[{P1*P1V}], slabts{L}_i[{P1*P1V}];")
            if L == 64:
                parts.append(kernels.gen_zline64("f64_zline"))
                parts.append(kernels.gen_inst(64, "f64_ycol", P1V, P1V, False))
                parts.append(kernels.gen_sq_stage2_fz64("f64_s2z", P2V, P2V, PWPAT=CONFIG.get("sqpw",{}).get("64","sn")))
            if int(CONFIG.get('sqpar', {}).get(str(L), 0)):
                parts.append(kernels.gen_inst(L, f"f{L}_cbs", P1V, P1V, False))
                parts.append(gen_sq_extractp(L))
            parts.append(kernels.gen_inst(L, f"f{L}_cb", P1V, 1, False, INL=int(CONFIG.get("inl",{}).get(str(L),0))))
            parts.append(kernels.gen_sq_stage2(L, G, f"f{L}_s2", P2V, L*P1V, P2V, PF=cfg_pf(L), PWPAT=CONFIG.get("sqpw",{}).get(str(L),"sn")))
            parts.append(kernels.gen_sq_stage2(L, G, f"f{L}_s2e", P2V, L*P1V, G*P2V, PF=cfg_pf(L), PWPAT=CONFIG.get("sqpw",{}).get(str(L),"sn")))
            parts.append(kernels.gen_sq_stage1(L, G, f"f{L}_s1", P2V, P2V, L*P1V, PF=0, NT=int(CONFIG.get("nt",{}).get(str(L),0))))
            parts.append(kernels.gen_sq_stage1(L, G, f"f{L}_s1p", G*P2V, P2V, L*P1V, PF=cfg_pf(L)))
            parts.append(gen_sq_extract(L))
            parts.append(gen_sq(L, G))
        elif cfg_scheme(L) == 'apfa2':
            assert L == 45
            P1 = r8(45); P2 = 45*P1
            P1V, P2V = P1//8, P2//8
            parts.append(kernels.gen_inst(45, "f45_cb", P1V, 1, False, INL=int(CONFIG.get("inl",{}).get("45",0))))
            if int(CONFIG.get('sqpar', {}).get('45', 0)):
                parts.append(kernels.gen_inst(45, "f45_cbs", P1V, P1V, False))
                parts.append(gen_sq_extractp(45).replace("slab45_extractp", "slab45x_extractp"))
            parts.append(kernels.gen_sq_stage2(45, 5, "f45e_s2", P2V, 45*P1V, P2V, PF=0, PWPAT=CONFIG.get("sqpw",{}).get("45","sn")))
            parts.append(kernels.gen_sq_stage2(45, 9, "f45o_s2", P2V, 45*P1V, P2V, PF=0, PWPAT=CONFIG.get("sqpw",{}).get("45","sn")))
            parts.append(kernels.gen_pfa_stage1_tab(45, 5, "f45e_s1", P2V, 45*P1V, 9*P2V))
            parts.append(kernels.gen_pfa_stage1_tab(45, 9, "f45o_s1", P2V, 45*P1V, 5*P2V))
            parts.append(gen_sq_extract(45).replace("slab45_extract", "slab45x_extract"))
            parts.append(gen_apfa2_45())
        elif cfg_scheme(L) == 'apfa':
            assert L == 45
            P1 = r8(45); P2 = 45*P1
            P1V, P2V = P1//8, P2//8
            parts.append(kernels.gen_inst(45, "f45_cb", P1V, 1, False, INL=int(CONFIG.get("inl",{}).get("45",0))))
            parts.append(kernels.gen_sq_stage2(45, 5, "f45_s2d", P2V, 45*P1V, 9*P2V, PF=cfg_pf(45)))
            parts.append(kernels.gen_sq_stage2(45, 5, "f45_s2t", P2V, 45*P1V, P2V, PF=0))
            parts.append(kernels.gen_pfa_stage1_tab(45, 9, "f45_s1", P2V, 45*P1V, 5*P2V))
            parts.append(gen_sq_extract(45).replace("slab45_extract", "slab45x_extract"))
            parts.append(gen_apfa45())
        else:
            P1 = r8(L); P2 = L*P1 + (8 if L == 64 else 0)
            parts.append(kernels.gen_inst(L, f"f{L}_cb", P1//8, 1, False, HU=cfg_hu(L)))
            parts.append(kernels.gen_inst(L, f"f{L}_k3", P2//8, P2//8, True, PF=cfg_pf(L), pwfn="pw_"+cfg_pw(L), HU=cfg_hu(L)))
            parts.append(gen_slab(L))
    src = "\n".join(parts)
    # page-fault warmup of all static V arrays at dlopen (import time, untimed)
    import re as _re
    names = []
    for m in _re.finditer(r"static V (\w+)\[", src):
        if m.group(1) not in names:
            names.append(m.group(1))
    warm = "\n".join(f"  memset({n}, 0, sizeof({n}));" for n in names)
    src += f"\n__attribute__((constructor)) static void _warm_bss(void) {{\n{warm}\n}}\n"
    open("../implementation.c", "w").write(src)
    print(f"wrote implementation.c: {len(src.splitlines())} lines ({len(names)} arrays warmed)")

if __name__ == "__main__":
    main()
