/* L13_dmma -- L = 13 on one A100.
 *
 * Technique (round gpu_r1): fused single kernel, one 13^3 volume per block in shared
 * memory (35,152 B, natural stride 13 is odd so every pass is bank-conflict-free), one
 * thread per 13-point line, three axis passes separated by __syncthreads(), one global
 * read + one global write per volume. The line transform is the conjugate-symmetric
 * folded dense matvec from the CPU phase's L13_direct winner:
 *
 *     u_j = x_j + x_{13-j},  v_j = x_j - x_{13-j}            (j = 1..6)
 *     P_k = x_0 + sum_j cos(2 pi k j/13) u_j
 *     S_k =       sum_j sin(2 pi k j/13) v_j                 (k = 1..6)
 *     X_0 = x_0 + sum_j u_j,   X_k = P_k - i S_k,   X_{13-k} = P_k + i S_k
 *
 * ~29 real flop/point/axis: at B_HBM the arithmetic sits at ~0.6x the HBM floor on the
 * vanilla FP64 pipe, so DMMA (the entry's namesake) is held in reserve -- see the
 * strategy record for the arithmetic and the conditions under which it would pay.
 *
 * The x-axis pass reads shared and writes its results directly to global (coalesced:
 * fixed k, consecutive threads hit consecutive complex doubles), saving one full
 * shared-memory round trip of the volume.
 */
#include <cuda_runtime.h>
#include <stdlib.h>

#include "../fft3d_gpu_api.h"

#define NPT   2197   /* 13^3 */
#define NLINE 169    /* 13^2 lines per axis */
#define TPB   192    /* 6 warps; 169 compute, all 192 load */

/* cos/sin(2 pi k j / 13), k,j = 1..6, folded through the residue (k*j mod 13) so
 * identical coefficients are bit-identical. Generated by numpy at 17 digits. */
static __constant__ double CT[6][6] = {
    {+8.85456025653209911e-01, +5.68064746731155923e-01, +1.20536680255323006e-01, -3.54604887042535455e-01, -7.48510748171101192e-01, -9.70941817426052012e-01},
    {+5.68064746731155923e-01, -3.54604887042535455e-01, -9.70941817426052012e-01, -7.48510748171101192e-01, +1.20536680255323006e-01, +8.85456025653209911e-01},
    {+1.20536680255323006e-01, -9.70941817426052012e-01, -3.54604887042535455e-01, +8.85456025653209911e-01, +5.68064746731155923e-01, -7.48510748171101192e-01},
    {-3.54604887042535455e-01, -7.48510748171101192e-01, +8.85456025653209911e-01, +1.20536680255323006e-01, -9.70941817426052012e-01, +5.68064746731155923e-01},
    {-7.48510748171101192e-01, +1.20536680255323006e-01, +5.68064746731155923e-01, -9.70941817426052012e-01, +8.85456025653209911e-01, -3.54604887042535455e-01},
    {-9.70941817426052012e-01, +8.85456025653209911e-01, -7.48510748171101192e-01, +5.68064746731155923e-01, -3.54604887042535455e-01, +1.20536680255323006e-01},
};
static __constant__ double ST[6][6] = {
    {+4.64723172043768507e-01, +8.22983865893656352e-01, +9.92708874098053973e-01, +9.35016242685414833e-01, +6.63122658240795193e-01, +2.39315664287557683e-01},
    {+8.22983865893656352e-01, +9.35016242685414833e-01, +2.39315664287557683e-01, -6.63122658240795193e-01, -9.92708874098053973e-01, -4.64723172043768507e-01},
    {+9.92708874098053973e-01, +2.39315664287557683e-01, -9.35016242685414833e-01, -4.64723172043768507e-01, +8.22983865893656352e-01, +6.63122658240795193e-01},
    {+9.35016242685414833e-01, -6.63122658240795193e-01, -4.64723172043768507e-01, +9.92708874098053973e-01, -2.39315664287557683e-01, -8.22983865893656352e-01},
    {+6.63122658240795193e-01, -9.92708874098053973e-01, +8.22983865893656352e-01, -2.39315664287557683e-01, -4.64723172043768507e-01, +9.35016242685414833e-01},
    {+2.39315664287557683e-01, -4.64723172043768507e-01, +6.63122658240795193e-01, -8.22983865893656352e-01, +9.35016242685414833e-01, -9.92708874098053973e-01},
};

/* One 13-point line: read src[0..12]*S, write dst[0..12]*S. Fold on load so only
 * u, v, x0 and four accumulators are live -- the register budget for 4 blocks/SM. */
template <int S>
__device__ __forceinline__ void dft13(const double2 *__restrict__ src,
                                      double2 *__restrict__ dst)
{
    double ur[6], ui[6], vr[6], vi[6];
    const double2 x0 = src[0];
#pragma unroll
    for (int j = 1; j <= 6; ++j) {
        const double2 a = src[j * S];
        const double2 b = src[(13 - j) * S];
        ur[j - 1] = a.x + b.x;
        ui[j - 1] = a.y + b.y;
        vr[j - 1] = a.x - b.x;
        vi[j - 1] = a.y - b.y;
    }
    double ar = x0.x, ai = x0.y;
#pragma unroll
    for (int j = 0; j < 6; ++j) { ar += ur[j]; ai += ui[j]; }
    dst[0] = make_double2(ar, ai);
#pragma unroll
    for (int k = 1; k <= 6; ++k) {
        double pr = x0.x, pi = x0.y, sr = 0.0, si = 0.0;
#pragma unroll
        for (int j = 0; j < 6; ++j) {
            pr = fma(CT[k - 1][j], ur[j], pr);
            pi = fma(CT[k - 1][j], ui[j], pi);
            sr = fma(ST[k - 1][j], vr[j], sr);
            si = fma(ST[k - 1][j], vi[j], si);
        }
        dst[k * S]        = make_double2(pr + si, pi - sr);
        dst[(13 - k) * S] = make_double2(pr - si, pi + sr);
    }
}

__global__ void __launch_bounds__(TPB, 4)
fft13_fused(const double2 *__restrict__ in, double2 *__restrict__ out)
{
    __shared__ double2 s[NPT];
    const int t = threadIdx.x;
    const size_t vbase = (size_t)blockIdx.x * NPT;

    /* Stage the volume through shared with the classic interleaved-coalesced pattern
     * (per-thread contiguous z-line reads measured 8% slower end-to-end: 1244 GB/s
     * against 1355 GB/s at B_HBM -- sector waste against a 28 KB L1). 169 threads x
     * 13 unrolled iterations covers 2197 exactly: no bounds check, 13 loads in flight. */
    if (t < NLINE) {
#pragma unroll
        for (int k = 0; k < 13; ++k) s[t + k * NLINE] = in[vbase + t + k * NLINE];
    }
    __syncthreads();

    if (t < NLINE) dft13<1>(s + t * 13, s + t * 13);           /* z: stride 1   */
    __syncthreads();
    if (t < NLINE) {                                           /* y: stride 13  */
        double2 *p = s + (t / 13) * 169 + (t % 13);
        dft13<13>(p, p);
    }
    __syncthreads();
    if (t < NLINE)                                             /* x: stride 169, write global */
        dft13<169>(s + t, out + vbase + t);
}

struct fft3d_gpu_plan { int L; int batch; };

extern "C" const char *fft3d_gpu_name(void) { return "L13_dmma"; }
extern "C" const char *fft3d_gpu_description(void)
{ return "fused block-per-volume in shared, conj-symmetric folded dense-13 per thread-line"; }
extern "C" int fft3d_gpu_supports(int L) { return L == 13; }

extern "C" fft3d_gpu_plan *fft3d_gpu_create(int L, int batch)
{
    if (L != 13 || batch < 1) return NULL;
    /* 4 blocks/SM wants 4 x 35,152 B resident: ask for the full shared carveout. */
    cudaFuncSetAttribute(fft13_fused, cudaFuncAttributePreferredSharedMemoryCarveout, 100);
    fft3d_gpu_plan *p = (fft3d_gpu_plan *)malloc(sizeof *p);
    if (!p) return NULL;
    p->L = L;
    p->batch = batch;
    return p;
}

extern "C" void fft3d_gpu_execute(fft3d_gpu_plan *p, const double2 *in, double2 *out)
{
    fft13_fused<<<p->batch, TPB>>>(in, out);
}

extern "C" void fft3d_gpu_destroy(fft3d_gpu_plan *p) { free(p); }
