#!/usr/bin/env python3
"""Regenerate implementation.c exactly as the graded attempt did (log 03:03:02Z):

    gen2.RADER_SET.update({13,17})
    src = gen2.generate_v6(gsizes=(6,8,13,17,23,36,45),
                           gmap={L:'ALT' for L in (6,8,13,17,23,36,45)})
    implementation.c = <header comment> + '\n' + src

The header block below is the one the attempt wrote at 02:38:40Z and carried
forward via hdr[:hdr.index('*/')+2] + '\n' in every later regeneration.

Requires: python3 + mpmath (pure Python).  Run from anywhere; gen2.py is
loaded from this script's directory and implementation.c is written to the
current working directory.  Verified to reproduce a 25,005-generated-line
file matching the attempt's own "~25k lines" record.
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen2

HDR = """/*
 * implementation.c -- machine-generated, specialized AVX-512 kernels for
 * iterated batched 3D complex FFTs over the fixed cube sizes
 * L in {6,8,13,17,23,36,45,64}, computing per iteration:
 *     z = FFT3(x) + c ;  x <- z / (1 + |z|)
 * (forward unnormalized DFT along each axis, fused elementwise map).
 *
 * All transform arithmetic is original generated code:
 *   - prime-factor (Good-Thomas) and Cooley-Tukey factorizations
 *     (6=2*3, 36=4*9, 45=5*9, 8, 9=3*3, 64=8*8),
 *   - Rader prime transforms for 13 (conv-12) and 17 (conv-16),
 *   - symmetric half-matrix direct prime transforms for 3,5,11,23,
 * with twiddle/convolution constants emitted in full precision.
 * No FFT library is used, linked against, or loaded. Single-threaded.
 *
 * Data layouts: batch-lane groups of 8 volumes (SIMD across the batch) for
 * L<=45, per-volume padded split-complex planes with an in-register
 * 8x8 transpose z-pass for L=64 and batch remainders.
 * Generated by gen_impl.py (shipped in this directory).
 */"""

gen2.RADER_SET.update({13, 17})
src = gen2.generate_v6(gsizes=(6, 8, 13, 17, 23, 36, 45),
                       gmap={L: 'ALT' for L in (6, 8, 13, 17, 23, 36, 45)})
out = os.path.join(os.getcwd(), "implementation.c")
open(out, "w").write(HDR + "\n" + src)
print("written", len(src.splitlines()), "generated lines ->", out)
