/* L17_winograd.c -- forward complex-double 3D DFT of the 17^3 cube.
 *
 * TECHNIQUE
 *   A hand-derived 17-point module obtained from the Fermat-prime structure of
 *   17 = 2^4+1, applied along all three axes by a three-pass row-column sweep
 *   whose passes each rotate the index order so that every pass reads and
 *   writes with unit-stride SIMD lanes.
 *
 *   Derivation (verified numerically, rel err 7e-16, see the strategy record):
 *     * (Z/17)* is cyclic of order 16, generated by g = 3.  Rader turns the
 *       17-point DFT into a length-16 cyclic convolution.
 *     * Quotienting by {+-1} splits that convolution canonically as
 *          Z[x]/(x^16-1) = Z[x]/(x^8-1)  (+)  Z[x]/(x^8+1),
 *       i.e. u_j = x_j + x_(17-j) drives a length-8 CYCLIC correlation with the
 *       REAL kernel c_r = cos(2 pi 3^r/17), and v_j = x_j - x_(17-j) drives a
 *       length-8 NEGACYCLIC correlation with the imaginary kernel i*sin(...).
 *       Indexing j and k by the order-8 quotient group makes both matrices
 *       (skew-)circulant -- checked exactly, err 2.4e-15.
 *     * The cyclic half splits ONE more level with sign-only reductions:
 *          x^8-1 = (x^4-1)(x^4+1),
 *       P_m = u_m + u_(m+4), Q_m = u_m - u_(m+4), giving a 4x4 cyclic and a 4x4
 *       negacyclic apply instead of one 8x8.  That is the whole win: 64 -> 32
 *       real MACs per component.  x^8+1 is irreducible over R, so the
 *       negacyclic half is left dense (see the record for why every way of
 *       splitting it -- Winograd cyclotomic, sqrt(2) factorisation, x^4-+i --
 *       loses on instruction count).
 *
 * LAYOUT / SIMD  (the other half of the technique)
 *   Each pass transforms the OUTER index of a [17][289] array and stores its
 *   result with the index order rotated left by one:
 *       in [x][y][z] --P1--> A[y][z][kx] --P2--> B[z][kx][ky] --P3--> out[kx][ky][kz]
 *   so the axis being transformed is always the outer one (stride SP) and the
 *   289-long "spectator" pair is always contiguous.  The SIMD lanes hold W
 *   consecutive spectators, so every lane runs the same straight-line code with
 *   lane-invariant broadcast constants and zero cross-lane traffic inside the
 *   kernel.  289 = 36*8 + 1 = 72*4 + 1, so exactly ONE spectator per pass falls
 *   outside the vector groups; it is (q,r) = (16,16) and is done by a scalar
 *   instantiation of the same kernel -- no masking, no padding-lane waste, and
 *   no out-of-bounds read at the end of the batch.
 *   The rotation is paid for inside the store: the kernel's 17 output vectors
 *   (indexed by output index, lanes = old spectator) are turned into W runs of
 *   17 contiguous doubles (lane-major) by W*log2(W) two-source shuffles per
 *   WxW block -- 24 vpermt2pd/vshuff64x2/vunpckpd per block at W=8.  Those land
 *   on port 5 while the FMAs are on port 0/1, so on a 1-FMA-unit part they are
 *   free; the W lanes' destinations are contiguous, so the stores stream.
 *   Scratch is 2 x (split re,im) x 17 x SP doubles = 161 kB, L2-resident, and
 *   is independent of the batch: B=1 and B=large run the identical code path.
 *
 * OPERATION COUNT PER 17-POINT TRANSFORM (exact; counted in the emitted
 * assembly, not estimated -- gcc -O3 -march=native emits exactly 296 FP
 * instructions per kernel instance):
 *     192 FMA + 104 add/sub = 296 FP instructions, 488 flops.
 *   Comparison on the same accounting (docs/literature/02 sections 2.4-2.7):
 *     this module                     296 instr / 488 flops
 *     FFTW dft-generic-17 (dense)     336 instr / 592 flops
 *     Rader-17, two length-16 FFTs    388 instr / 468 flops
 *     Winograd/WFTA-17 (Burrus T7.1)  384 instr / 384 flops (70 mul+314 add)
 *   The dense kernel is built into this file too (-DL17_DENSE_KERNEL) and
 *   measured 39.4 us against this module's 32.3 us per 17^3 transform in an
 *   otherwise identical harness (Haswell, AVX2, B=1): -18%.
 *   The minimum-multiplication WFTA route LOSES here and is not used; see the
 *   strategy record for the counts that kill each way of splitting the
 *   negacyclic half.
 *   Per 17^3 volume: 3*289*296 = 256,632 FP instructions, 423,096 flops.
 *
 * ASSUMPTIONS
 *   * L == 17 only.  Single-threaded.  Out-of-place, `in` untouched.
 *   * add, mul and FMA all have the same throughput and issue on the same
 *     ports (true for every x86 from Haswell on).  This is what makes the
 *     minimum-multiplication programme lose and the sign-only split win.
 *   * fp-contract is on (-O3 default in gnu11), so `a + b*c` becomes one FMA.
 *   * Eight instantiations ({256,512}-bit x three kernel schedules, plus two
 *     fused-pass-2+3 variants f4/f8 that delete the full-volume B scratch by
 *     completing passes 2+3 one kx-block at a time out of an L1-resident
 *     mini-buffer) are compiled and fft3d_create() picks by measurement.
 *     On a 1-FMA-unit Cascade Lake part 512-bit and 256-bit code have identical
 *     peak FP throughput while 512-bit pays the AVX-512 licence frequency, so
 *     wider is not automatically faster and guessing is not safe.  All four
 *     execute the same arithmetic in the same order and are bit-identical
 *     (verified by cmp on the output files), so the choice cannot change the
 *     answer -- only the speed.
 */
#define _POSIX_C_SOURCE 200809L
#include <complex.h>
#include <math.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

#include "fft3d_api.h"

#define NS 289          /* spectator count per pass: 17*17                  */
#ifndef SP
#define SP 296          /* padded spectator stride, multiple of 8 doubles   */
#endif
#define VOL 4913
#ifdef L17_DENSE_KERNEL
#define NVAR 4
#else
#define NVAR 8         /* {3 kernel schedules} x {256,512 bit} + 2 fused-pass-2+3
                          variants (f4/f8), all bit-identical */
#endif

typedef double    v8  __attribute__((vector_size(64)));
typedef double    v8u __attribute__((vector_size(64), aligned(8)));
typedef long long i8v __attribute__((vector_size(64)));
typedef double    v4  __attribute__((vector_size(32)));
typedef double    v4u __attribute__((vector_size(32), aligned(8)));
typedef long long i4v __attribute__((vector_size(32)));

#define BCAST(TY,x) ((TY){0} + (x))   /* scalar -> lane-broadcast, folded at compile time */
#define SH8(a,b,...) ((v8)__builtin_shuffle((v8)(a),(v8)(b),(i8v){__VA_ARGS__}))
#define SH4(a,b,...) ((v4)__builtin_shuffle((v4)(a),(v4)(b),(i4v){__VA_ARGS__}))

#define DEF_K17_A(SUF, T) \
static inline __attribute__((always_inline)) void k17_##SUF(const T *xr, const T *xi, T *yr, T *yi) \
{ \
    T pq[8], vv[16], cc[16]; \
    T a0r, a1r, a2r, a3r, a0i, a1i, a2i, a3i, dr, di, u0r,u0i,u1r,u1i; \
    dr = xr[0]; di = xi[0]; \
    u0r = xr[1] + xr[16];  u0i = xi[1] + xi[16]; \
    u1r = xr[4] + xr[13];  u1i = xi[4] + xi[13]; \
    vv[0] = xr[1] - xr[16];  vv[1] = xi[1] - xi[16]; \
    vv[8] = xr[13] - xr[4];  vv[9] = xi[13] - xi[4]; \
    { const T pr = u0r + u1r, pi = u0i + u1i; \
      pq[0] = u0r - u1r;  pq[1] = u0i - u1i; \
      dr = dr + pr;  di = di + pi; \
      a0r = xr[0] + pr*5.12370294433828866e-01; \
      a1r = xr[0] + pr*8.60376828522276954e-02; \
      a2r = xr[0] + pr*-1.21982091231621334e-01; \
      a3r = xr[0] + pr*-7.26425886054435255e-01; \
      a0i = xi[0] + pi*5.12370294433828866e-01; \
      a1i = xi[0] + pi*8.60376828522276954e-02; \
      a2i = xi[0] + pi*-1.21982091231621334e-01; \
      a3i = xi[0] + pi*-7.26425886054435255e-01; \
    } \
    u0r = xr[3] + xr[14];  u0i = xi[3] + xi[14]; \
    u1r = xr[5] + xr[12];  u1i = xi[5] + xi[12]; \
    vv[2] = xr[3] - xr[14];  vv[3] = xi[3] - xi[14]; \
    vv[10] = xr[5] - xr[12];  vv[11] = xi[5] - xi[12]; \
    { const T pr = u0r + u1r, pi = u0i + u1i; \
      pq[2] = u0r - u1r;  pq[3] = u0i - u1i; \
      dr = dr + pr;  di = di + pi; \
      a0r = a0r + pr*8.60376828522276954e-02; \
      a1r = a1r + pr*-1.21982091231621334e-01; \
      a2r = a2r + pr*-7.26425886054435255e-01; \
      a3r = a3r + pr*5.12370294433828866e-01; \
      a0i = a0i + pi*8.60376828522276954e-02; \
      a1i = a1i + pi*-1.21982091231621334e-01; \
      a2i = a2i + pi*-7.26425886054435255e-01; \
      a3i = a3i + pi*5.12370294433828866e-01; \
    } \
    u0r = xr[8] + xr[9];  u0i = xi[8] + xi[9]; \
    u1r = xr[2] + xr[15];  u1i = xi[2] + xi[15]; \
    vv[4] = xr[9] - xr[8];  vv[5] = xi[9] - xi[8]; \
    vv[12] = xr[15] - xr[2];  vv[13] = xi[15] - xi[2]; \
    { const T pr = u0r + u1r, pi = u0i + u1i; \
      pq[4] = u0r - u1r;  pq[5] = u0i - u1i; \
      dr = dr + pr;  di = di + pi; \
      a0r = a0r + pr*-1.21982091231621334e-01; \
      a1r = a1r + pr*-7.26425886054435255e-01; \
      a2r = a2r + pr*5.12370294433828866e-01; \
      a3r = a3r + pr*8.60376828522276954e-02; \
      a0i = a0i + pi*-1.21982091231621334e-01; \
      a1i = a1i + pi*-7.26425886054435255e-01; \
      a2i = a2i + pi*5.12370294433828866e-01; \
      a3i = a3i + pi*8.60376828522276954e-02; \
    } \
    u0r = xr[7] + xr[10];  u0i = xi[7] + xi[10]; \
    u1r = xr[6] + xr[11];  u1i = xi[6] + xi[11]; \
    vv[6] = xr[10] - xr[7];  vv[7] = xi[10] - xi[7]; \
    vv[14] = xr[11] - xr[6];  vv[15] = xi[11] - xi[6]; \
    { const T pr = u0r + u1r, pi = u0i + u1i; \
      pq[6] = u0r - u1r;  pq[7] = u0i - u1i; \
      dr = dr + pr;  di = di + pi; \
      a0r = a0r + pr*-7.26425886054435255e-01; \
      a1r = a1r + pr*5.12370294433828866e-01; \
      a2r = a2r + pr*8.60376828522276954e-02; \
      a3r = a3r + pr*-1.21982091231621334e-01; \
      a0i = a0i + pi*-7.26425886054435255e-01; \
      a1i = a1i + pi*5.12370294433828866e-01; \
      a2i = a2i + pi*8.60376828522276954e-02; \
      a3i = a3i + pi*-1.21982091231621334e-01; \
    } \
    yr[0] = dr;  yi[0] = di; \
    cc[0] = a0r; cc[1] = a0i; cc[2] = a1r; cc[3] = a1i; \
    cc[4] = a2r; cc[5] = a2i; cc[6] = a3r; cc[7] = a3i; \
    { const T qr = pq[0], qi = pq[1]; \
      a0r = qr*4.20101934970526891e-01; \
      a1r = qr*3.59700672924310572e-01; \
      a2r = qr*-8.60991008452280493e-01; \
      a3r = qr*-1.23791249675178877e-01; \
      a0i = qi*4.20101934970526891e-01; \
      a1i = qi*3.59700672924310572e-01; \
      a2i = qi*-8.60991008452280493e-01; \
      a3i = qi*-1.23791249675178877e-01; \
    } \
    { const T qr = pq[2], qi = pq[3]; \
      a0r = a0r + qr*3.59700672924310572e-01; \
      a1r = a1r + qr*-8.60991008452280493e-01; \
      a2r = a2r + qr*-1.23791249675178877e-01; \
      a3r = a3r + qr*-4.20101934970526891e-01; \
      a0i = a0i + qi*3.59700672924310572e-01; \
      a1i = a1i + qi*-8.60991008452280493e-01; \
      a2i = a2i + qi*-1.23791249675178877e-01; \
      a3i = a3i + qi*-4.20101934970526891e-01; \
    } \
    { const T qr = pq[4], qi = pq[5]; \
      a0r = a0r + qr*-8.60991008452280493e-01; \
      a1r = a1r + qr*-1.23791249675178877e-01; \
      a2r = a2r + qr*-4.20101934970526891e-01; \
      a3r = a3r + qr*-3.59700672924310572e-01; \
      a0i = a0i + qi*-8.60991008452280493e-01; \
      a1i = a1i + qi*-1.23791249675178877e-01; \
      a2i = a2i + qi*-4.20101934970526891e-01; \
      a3i = a3i + qi*-3.59700672924310572e-01; \
    } \
    { const T qr = pq[6], qi = pq[7]; \
      a0r = a0r + qr*-1.23791249675178877e-01; \
      a1r = a1r + qr*-4.20101934970526891e-01; \
      a2r = a2r + qr*-3.59700672924310572e-01; \
      a3r = a3r + qr*8.60991008452280493e-01; \
      a0i = a0i + qi*-1.23791249675178877e-01; \
      a1i = a1i + qi*-4.20101934970526891e-01; \
      a2i = a2i + qi*-3.59700672924310572e-01; \
      a3i = a3i + qi*8.60991008452280493e-01; \
    } \
    { const T ta = cc[0], tb = cc[1]; \
      cc[0] = ta + a0r;  cc[1] = tb + a0i; \
      cc[8] = ta - a0r;  cc[9] = tb - a0i; } \
    { const T ta = cc[2], tb = cc[3]; \
      cc[2] = ta + a1r;  cc[3] = tb + a1i; \
      cc[10] = ta - a1r;  cc[11] = tb - a1i; } \
    { const T ta = cc[4], tb = cc[5]; \
      cc[4] = ta + a2r;  cc[5] = tb + a2i; \
      cc[12] = ta - a2r;  cc[13] = tb - a2i; } \
    { const T ta = cc[6], tb = cc[7]; \
      cc[6] = ta + a3r;  cc[7] = tb + a3i; \
      cc[14] = ta - a3r;  cc[15] = tb - a3i; } \
    { const T tvr = vv[0], tvi = vv[1]; \
      a0r = tvr*3.61241666187152921e-01; \
      a1r = tvr*8.95163291355062340e-01; \
      a2r = tvr*-1.83749517816570340e-01; \
      a3r = tvr*-5.26432162877355836e-01; \
      a0i = tvi*3.61241666187152921e-01; \
      a1i = tvi*8.95163291355062340e-01; \
      a2i = tvi*-1.83749517816570340e-01; \
      a3i = tvi*-5.26432162877355836e-01; \
    } \
    { const T tvr = vv[2], tvi = vv[3]; \
      a0r = a0r + tvr*8.95163291355062340e-01; \
      a1r = a1r + tvr*-1.83749517816570340e-01; \
      a2r = a2r + tvr*-5.26432162877355836e-01; \
      a3r = a3r + tvr*-9.95734176295034468e-01; \
      a0i = a0i + tvi*8.95163291355062340e-01; \
      a1i = a1i + tvi*-1.83749517816570340e-01; \
      a2i = a2i + tvi*-5.26432162877355836e-01; \
      a3i = a3i + tvi*-9.95734176295034468e-01; \
    } \
    { const T tvr = vv[4], tvi = vv[5]; \
      a0r = a0r + tvr*-1.83749517816570340e-01; \
      a1r = a1r + tvr*-5.26432162877355836e-01; \
      a2r = a2r + tvr*-9.95734176295034468e-01; \
      a3r = a3r + tvr*9.61825643172819045e-01; \
      a0i = a0i + tvi*-1.83749517816570340e-01; \
      a1i = a1i + tvi*-5.26432162877355836e-01; \
      a2i = a2i + tvi*-9.95734176295034468e-01; \
      a3i = a3i + tvi*9.61825643172819045e-01; \
    } \
    { const T tvr = vv[6], tvi = vv[7]; \
      a0r = a0r + tvr*-5.26432162877355836e-01; \
      a1r = a1r + tvr*-9.95734176295034468e-01; \
      a2r = a2r + tvr*9.61825643172819045e-01; \
      a3r = a3r + tvr*-6.73695643646557207e-01; \
      a0i = a0i + tvi*-5.26432162877355836e-01; \
      a1i = a1i + tvi*-9.95734176295034468e-01; \
      a2i = a2i + tvi*9.61825643172819045e-01; \
      a3i = a3i + tvi*-6.73695643646557207e-01; \
    } \
    { const T tvr = vv[8], tvi = vv[9]; \
      a0r = a0r + tvr*-9.95734176295034468e-01; \
      a1r = a1r + tvr*9.61825643172819045e-01; \
      a2r = a2r + tvr*-6.73695643646557207e-01; \
      a3r = a3r + tvr*-7.98017227280239494e-01; \
      a0i = a0i + tvi*-9.95734176295034468e-01; \
      a1i = a1i + tvi*9.61825643172819045e-01; \
      a2i = a2i + tvi*-6.73695643646557207e-01; \
      a3i = a3i + tvi*-7.98017227280239494e-01; \
    } \
    { const T tvr = vv[10], tvi = vv[11]; \
      a0r = a0r + tvr*9.61825643172819045e-01; \
      a1r = a1r + tvr*-6.73695643646557207e-01; \
      a2r = a2r + tvr*-7.98017227280239494e-01; \
      a3r = a3r + tvr*-3.61241666187152921e-01; \
      a0i = a0i + tvi*9.61825643172819045e-01; \
      a1i = a1i + tvi*-6.73695643646557207e-01; \
      a2i = a2i + tvi*-7.98017227280239494e-01; \
      a3i = a3i + tvi*-3.61241666187152921e-01; \
    } \
    { const T tvr = vv[12], tvi = vv[13]; \
      a0r = a0r + tvr*-6.73695643646557207e-01; \
      a1r = a1r + tvr*-7.98017227280239494e-01; \
      a2r = a2r + tvr*-3.61241666187152921e-01; \
      a3r = a3r + tvr*-8.95163291355062340e-01; \
      a0i = a0i + tvi*-6.73695643646557207e-01; \
      a1i = a1i + tvi*-7.98017227280239494e-01; \
      a2i = a2i + tvi*-3.61241666187152921e-01; \
      a3i = a3i + tvi*-8.95163291355062340e-01; \
    } \
    { const T tvr = vv[14], tvi = vv[15]; \
      a0r = a0r + tvr*-7.98017227280239494e-01; \
      a1r = a1r + tvr*-3.61241666187152921e-01; \
      a2r = a2r + tvr*-8.95163291355062340e-01; \
      a3r = a3r + tvr*1.83749517816570340e-01; \
      a0i = a0i + tvi*-7.98017227280239494e-01; \
      a1i = a1i + tvi*-3.61241666187152921e-01; \
      a2i = a2i + tvi*-8.95163291355062340e-01; \
      a3i = a3i + tvi*1.83749517816570340e-01; \
    } \
    { const T tcr = cc[0], tci = cc[1]; \
      yr[1] = tcr + a0i;  yi[1] = tci - a0r; \
      yr[16] = tcr - a0i;  yi[16] = tci + a0r; } \
    { const T tcr = cc[2], tci = cc[3]; \
      yr[3] = tcr + a1i;  yi[3] = tci - a1r; \
      yr[14] = tcr - a1i;  yi[14] = tci + a1r; } \
    { const T tcr = cc[4], tci = cc[5]; \
      yr[8] = tcr - a2i;  yi[8] = tci + a2r; \
      yr[9] = tcr + a2i;  yi[9] = tci - a2r; } \
    { const T tcr = cc[6], tci = cc[7]; \
      yr[7] = tcr - a3i;  yi[7] = tci + a3r; \
      yr[10] = tcr + a3i;  yi[10] = tci - a3r; } \
    { const T tvr = vv[0], tvi = vv[1]; \
      a0r = tvr*-9.95734176295034468e-01; \
      a1r = tvr*9.61825643172819045e-01; \
      a2r = tvr*-6.73695643646557207e-01; \
      a3r = tvr*-7.98017227280239494e-01; \
      a0i = tvi*-9.95734176295034468e-01; \
      a1i = tvi*9.61825643172819045e-01; \
      a2i = tvi*-6.73695643646557207e-01; \
      a3i = tvi*-7.98017227280239494e-01; \
    } \
    { const T tvr = vv[2], tvi = vv[3]; \
      a0r = a0r + tvr*9.61825643172819045e-01; \
      a1r = a1r + tvr*-6.73695643646557207e-01; \
      a2r = a2r + tvr*-7.98017227280239494e-01; \
      a3r = a3r + tvr*-3.61241666187152921e-01; \
      a0i = a0i + tvi*9.61825643172819045e-01; \
      a1i = a1i + tvi*-6.73695643646557207e-01; \
      a2i = a2i + tvi*-7.98017227280239494e-01; \
      a3i = a3i + tvi*-3.61241666187152921e-01; \
    } \
    { const T tvr = vv[4], tvi = vv[5]; \
      a0r = a0r + tvr*-6.73695643646557207e-01; \
      a1r = a1r + tvr*-7.98017227280239494e-01; \
      a2r = a2r + tvr*-3.61241666187152921e-01; \
      a3r = a3r + tvr*-8.95163291355062340e-01; \
      a0i = a0i + tvi*-6.73695643646557207e-01; \
      a1i = a1i + tvi*-7.98017227280239494e-01; \
      a2i = a2i + tvi*-3.61241666187152921e-01; \
      a3i = a3i + tvi*-8.95163291355062340e-01; \
    } \
    { const T tvr = vv[6], tvi = vv[7]; \
      a0r = a0r + tvr*-7.98017227280239494e-01; \
      a1r = a1r + tvr*-3.61241666187152921e-01; \
      a2r = a2r + tvr*-8.95163291355062340e-01; \
      a3r = a3r + tvr*1.83749517816570340e-01; \
      a0i = a0i + tvi*-7.98017227280239494e-01; \
      a1i = a1i + tvi*-3.61241666187152921e-01; \
      a2i = a2i + tvi*-8.95163291355062340e-01; \
      a3i = a3i + tvi*1.83749517816570340e-01; \
    } \
    { const T tvr = vv[8], tvi = vv[9]; \
      a0r = a0r + tvr*-3.61241666187152921e-01; \
      a1r = a1r + tvr*-8.95163291355062340e-01; \
      a2r = a2r + tvr*1.83749517816570340e-01; \
      a3r = a3r + tvr*5.26432162877355836e-01; \
      a0i = a0i + tvi*-3.61241666187152921e-01; \
      a1i = a1i + tvi*-8.95163291355062340e-01; \
      a2i = a2i + tvi*1.83749517816570340e-01; \
      a3i = a3i + tvi*5.26432162877355836e-01; \
    } \
    { const T tvr = vv[10], tvi = vv[11]; \
      a0r = a0r + tvr*-8.95163291355062340e-01; \
      a1r = a1r + tvr*1.83749517816570340e-01; \
      a2r = a2r + tvr*5.26432162877355836e-01; \
      a3r = a3r + tvr*9.95734176295034468e-01; \
      a0i = a0i + tvi*-8.95163291355062340e-01; \
      a1i = a1i + tvi*1.83749517816570340e-01; \
      a2i = a2i + tvi*5.26432162877355836e-01; \
      a3i = a3i + tvi*9.95734176295034468e-01; \
    } \
    { const T tvr = vv[12], tvi = vv[13]; \
      a0r = a0r + tvr*1.83749517816570340e-01; \
      a1r = a1r + tvr*5.26432162877355836e-01; \
      a2r = a2r + tvr*9.95734176295034468e-01; \
      a3r = a3r + tvr*-9.61825643172819045e-01; \
      a0i = a0i + tvi*1.83749517816570340e-01; \
      a1i = a1i + tvi*5.26432162877355836e-01; \
      a2i = a2i + tvi*9.95734176295034468e-01; \
      a3i = a3i + tvi*-9.61825643172819045e-01; \
    } \
    { const T tvr = vv[14], tvi = vv[15]; \
      a0r = a0r + tvr*5.26432162877355836e-01; \
      a1r = a1r + tvr*9.95734176295034468e-01; \
      a2r = a2r + tvr*-9.61825643172819045e-01; \
      a3r = a3r + tvr*6.73695643646557207e-01; \
      a0i = a0i + tvi*5.26432162877355836e-01; \
      a1i = a1i + tvi*9.95734176295034468e-01; \
      a2i = a2i + tvi*-9.61825643172819045e-01; \
      a3i = a3i + tvi*6.73695643646557207e-01; \
    } \
    { const T tcr = cc[8], tci = cc[9]; \
      yr[4] = tcr - a0i;  yi[4] = tci + a0r; \
      yr[13] = tcr + a0i;  yi[13] = tci - a0r; } \
    { const T tcr = cc[10], tci = cc[11]; \
      yr[5] = tcr + a1i;  yi[5] = tci - a1r; \
      yr[12] = tcr - a1i;  yi[12] = tci + a1r; } \
    { const T tcr = cc[12], tci = cc[13]; \
      yr[2] = tcr - a2i;  yi[2] = tci + a2r; \
      yr[15] = tcr + a2i;  yi[15] = tci - a2r; } \
    { const T tcr = cc[14], tci = cc[15]; \
      yr[6] = tcr - a3i;  yi[6] = tci + a3r; \
      yr[11] = tcr + a3i;  yi[11] = tci - a3r; } \
}

#define DEF_K17_B(SUF, T) \
static inline __attribute__((always_inline)) void k17_##SUF(const T *xr, const T *xi, T *yr, T *yi) \
{ \
    T vv[16], cc[16]; \
    T a0r, a1r, a2r, a3r, a0i, a1i, a2i, a3i, b0r, b1r, b2r, b3r, b0i, b1i, b2i, b3i, dr, di, u0r,u0i,u1r,u1i; \
    dr = xr[0]; di = xi[0]; \
    u0r = xr[1] + xr[16];  u0i = xi[1] + xi[16]; \
    u1r = xr[4] + xr[13];  u1i = xi[4] + xi[13]; \
    vv[0] = xr[1] - xr[16];  vv[1] = xi[1] - xi[16]; \
    vv[8] = xr[13] - xr[4];  vv[9] = xi[13] - xi[4]; \
    { const T pr = u0r + u1r, pi = u0i + u1i; \
      const T qr = u0r - u1r, qi = u0i - u1i; \
      dr = dr + pr;  di = di + pi; \
      a0r = xr[0] + pr*5.12370294433828866e-01; \
      a1r = xr[0] + pr*8.60376828522276954e-02; \
      a2r = xr[0] + pr*-1.21982091231621334e-01; \
      a3r = xr[0] + pr*-7.26425886054435255e-01; \
      a0i = xi[0] + pi*5.12370294433828866e-01; \
      a1i = xi[0] + pi*8.60376828522276954e-02; \
      a2i = xi[0] + pi*-1.21982091231621334e-01; \
      a3i = xi[0] + pi*-7.26425886054435255e-01; \
      b0r = qr*4.20101934970526891e-01; \
      b1r = qr*3.59700672924310572e-01; \
      b2r = qr*-8.60991008452280493e-01; \
      b3r = qr*-1.23791249675178877e-01; \
      b0i = qi*4.20101934970526891e-01; \
      b1i = qi*3.59700672924310572e-01; \
      b2i = qi*-8.60991008452280493e-01; \
      b3i = qi*-1.23791249675178877e-01; \
    } \
    u0r = xr[3] + xr[14];  u0i = xi[3] + xi[14]; \
    u1r = xr[5] + xr[12];  u1i = xi[5] + xi[12]; \
    vv[2] = xr[3] - xr[14];  vv[3] = xi[3] - xi[14]; \
    vv[10] = xr[5] - xr[12];  vv[11] = xi[5] - xi[12]; \
    { const T pr = u0r + u1r, pi = u0i + u1i; \
      const T qr = u0r - u1r, qi = u0i - u1i; \
      dr = dr + pr;  di = di + pi; \
      a0r = a0r + pr*8.60376828522276954e-02; \
      a1r = a1r + pr*-1.21982091231621334e-01; \
      a2r = a2r + pr*-7.26425886054435255e-01; \
      a3r = a3r + pr*5.12370294433828866e-01; \
      a0i = a0i + pi*8.60376828522276954e-02; \
      a1i = a1i + pi*-1.21982091231621334e-01; \
      a2i = a2i + pi*-7.26425886054435255e-01; \
      a3i = a3i + pi*5.12370294433828866e-01; \
      b0r = b0r + qr*3.59700672924310572e-01; \
      b1r = b1r + qr*-8.60991008452280493e-01; \
      b2r = b2r + qr*-1.23791249675178877e-01; \
      b3r = b3r + qr*-4.20101934970526891e-01; \
      b0i = b0i + qi*3.59700672924310572e-01; \
      b1i = b1i + qi*-8.60991008452280493e-01; \
      b2i = b2i + qi*-1.23791249675178877e-01; \
      b3i = b3i + qi*-4.20101934970526891e-01; \
    } \
    u0r = xr[8] + xr[9];  u0i = xi[8] + xi[9]; \
    u1r = xr[2] + xr[15];  u1i = xi[2] + xi[15]; \
    vv[4] = xr[9] - xr[8];  vv[5] = xi[9] - xi[8]; \
    vv[12] = xr[15] - xr[2];  vv[13] = xi[15] - xi[2]; \
    { const T pr = u0r + u1r, pi = u0i + u1i; \
      const T qr = u0r - u1r, qi = u0i - u1i; \
      dr = dr + pr;  di = di + pi; \
      a0r = a0r + pr*-1.21982091231621334e-01; \
      a1r = a1r + pr*-7.26425886054435255e-01; \
      a2r = a2r + pr*5.12370294433828866e-01; \
      a3r = a3r + pr*8.60376828522276954e-02; \
      a0i = a0i + pi*-1.21982091231621334e-01; \
      a1i = a1i + pi*-7.26425886054435255e-01; \
      a2i = a2i + pi*5.12370294433828866e-01; \
      a3i = a3i + pi*8.60376828522276954e-02; \
      b0r = b0r + qr*-8.60991008452280493e-01; \
      b1r = b1r + qr*-1.23791249675178877e-01; \
      b2r = b2r + qr*-4.20101934970526891e-01; \
      b3r = b3r + qr*-3.59700672924310572e-01; \
      b0i = b0i + qi*-8.60991008452280493e-01; \
      b1i = b1i + qi*-1.23791249675178877e-01; \
      b2i = b2i + qi*-4.20101934970526891e-01; \
      b3i = b3i + qi*-3.59700672924310572e-01; \
    } \
    u0r = xr[7] + xr[10];  u0i = xi[7] + xi[10]; \
    u1r = xr[6] + xr[11];  u1i = xi[6] + xi[11]; \
    vv[6] = xr[10] - xr[7];  vv[7] = xi[10] - xi[7]; \
    vv[14] = xr[11] - xr[6];  vv[15] = xi[11] - xi[6]; \
    { const T pr = u0r + u1r, pi = u0i + u1i; \
      const T qr = u0r - u1r, qi = u0i - u1i; \
      dr = dr + pr;  di = di + pi; \
      a0r = a0r + pr*-7.26425886054435255e-01; \
      a1r = a1r + pr*5.12370294433828866e-01; \
      a2r = a2r + pr*8.60376828522276954e-02; \
      a3r = a3r + pr*-1.21982091231621334e-01; \
      a0i = a0i + pi*-7.26425886054435255e-01; \
      a1i = a1i + pi*5.12370294433828866e-01; \
      a2i = a2i + pi*8.60376828522276954e-02; \
      a3i = a3i + pi*-1.21982091231621334e-01; \
      b0r = b0r + qr*-1.23791249675178877e-01; \
      b1r = b1r + qr*-4.20101934970526891e-01; \
      b2r = b2r + qr*-3.59700672924310572e-01; \
      b3r = b3r + qr*8.60991008452280493e-01; \
      b0i = b0i + qi*-1.23791249675178877e-01; \
      b1i = b1i + qi*-4.20101934970526891e-01; \
      b2i = b2i + qi*-3.59700672924310572e-01; \
      b3i = b3i + qi*8.60991008452280493e-01; \
    } \
    yr[0] = dr;  yi[0] = di; \
    cc[0] = a0r + b0r;  cc[1] = a0i + b0i; \
    cc[8] = a0r - b0r;  cc[9] = a0i - b0i; \
    cc[2] = a1r + b1r;  cc[3] = a1i + b1i; \
    cc[10] = a1r - b1r;  cc[11] = a1i - b1i; \
    cc[4] = a2r + b2r;  cc[5] = a2i + b2i; \
    cc[12] = a2r - b2r;  cc[13] = a2i - b2i; \
    cc[6] = a3r + b3r;  cc[7] = a3i + b3i; \
    cc[14] = a3r - b3r;  cc[15] = a3i - b3i; \
    { const T tvr = vv[0], tvi = vv[1]; \
      a0r = tvr*3.61241666187152921e-01; \
      a1r = tvr*8.95163291355062340e-01; \
      a2r = tvr*-1.83749517816570340e-01; \
      a3r = tvr*-5.26432162877355836e-01; \
      a0i = tvi*3.61241666187152921e-01; \
      a1i = tvi*8.95163291355062340e-01; \
      a2i = tvi*-1.83749517816570340e-01; \
      a3i = tvi*-5.26432162877355836e-01; \
    } \
    { const T tvr = vv[2], tvi = vv[3]; \
      a0r = a0r + tvr*8.95163291355062340e-01; \
      a1r = a1r + tvr*-1.83749517816570340e-01; \
      a2r = a2r + tvr*-5.26432162877355836e-01; \
      a3r = a3r + tvr*-9.95734176295034468e-01; \
      a0i = a0i + tvi*8.95163291355062340e-01; \
      a1i = a1i + tvi*-1.83749517816570340e-01; \
      a2i = a2i + tvi*-5.26432162877355836e-01; \
      a3i = a3i + tvi*-9.95734176295034468e-01; \
    } \
    { const T tvr = vv[4], tvi = vv[5]; \
      a0r = a0r + tvr*-1.83749517816570340e-01; \
      a1r = a1r + tvr*-5.26432162877355836e-01; \
      a2r = a2r + tvr*-9.95734176295034468e-01; \
      a3r = a3r + tvr*9.61825643172819045e-01; \
      a0i = a0i + tvi*-1.83749517816570340e-01; \
      a1i = a1i + tvi*-5.26432162877355836e-01; \
      a2i = a2i + tvi*-9.95734176295034468e-01; \
      a3i = a3i + tvi*9.61825643172819045e-01; \
    } \
    { const T tvr = vv[6], tvi = vv[7]; \
      a0r = a0r + tvr*-5.26432162877355836e-01; \
      a1r = a1r + tvr*-9.95734176295034468e-01; \
      a2r = a2r + tvr*9.61825643172819045e-01; \
      a3r = a3r + tvr*-6.73695643646557207e-01; \
      a0i = a0i + tvi*-5.26432162877355836e-01; \
      a1i = a1i + tvi*-9.95734176295034468e-01; \
      a2i = a2i + tvi*9.61825643172819045e-01; \
      a3i = a3i + tvi*-6.73695643646557207e-01; \
    } \
    { const T tvr = vv[8], tvi = vv[9]; \
      a0r = a0r + tvr*-9.95734176295034468e-01; \
      a1r = a1r + tvr*9.61825643172819045e-01; \
      a2r = a2r + tvr*-6.73695643646557207e-01; \
      a3r = a3r + tvr*-7.98017227280239494e-01; \
      a0i = a0i + tvi*-9.95734176295034468e-01; \
      a1i = a1i + tvi*9.61825643172819045e-01; \
      a2i = a2i + tvi*-6.73695643646557207e-01; \
      a3i = a3i + tvi*-7.98017227280239494e-01; \
    } \
    { const T tvr = vv[10], tvi = vv[11]; \
      a0r = a0r + tvr*9.61825643172819045e-01; \
      a1r = a1r + tvr*-6.73695643646557207e-01; \
      a2r = a2r + tvr*-7.98017227280239494e-01; \
      a3r = a3r + tvr*-3.61241666187152921e-01; \
      a0i = a0i + tvi*9.61825643172819045e-01; \
      a1i = a1i + tvi*-6.73695643646557207e-01; \
      a2i = a2i + tvi*-7.98017227280239494e-01; \
      a3i = a3i + tvi*-3.61241666187152921e-01; \
    } \
    { const T tvr = vv[12], tvi = vv[13]; \
      a0r = a0r + tvr*-6.73695643646557207e-01; \
      a1r = a1r + tvr*-7.98017227280239494e-01; \
      a2r = a2r + tvr*-3.61241666187152921e-01; \
      a3r = a3r + tvr*-8.95163291355062340e-01; \
      a0i = a0i + tvi*-6.73695643646557207e-01; \
      a1i = a1i + tvi*-7.98017227280239494e-01; \
      a2i = a2i + tvi*-3.61241666187152921e-01; \
      a3i = a3i + tvi*-8.95163291355062340e-01; \
    } \
    { const T tvr = vv[14], tvi = vv[15]; \
      a0r = a0r + tvr*-7.98017227280239494e-01; \
      a1r = a1r + tvr*-3.61241666187152921e-01; \
      a2r = a2r + tvr*-8.95163291355062340e-01; \
      a3r = a3r + tvr*1.83749517816570340e-01; \
      a0i = a0i + tvi*-7.98017227280239494e-01; \
      a1i = a1i + tvi*-3.61241666187152921e-01; \
      a2i = a2i + tvi*-8.95163291355062340e-01; \
      a3i = a3i + tvi*1.83749517816570340e-01; \
    } \
    { const T tcr = cc[0], tci = cc[1]; \
      yr[1] = tcr + a0i;  yi[1] = tci - a0r; \
      yr[16] = tcr - a0i;  yi[16] = tci + a0r; } \
    { const T tcr = cc[2], tci = cc[3]; \
      yr[3] = tcr + a1i;  yi[3] = tci - a1r; \
      yr[14] = tcr - a1i;  yi[14] = tci + a1r; } \
    { const T tcr = cc[4], tci = cc[5]; \
      yr[8] = tcr - a2i;  yi[8] = tci + a2r; \
      yr[9] = tcr + a2i;  yi[9] = tci - a2r; } \
    { const T tcr = cc[6], tci = cc[7]; \
      yr[7] = tcr - a3i;  yi[7] = tci + a3r; \
      yr[10] = tcr + a3i;  yi[10] = tci - a3r; } \
    { const T tvr = vv[0], tvi = vv[1]; \
      a0r = tvr*-9.95734176295034468e-01; \
      a1r = tvr*9.61825643172819045e-01; \
      a2r = tvr*-6.73695643646557207e-01; \
      a3r = tvr*-7.98017227280239494e-01; \
      a0i = tvi*-9.95734176295034468e-01; \
      a1i = tvi*9.61825643172819045e-01; \
      a2i = tvi*-6.73695643646557207e-01; \
      a3i = tvi*-7.98017227280239494e-01; \
    } \
    { const T tvr = vv[2], tvi = vv[3]; \
      a0r = a0r + tvr*9.61825643172819045e-01; \
      a1r = a1r + tvr*-6.73695643646557207e-01; \
      a2r = a2r + tvr*-7.98017227280239494e-01; \
      a3r = a3r + tvr*-3.61241666187152921e-01; \
      a0i = a0i + tvi*9.61825643172819045e-01; \
      a1i = a1i + tvi*-6.73695643646557207e-01; \
      a2i = a2i + tvi*-7.98017227280239494e-01; \
      a3i = a3i + tvi*-3.61241666187152921e-01; \
    } \
    { const T tvr = vv[4], tvi = vv[5]; \
      a0r = a0r + tvr*-6.73695643646557207e-01; \
      a1r = a1r + tvr*-7.98017227280239494e-01; \
      a2r = a2r + tvr*-3.61241666187152921e-01; \
      a3r = a3r + tvr*-8.95163291355062340e-01; \
      a0i = a0i + tvi*-6.73695643646557207e-01; \
      a1i = a1i + tvi*-7.98017227280239494e-01; \
      a2i = a2i + tvi*-3.61241666187152921e-01; \
      a3i = a3i + tvi*-8.95163291355062340e-01; \
    } \
    { const T tvr = vv[6], tvi = vv[7]; \
      a0r = a0r + tvr*-7.98017227280239494e-01; \
      a1r = a1r + tvr*-3.61241666187152921e-01; \
      a2r = a2r + tvr*-8.95163291355062340e-01; \
      a3r = a3r + tvr*1.83749517816570340e-01; \
      a0i = a0i + tvi*-7.98017227280239494e-01; \
      a1i = a1i + tvi*-3.61241666187152921e-01; \
      a2i = a2i + tvi*-8.95163291355062340e-01; \
      a3i = a3i + tvi*1.83749517816570340e-01; \
    } \
    { const T tvr = vv[8], tvi = vv[9]; \
      a0r = a0r + tvr*-3.61241666187152921e-01; \
      a1r = a1r + tvr*-8.95163291355062340e-01; \
      a2r = a2r + tvr*1.83749517816570340e-01; \
      a3r = a3r + tvr*5.26432162877355836e-01; \
      a0i = a0i + tvi*-3.61241666187152921e-01; \
      a1i = a1i + tvi*-8.95163291355062340e-01; \
      a2i = a2i + tvi*1.83749517816570340e-01; \
      a3i = a3i + tvi*5.26432162877355836e-01; \
    } \
    { const T tvr = vv[10], tvi = vv[11]; \
      a0r = a0r + tvr*-8.95163291355062340e-01; \
      a1r = a1r + tvr*1.83749517816570340e-01; \
      a2r = a2r + tvr*5.26432162877355836e-01; \
      a3r = a3r + tvr*9.95734176295034468e-01; \
      a0i = a0i + tvi*-8.95163291355062340e-01; \
      a1i = a1i + tvi*1.83749517816570340e-01; \
      a2i = a2i + tvi*5.26432162877355836e-01; \
      a3i = a3i + tvi*9.95734176295034468e-01; \
    } \
    { const T tvr = vv[12], tvi = vv[13]; \
      a0r = a0r + tvr*1.83749517816570340e-01; \
      a1r = a1r + tvr*5.26432162877355836e-01; \
      a2r = a2r + tvr*9.95734176295034468e-01; \
      a3r = a3r + tvr*-9.61825643172819045e-01; \
      a0i = a0i + tvi*1.83749517816570340e-01; \
      a1i = a1i + tvi*5.26432162877355836e-01; \
      a2i = a2i + tvi*9.95734176295034468e-01; \
      a3i = a3i + tvi*-9.61825643172819045e-01; \
    } \
    { const T tvr = vv[14], tvi = vv[15]; \
      a0r = a0r + tvr*5.26432162877355836e-01; \
      a1r = a1r + tvr*9.95734176295034468e-01; \
      a2r = a2r + tvr*-9.61825643172819045e-01; \
      a3r = a3r + tvr*6.73695643646557207e-01; \
      a0i = a0i + tvi*5.26432162877355836e-01; \
      a1i = a1i + tvi*9.95734176295034468e-01; \
      a2i = a2i + tvi*-9.61825643172819045e-01; \
      a3i = a3i + tvi*6.73695643646557207e-01; \
    } \
    { const T tcr = cc[8], tci = cc[9]; \
      yr[4] = tcr - a0i;  yi[4] = tci + a0r; \
      yr[13] = tcr + a0i;  yi[13] = tci - a0r; } \
    { const T tcr = cc[10], tci = cc[11]; \
      yr[5] = tcr + a1i;  yi[5] = tci - a1r; \
      yr[12] = tcr - a1i;  yi[12] = tci + a1r; } \
    { const T tcr = cc[12], tci = cc[13]; \
      yr[2] = tcr - a2i;  yi[2] = tci + a2r; \
      yr[15] = tcr + a2i;  yi[15] = tci - a2r; } \
    { const T tcr = cc[14], tci = cc[15]; \
      yr[6] = tcr - a3i;  yi[6] = tci + a3r; \
      yr[11] = tcr + a3i;  yi[11] = tci - a3r; } \
}

#define DEF_K17_DENSE(SUF, T) \
static inline __attribute__((always_inline)) void k17_##SUF(const T *xr, const T *xi, T *yr, T *yi) \
{ \
    T uv[32], a0r,a1r,a2r,a3r,a0i,a1i,a2i,a3i, b0r,b1r,b2r,b3r,b0i,b1i,b2i,b3i; \
    T dr = xr[0], di = xi[0]; \
    uv[0] = xr[1] + xr[16];  uv[1] = xi[1] + xi[16]; \
    uv[16] = xr[1] - xr[16];  uv[17] = xi[1] - xi[16]; \
    dr = dr + uv[0];  di = di + uv[1]; \
    uv[2] = xr[2] + xr[15];  uv[3] = xi[2] + xi[15]; \
    uv[18] = xr[2] - xr[15];  uv[19] = xi[2] - xi[15]; \
    dr = dr + uv[2];  di = di + uv[3]; \
    uv[4] = xr[3] + xr[14];  uv[5] = xi[3] + xi[14]; \
    uv[20] = xr[3] - xr[14];  uv[21] = xi[3] - xi[14]; \
    dr = dr + uv[4];  di = di + uv[5]; \
    uv[6] = xr[4] + xr[13];  uv[7] = xi[4] + xi[13]; \
    uv[22] = xr[4] - xr[13];  uv[23] = xi[4] - xi[13]; \
    dr = dr + uv[6];  di = di + uv[7]; \
    uv[8] = xr[5] + xr[12];  uv[9] = xi[5] + xi[12]; \
    uv[24] = xr[5] - xr[12];  uv[25] = xi[5] - xi[12]; \
    dr = dr + uv[8];  di = di + uv[9]; \
    uv[10] = xr[6] + xr[11];  uv[11] = xi[6] + xi[11]; \
    uv[26] = xr[6] - xr[11];  uv[27] = xi[6] - xi[11]; \
    dr = dr + uv[10];  di = di + uv[11]; \
    uv[12] = xr[7] + xr[10];  uv[13] = xi[7] + xi[10]; \
    uv[28] = xr[7] - xr[10];  uv[29] = xi[7] - xi[10]; \
    dr = dr + uv[12];  di = di + uv[13]; \
    uv[14] = xr[8] + xr[9];  uv[15] = xi[8] + xi[9]; \
    uv[30] = xr[8] - xr[9];  uv[31] = xi[8] - xi[9]; \
    dr = dr + uv[14];  di = di + uv[15]; \
    yr[0] = dr;  yi[0] = di; \
    { const T tur = uv[0], tui = uv[1], tvr = uv[16], tvi = uv[17]; \
      a0r = xr[0] + tur*9.32472229404355812e-01; \
      a0i = xi[0] + tui*9.32472229404355812e-01; \
      a1r = xr[0] + tur*7.39008917220659090e-01; \
      a1i = xi[0] + tui*7.39008917220659090e-01; \
      a2r = xr[0] + tur*4.45738355776538253e-01; \
      a2i = xi[0] + tui*4.45738355776538253e-01; \
      a3r = xr[0] + tur*9.22683594633020021e-02; \
      a3i = xi[0] + tui*9.22683594633020021e-02; \
      b0r = tvr*3.61241666187152921e-01; \
      b0i = tvi*3.61241666187152921e-01; \
      b1r = tvr*6.73695643646557207e-01; \
      b1i = tvi*6.73695643646557207e-01; \
      b2r = tvr*8.95163291355062340e-01; \
      b2i = tvi*8.95163291355062340e-01; \
      b3r = tvr*9.95734176295034468e-01; \
      b3i = tvi*9.95734176295034468e-01; \
    } \
    { const T tur = uv[2], tui = uv[3], tvr = uv[18], tvi = uv[19]; \
      a0r = a0r + tur*7.39008917220659090e-01; \
      a0i = a0i + tui*7.39008917220659090e-01; \
      a1r = a1r + tur*9.22683594633020021e-02; \
      a1i = a1i + tui*9.22683594633020021e-02; \
      a2r = a2r + tur*-6.02634636379256405e-01; \
      a2i = a2i + tui*-6.02634636379256405e-01; \
      a3r = a3r + tur*-9.82973099683901785e-01; \
      a3i = a3i + tui*-9.82973099683901785e-01; \
      b0r = b0r + tvr*6.73695643646557207e-01; \
      b0i = b0i + tvi*6.73695643646557207e-01; \
      b1r = b1r + tvr*9.95734176295034468e-01; \
      b1i = b1i + tvi*9.95734176295034468e-01; \
      b2r = b2r + tvr*7.98017227280239494e-01; \
      b2i = b2i + tvi*7.98017227280239494e-01; \
      b3r = b3r + tvr*1.83749517816570340e-01; \
      b3i = b3i + tvi*1.83749517816570340e-01; \
    } \
    { const T tur = uv[4], tui = uv[5], tvr = uv[20], tvi = uv[21]; \
      a0r = a0r + tur*4.45738355776538253e-01; \
      a0i = a0i + tui*4.45738355776538253e-01; \
      a1r = a1r + tur*-6.02634636379256405e-01; \
      a1i = a1i + tui*-6.02634636379256405e-01; \
      a2r = a2r + tur*-9.82973099683901785e-01; \
      a2i = a2i + tui*-9.82973099683901785e-01; \
      a3r = a3r + tur*-2.73662990072082890e-01; \
      a3i = a3i + tui*-2.73662990072082890e-01; \
      b0r = b0r + tvr*8.95163291355062340e-01; \
      b0i = b0i + tvi*8.95163291355062340e-01; \
      b1r = b1r + tvr*7.98017227280239494e-01; \
      b1i = b1i + tvi*7.98017227280239494e-01; \
      b2r = b2r + tvr*-1.83749517816570340e-01; \
      b2i = b2i + tvi*-1.83749517816570340e-01; \
      b3r = b3r + tvr*-9.61825643172819045e-01; \
      b3i = b3i + tvi*-9.61825643172819045e-01; \
    } \
    { const T tur = uv[6], tui = uv[7], tvr = uv[22], tvi = uv[23]; \
      a0r = a0r + tur*9.22683594633020021e-02; \
      a0i = a0i + tui*9.22683594633020021e-02; \
      a1r = a1r + tur*-9.82973099683901785e-01; \
      a1i = a1i + tui*-9.82973099683901785e-01; \
      a2r = a2r + tur*-2.73662990072082890e-01; \
      a2i = a2i + tui*-2.73662990072082890e-01; \
      a3r = a3r + tur*9.32472229404355812e-01; \
      a3i = a3i + tui*9.32472229404355812e-01; \
      b0r = b0r + tvr*9.95734176295034468e-01; \
      b0i = b0i + tvi*9.95734176295034468e-01; \
      b1r = b1r + tvr*1.83749517816570340e-01; \
      b1i = b1i + tvi*1.83749517816570340e-01; \
      b2r = b2r + tvr*-9.61825643172819045e-01; \
      b2i = b2i + tvi*-9.61825643172819045e-01; \
      b3r = b3r + tvr*-3.61241666187152921e-01; \
      b3i = b3i + tvi*-3.61241666187152921e-01; \
    } \
    { const T tur = uv[8], tui = uv[9], tvr = uv[24], tvi = uv[25]; \
      a0r = a0r + tur*-2.73662990072082890e-01; \
      a0i = a0i + tui*-2.73662990072082890e-01; \
      a1r = a1r + tur*-8.50217135729614104e-01; \
      a1i = a1i + tui*-8.50217135729614104e-01; \
      a2r = a2r + tur*7.39008917220659090e-01; \
      a2i = a2i + tui*7.39008917220659090e-01; \
      a3r = a3r + tur*4.45738355776538253e-01; \
      a3i = a3i + tui*4.45738355776538253e-01; \
      b0r = b0r + tvr*9.61825643172819045e-01; \
      b0i = b0i + tvi*9.61825643172819045e-01; \
      b1r = b1r + tvr*-5.26432162877355836e-01; \
      b1i = b1i + tvi*-5.26432162877355836e-01; \
      b2r = b2r + tvr*-6.73695643646557207e-01; \
      b2i = b2i + tvi*-6.73695643646557207e-01; \
      b3r = b3r + tvr*8.95163291355062340e-01; \
      b3i = b3i + tvi*8.95163291355062340e-01; \
    } \
    { const T tur = uv[10], tui = uv[11], tvr = uv[26], tvi = uv[27]; \
      a0r = a0r + tur*-6.02634636379256405e-01; \
      a0i = a0i + tui*-6.02634636379256405e-01; \
      a1r = a1r + tur*-2.73662990072082890e-01; \
      a1i = a1i + tui*-2.73662990072082890e-01; \
      a2r = a2r + tur*9.32472229404355812e-01; \
      a2i = a2i + tui*9.32472229404355812e-01; \
      a3r = a3r + tur*-8.50217135729614104e-01; \
      a3i = a3i + tui*-8.50217135729614104e-01; \
      b0r = b0r + tvr*7.98017227280239494e-01; \
      b0i = b0i + tvi*7.98017227280239494e-01; \
      b1r = b1r + tvr*-9.61825643172819045e-01; \
      b1i = b1i + tvi*-9.61825643172819045e-01; \
      b2r = b2r + tvr*3.61241666187152921e-01; \
      b2i = b2i + tvi*3.61241666187152921e-01; \
      b3r = b3r + tvr*5.26432162877355836e-01; \
      b3i = b3i + tvi*5.26432162877355836e-01; \
    } \
    { const T tur = uv[12], tui = uv[13], tvr = uv[28], tvi = uv[29]; \
      a0r = a0r + tur*-8.50217135729614104e-01; \
      a0i = a0i + tui*-8.50217135729614104e-01; \
      a1r = a1r + tur*4.45738355776538253e-01; \
      a1i = a1i + tui*4.45738355776538253e-01; \
      a2r = a2r + tur*9.22683594633020021e-02; \
      a2i = a2i + tui*9.22683594633020021e-02; \
      a3r = a3r + tur*-6.02634636379256405e-01; \
      a3i = a3i + tui*-6.02634636379256405e-01; \
      b0r = b0r + tvr*5.26432162877355836e-01; \
      b0i = b0i + tvi*5.26432162877355836e-01; \
      b1r = b1r + tvr*-8.95163291355062340e-01; \
      b1i = b1i + tvi*-8.95163291355062340e-01; \
      b2r = b2r + tvr*9.95734176295034468e-01; \
      b2i = b2i + tvi*9.95734176295034468e-01; \
      b3r = b3r + tvr*-7.98017227280239494e-01; \
      b3i = b3i + tvi*-7.98017227280239494e-01; \
    } \
    { const T tur = uv[14], tui = uv[15], tvr = uv[30], tvi = uv[31]; \
      a0r = a0r + tur*-9.82973099683901785e-01; \
      a0i = a0i + tui*-9.82973099683901785e-01; \
      a1r = a1r + tur*9.32472229404355812e-01; \
      a1i = a1i + tui*9.32472229404355812e-01; \
      a2r = a2r + tur*-8.50217135729614104e-01; \
      a2i = a2i + tui*-8.50217135729614104e-01; \
      a3r = a3r + tur*7.39008917220659090e-01; \
      a3i = a3i + tui*7.39008917220659090e-01; \
      b0r = b0r + tvr*1.83749517816570340e-01; \
      b0i = b0i + tvi*1.83749517816570340e-01; \
      b1r = b1r + tvr*-3.61241666187152921e-01; \
      b1i = b1i + tvi*-3.61241666187152921e-01; \
      b2r = b2r + tvr*5.26432162877355836e-01; \
      b2i = b2i + tvi*5.26432162877355836e-01; \
      b3r = b3r + tvr*-6.73695643646557207e-01; \
      b3i = b3i + tvi*-6.73695643646557207e-01; \
    } \
    yr[1] = a0r + b0i;  yi[1] = a0i - b0r; \
    yr[16] = a0r - b0i;  yi[16] = a0i + b0r; \
    yr[2] = a1r + b1i;  yi[2] = a1i - b1r; \
    yr[15] = a1r - b1i;  yi[15] = a1i + b1r; \
    yr[3] = a2r + b2i;  yi[3] = a2i - b2r; \
    yr[14] = a2r - b2i;  yi[14] = a2i + b2r; \
    yr[4] = a3r + b3i;  yi[4] = a3i - b3r; \
    yr[13] = a3r - b3i;  yi[13] = a3i + b3r; \
    { const T tur = uv[0], tui = uv[1], tvr = uv[16], tvi = uv[17]; \
      a0r = xr[0] + tur*-2.73662990072082890e-01; \
      a0i = xi[0] + tui*-2.73662990072082890e-01; \
      a1r = xr[0] + tur*-6.02634636379256405e-01; \
      a1i = xi[0] + tui*-6.02634636379256405e-01; \
      a2r = xr[0] + tur*-8.50217135729614104e-01; \
      a2i = xi[0] + tui*-8.50217135729614104e-01; \
      a3r = xr[0] + tur*-9.82973099683901785e-01; \
      a3i = xi[0] + tui*-9.82973099683901785e-01; \
      b0r = tvr*9.61825643172819045e-01; \
      b0i = tvi*9.61825643172819045e-01; \
      b1r = tvr*7.98017227280239494e-01; \
      b1i = tvi*7.98017227280239494e-01; \
      b2r = tvr*5.26432162877355836e-01; \
      b2i = tvi*5.26432162877355836e-01; \
      b3r = tvr*1.83749517816570340e-01; \
      b3i = tvi*1.83749517816570340e-01; \
    } \
    { const T tur = uv[2], tui = uv[3], tvr = uv[18], tvi = uv[19]; \
      a0r = a0r + tur*-8.50217135729614104e-01; \
      a0i = a0i + tui*-8.50217135729614104e-01; \
      a1r = a1r + tur*-2.73662990072082890e-01; \
      a1i = a1i + tui*-2.73662990072082890e-01; \
      a2r = a2r + tur*4.45738355776538253e-01; \
      a2i = a2i + tui*4.45738355776538253e-01; \
      a3r = a3r + tur*9.32472229404355812e-01; \
      a3i = a3i + tui*9.32472229404355812e-01; \
      b0r = b0r + tvr*-5.26432162877355836e-01; \
      b0i = b0i + tvi*-5.26432162877355836e-01; \
      b1r = b1r + tvr*-9.61825643172819045e-01; \
      b1i = b1i + tvi*-9.61825643172819045e-01; \
      b2r = b2r + tvr*-8.95163291355062340e-01; \
      b2i = b2i + tvi*-8.95163291355062340e-01; \
      b3r = b3r + tvr*-3.61241666187152921e-01; \
      b3i = b3i + tvi*-3.61241666187152921e-01; \
    } \
    { const T tur = uv[4], tui = uv[5], tvr = uv[20], tvi = uv[21]; \
      a0r = a0r + tur*7.39008917220659090e-01; \
      a0i = a0i + tui*7.39008917220659090e-01; \
      a1r = a1r + tur*9.32472229404355812e-01; \
      a1i = a1i + tui*9.32472229404355812e-01; \
      a2r = a2r + tur*9.22683594633020021e-02; \
      a2i = a2i + tui*9.22683594633020021e-02; \
      a3r = a3r + tur*-8.50217135729614104e-01; \
      a3i = a3i + tui*-8.50217135729614104e-01; \
      b0r = b0r + tvr*-6.73695643646557207e-01; \
      b0i = b0i + tvi*-6.73695643646557207e-01; \
      b1r = b1r + tvr*3.61241666187152921e-01; \
      b1i = b1i + tvi*3.61241666187152921e-01; \
      b2r = b2r + tvr*9.95734176295034468e-01; \
      b2i = b2i + tvi*9.95734176295034468e-01; \
      b3r = b3r + tvr*5.26432162877355836e-01; \
      b3i = b3i + tvi*5.26432162877355836e-01; \
    } \
    { const T tur = uv[6], tui = uv[7], tvr = uv[22], tvi = uv[23]; \
      a0r = a0r + tur*4.45738355776538253e-01; \
      a0i = a0i + tui*4.45738355776538253e-01; \
      a1r = a1r + tur*-8.50217135729614104e-01; \
      a1i = a1i + tui*-8.50217135729614104e-01; \
      a2r = a2r + tur*-6.02634636379256405e-01; \
      a2i = a2i + tui*-6.02634636379256405e-01; \
      a3r = a3r + tur*7.39008917220659090e-01; \
      a3i = a3i + tui*7.39008917220659090e-01; \
      b0r = b0r + tvr*8.95163291355062340e-01; \
      b0i = b0i + tvi*8.95163291355062340e-01; \
      b1r = b1r + tvr*5.26432162877355836e-01; \
      b1i = b1i + tvi*5.26432162877355836e-01; \
      b2r = b2r + tvr*-7.98017227280239494e-01; \
      b2i = b2i + tvi*-7.98017227280239494e-01; \
      b3r = b3r + tvr*-6.73695643646557207e-01; \
      b3i = b3i + tvi*-6.73695643646557207e-01; \
    } \
    { const T tur = uv[8], tui = uv[9], tvr = uv[24], tvi = uv[25]; \
      a0r = a0r + tur*-9.82973099683901785e-01; \
      a0i = a0i + tui*-9.82973099683901785e-01; \
      a1r = a1r + tur*9.22683594633020021e-02; \
      a1i = a1i + tui*9.22683594633020021e-02; \
      a2r = a2r + tur*9.32472229404355812e-01; \
      a2i = a2i + tui*9.32472229404355812e-01; \
      a3r = a3r + tur*-6.02634636379256405e-01; \
      a3i = a3i + tui*-6.02634636379256405e-01; \
      b0r = b0r + tvr*1.83749517816570340e-01; \
      b0i = b0i + tvi*1.83749517816570340e-01; \
      b1r = b1r + tvr*-9.95734176295034468e-01; \
      b1i = b1i + tvi*-9.95734176295034468e-01; \
      b2r = b2r + tvr*3.61241666187152921e-01; \
      b2i = b2i + tvi*3.61241666187152921e-01; \
      b3r = b3r + tvr*7.98017227280239494e-01; \
      b3i = b3i + tvi*7.98017227280239494e-01; \
    } \
    { const T tur = uv[10], tui = uv[11], tvr = uv[26], tvi = uv[27]; \
      a0r = a0r + tur*9.22683594633020021e-02; \
      a0i = a0i + tui*9.22683594633020021e-02; \
      a1r = a1r + tur*7.39008917220659090e-01; \
      a1i = a1i + tui*7.39008917220659090e-01; \
      a2r = a2r + tur*-9.82973099683901785e-01; \
      a2i = a2i + tui*-9.82973099683901785e-01; \
      a3r = a3r + tur*4.45738355776538253e-01; \
      a3i = a3i + tui*4.45738355776538253e-01; \
      b0r = b0r + tvr*-9.95734176295034468e-01; \
      b0i = b0i + tvi*-9.95734176295034468e-01; \
      b1r = b1r + tvr*6.73695643646557207e-01; \
      b1i = b1i + tvi*6.73695643646557207e-01; \
      b2r = b2r + tvr*1.83749517816570340e-01; \
      b2i = b2i + tvi*1.83749517816570340e-01; \
      b3r = b3r + tvr*-8.95163291355062340e-01; \
      b3i = b3i + tvi*-8.95163291355062340e-01; \
    } \
    { const T tur = uv[12], tui = uv[13], tvr = uv[28], tvi = uv[29]; \
      a0r = a0r + tur*9.32472229404355812e-01; \
      a0i = a0i + tui*9.32472229404355812e-01; \
      a1r = a1r + tur*-9.82973099683901785e-01; \
      a1i = a1i + tui*-9.82973099683901785e-01; \
      a2r = a2r + tur*7.39008917220659090e-01; \
      a2i = a2i + tui*7.39008917220659090e-01; \
      a3r = a3r + tur*-2.73662990072082890e-01; \
      a3i = a3i + tui*-2.73662990072082890e-01; \
      b0r = b0r + tvr*3.61241666187152921e-01; \
      b0i = b0i + tvi*3.61241666187152921e-01; \
      b1r = b1r + tvr*1.83749517816570340e-01; \
      b1i = b1i + tvi*1.83749517816570340e-01; \
      b2r = b2r + tvr*-6.73695643646557207e-01; \
      b2i = b2i + tvi*-6.73695643646557207e-01; \
      b3r = b3r + tvr*9.61825643172819045e-01; \
      b3i = b3i + tvi*9.61825643172819045e-01; \
    } \
    { const T tur = uv[14], tui = uv[15], tvr = uv[30], tvi = uv[31]; \
      a0r = a0r + tur*-6.02634636379256405e-01; \
      a0i = a0i + tui*-6.02634636379256405e-01; \
      a1r = a1r + tur*4.45738355776538253e-01; \
      a1i = a1i + tui*4.45738355776538253e-01; \
      a2r = a2r + tur*-2.73662990072082890e-01; \
      a2i = a2i + tui*-2.73662990072082890e-01; \
      a3r = a3r + tur*9.22683594633020021e-02; \
      a3i = a3i + tui*9.22683594633020021e-02; \
      b0r = b0r + tvr*7.98017227280239494e-01; \
      b0i = b0i + tvi*7.98017227280239494e-01; \
      b1r = b1r + tvr*-8.95163291355062340e-01; \
      b1i = b1i + tvi*-8.95163291355062340e-01; \
      b2r = b2r + tvr*9.61825643172819045e-01; \
      b2i = b2i + tvi*9.61825643172819045e-01; \
      b3r = b3r + tvr*-9.95734176295034468e-01; \
      b3i = b3i + tvi*-9.95734176295034468e-01; \
    } \
    yr[5] = a0r + b0i;  yi[5] = a0i - b0r; \
    yr[12] = a0r - b0i;  yi[12] = a0i + b0r; \
    yr[6] = a1r + b1i;  yi[6] = a1i - b1r; \
    yr[11] = a1r - b1i;  yi[11] = a1i + b1r; \
    yr[7] = a2r + b2i;  yi[7] = a2i - b2r; \
    yr[10] = a2r - b2i;  yi[10] = a2i + b2r; \
    yr[8] = a3r + b3i;  yi[8] = a3i - b3r; \
    yr[9] = a3r - b3i;  yi[9] = a3i + b3r; \
}

/* Kernel C: same fused A/B first half as kernel B, but the negacyclic S stage
 * is ONE sweep over the 8 v-pairs into 16 accumulators (all 8 outputs at
 * once), with the 8 distinct sine constants passed in as register operands.
 * The caller loads them once per pass and makes them opaque to gcc with an
 * empty asm, so they cannot be folded back into per-FMA .LC memory operands --
 * this is the register-residency fix for the -19% constant-load wall found in
 * round 1 (strategy record, "what did not work" item 6).  Peak liveness in the
 * sweep is 16 accumulators + 8 constants + 2 data = 26 vectors, which fits the
 * 32-register EVEX file (node and wallaby) but NOT a 16-register AVX2 file, so
 * this variant is expected to lose on a Haswell host and win where AVX-512 is
 * available; the plan-time tuner decides.
 * Bit-identity with kernels A/B: the accumulation order over m = 0..7 is
 * unchanged, and acc - v*C (vfnmadd) rounds identically to acc + v*(-C)
 * (vfmadd with the negated literal), so all variants still produce
 * byte-identical output. */
#define DEF_K17_C(SUF, T) \
static inline __attribute__((always_inline)) void k17_##SUF(const T *xr, const T *xi, T *yr, T *yi, \
        const T C0, const T C1, const T C2, const T C3, \
        const T C4, const T C5, const T C6, const T C7) \
{ \
    T vv[16], cc[16]; \
    T a0r, a1r, a2r, a3r, a0i, a1i, a2i, a3i, b0r, b1r, b2r, b3r, b0i, b1i, b2i, b3i, dr, di, u0r,u0i,u1r,u1i; \
    dr = xr[0]; di = xi[0]; \
    u0r = xr[1] + xr[16];  u0i = xi[1] + xi[16]; \
    u1r = xr[4] + xr[13];  u1i = xi[4] + xi[13]; \
    vv[0] = xr[1] - xr[16];  vv[1] = xi[1] - xi[16]; \
    vv[8] = xr[13] - xr[4];  vv[9] = xi[13] - xi[4]; \
    { const T pr = u0r + u1r, pi = u0i + u1i; \
      const T qr = u0r - u1r, qi = u0i - u1i; \
      dr = dr + pr;  di = di + pi; \
      a0r = xr[0] + pr*5.12370294433828866e-01; \
      a1r = xr[0] + pr*8.60376828522276954e-02; \
      a2r = xr[0] + pr*-1.21982091231621334e-01; \
      a3r = xr[0] + pr*-7.26425886054435255e-01; \
      a0i = xi[0] + pi*5.12370294433828866e-01; \
      a1i = xi[0] + pi*8.60376828522276954e-02; \
      a2i = xi[0] + pi*-1.21982091231621334e-01; \
      a3i = xi[0] + pi*-7.26425886054435255e-01; \
      b0r = qr*4.20101934970526891e-01; \
      b1r = qr*3.59700672924310572e-01; \
      b2r = qr*-8.60991008452280493e-01; \
      b3r = qr*-1.23791249675178877e-01; \
      b0i = qi*4.20101934970526891e-01; \
      b1i = qi*3.59700672924310572e-01; \
      b2i = qi*-8.60991008452280493e-01; \
      b3i = qi*-1.23791249675178877e-01; \
    } \
    u0r = xr[3] + xr[14];  u0i = xi[3] + xi[14]; \
    u1r = xr[5] + xr[12];  u1i = xi[5] + xi[12]; \
    vv[2] = xr[3] - xr[14];  vv[3] = xi[3] - xi[14]; \
    vv[10] = xr[5] - xr[12];  vv[11] = xi[5] - xi[12]; \
    { const T pr = u0r + u1r, pi = u0i + u1i; \
      const T qr = u0r - u1r, qi = u0i - u1i; \
      dr = dr + pr;  di = di + pi; \
      a0r = a0r + pr*8.60376828522276954e-02; \
      a1r = a1r + pr*-1.21982091231621334e-01; \
      a2r = a2r + pr*-7.26425886054435255e-01; \
      a3r = a3r + pr*5.12370294433828866e-01; \
      a0i = a0i + pi*8.60376828522276954e-02; \
      a1i = a1i + pi*-1.21982091231621334e-01; \
      a2i = a2i + pi*-7.26425886054435255e-01; \
      a3i = a3i + pi*5.12370294433828866e-01; \
      b0r = b0r + qr*3.59700672924310572e-01; \
      b1r = b1r + qr*-8.60991008452280493e-01; \
      b2r = b2r + qr*-1.23791249675178877e-01; \
      b3r = b3r + qr*-4.20101934970526891e-01; \
      b0i = b0i + qi*3.59700672924310572e-01; \
      b1i = b1i + qi*-8.60991008452280493e-01; \
      b2i = b2i + qi*-1.23791249675178877e-01; \
      b3i = b3i + qi*-4.20101934970526891e-01; \
    } \
    u0r = xr[8] + xr[9];  u0i = xi[8] + xi[9]; \
    u1r = xr[2] + xr[15];  u1i = xi[2] + xi[15]; \
    vv[4] = xr[9] - xr[8];  vv[5] = xi[9] - xi[8]; \
    vv[12] = xr[15] - xr[2];  vv[13] = xi[15] - xi[2]; \
    { const T pr = u0r + u1r, pi = u0i + u1i; \
      const T qr = u0r - u1r, qi = u0i - u1i; \
      dr = dr + pr;  di = di + pi; \
      a0r = a0r + pr*-1.21982091231621334e-01; \
      a1r = a1r + pr*-7.26425886054435255e-01; \
      a2r = a2r + pr*5.12370294433828866e-01; \
      a3r = a3r + pr*8.60376828522276954e-02; \
      a0i = a0i + pi*-1.21982091231621334e-01; \
      a1i = a1i + pi*-7.26425886054435255e-01; \
      a2i = a2i + pi*5.12370294433828866e-01; \
      a3i = a3i + pi*8.60376828522276954e-02; \
      b0r = b0r + qr*-8.60991008452280493e-01; \
      b1r = b1r + qr*-1.23791249675178877e-01; \
      b2r = b2r + qr*-4.20101934970526891e-01; \
      b3r = b3r + qr*-3.59700672924310572e-01; \
      b0i = b0i + qi*-8.60991008452280493e-01; \
      b1i = b1i + qi*-1.23791249675178877e-01; \
      b2i = b2i + qi*-4.20101934970526891e-01; \
      b3i = b3i + qi*-3.59700672924310572e-01; \
    } \
    u0r = xr[7] + xr[10];  u0i = xi[7] + xi[10]; \
    u1r = xr[6] + xr[11];  u1i = xi[6] + xi[11]; \
    vv[6] = xr[10] - xr[7];  vv[7] = xi[10] - xi[7]; \
    vv[14] = xr[11] - xr[6];  vv[15] = xi[11] - xi[6]; \
    { const T pr = u0r + u1r, pi = u0i + u1i; \
      const T qr = u0r - u1r, qi = u0i - u1i; \
      dr = dr + pr;  di = di + pi; \
      a0r = a0r + pr*-7.26425886054435255e-01; \
      a1r = a1r + pr*5.12370294433828866e-01; \
      a2r = a2r + pr*8.60376828522276954e-02; \
      a3r = a3r + pr*-1.21982091231621334e-01; \
      a0i = a0i + pi*-7.26425886054435255e-01; \
      a1i = a1i + pi*5.12370294433828866e-01; \
      a2i = a2i + pi*8.60376828522276954e-02; \
      a3i = a3i + pi*-1.21982091231621334e-01; \
      b0r = b0r + qr*-1.23791249675178877e-01; \
      b1r = b1r + qr*-4.20101934970526891e-01; \
      b2r = b2r + qr*-3.59700672924310572e-01; \
      b3r = b3r + qr*8.60991008452280493e-01; \
      b0i = b0i + qi*-1.23791249675178877e-01; \
      b1i = b1i + qi*-4.20101934970526891e-01; \
      b2i = b2i + qi*-3.59700672924310572e-01; \
      b3i = b3i + qi*8.60991008452280493e-01; \
    } \
    yr[0] = dr;  yi[0] = di; \
    cc[0] = a0r + b0r;  cc[1] = a0i + b0i; \
    cc[8] = a0r - b0r;  cc[9] = a0i - b0i; \
    cc[2] = a1r + b1r;  cc[3] = a1i + b1i; \
    cc[10] = a1r - b1r;  cc[11] = a1i - b1i; \
    cc[4] = a2r + b2r;  cc[5] = a2i + b2i; \
    cc[12] = a2r - b2r;  cc[13] = a2i - b2i; \
    cc[6] = a3r + b3r;  cc[7] = a3i + b3i; \
    cc[14] = a3r - b3r;  cc[15] = a3i - b3i; \
    { \
    T s0r,s1r,s2r,s3r,s4r,s5r,s6r,s7r, s0i,s1i,s2i,s3i,s4i,s5i,s6i,s7i; \
    { const T vr = vv[0], vi = vv[1];   /* m=0 */ \
      s0r = vr*C0;  s0i = vi*C0; \
      s1r = vr*C1;  s1i = vi*C1; \
      s2r = vr*C2;  s2i = vi*C2; \
      s3r = vr*C3;  s3i = vi*C3; \
      s4r = vr*C4;  s4i = vi*C4; \
      s5r = vr*C5;  s5i = vi*C5; \
      s6r = vr*C6;  s6i = vi*C6; \
      s7r = vr*C7;  s7i = vi*C7; \
    } \
    { const T vr = vv[2], vi = vv[3];   /* m=1 */ \
      s0r = s0r + vr*C1;  s0i = s0i + vi*C1; \
      s1r = s1r + vr*C2;  s1i = s1i + vi*C2; \
      s2r = s2r + vr*C3;  s2i = s2i + vi*C3; \
      s3r = s3r + vr*C4;  s3i = s3i + vi*C4; \
      s4r = s4r + vr*C5;  s4i = s4i + vi*C5; \
      s5r = s5r + vr*C6;  s5i = s5i + vi*C6; \
      s6r = s6r + vr*C7;  s6i = s6i + vi*C7; \
      s7r = s7r - vr*C0;  s7i = s7i - vi*C0; \
    } \
    { const T vr = vv[4], vi = vv[5];   /* m=2 */ \
      s0r = s0r + vr*C2;  s0i = s0i + vi*C2; \
      s1r = s1r + vr*C3;  s1i = s1i + vi*C3; \
      s2r = s2r + vr*C4;  s2i = s2i + vi*C4; \
      s3r = s3r + vr*C5;  s3i = s3i + vi*C5; \
      s4r = s4r + vr*C6;  s4i = s4i + vi*C6; \
      s5r = s5r + vr*C7;  s5i = s5i + vi*C7; \
      s6r = s6r - vr*C0;  s6i = s6i - vi*C0; \
      s7r = s7r - vr*C1;  s7i = s7i - vi*C1; \
    } \
    { const T vr = vv[6], vi = vv[7];   /* m=3 */ \
      s0r = s0r + vr*C3;  s0i = s0i + vi*C3; \
      s1r = s1r + vr*C4;  s1i = s1i + vi*C4; \
      s2r = s2r + vr*C5;  s2i = s2i + vi*C5; \
      s3r = s3r + vr*C6;  s3i = s3i + vi*C6; \
      s4r = s4r + vr*C7;  s4i = s4i + vi*C7; \
      s5r = s5r - vr*C0;  s5i = s5i - vi*C0; \
      s6r = s6r - vr*C1;  s6i = s6i - vi*C1; \
      s7r = s7r - vr*C2;  s7i = s7i - vi*C2; \
    } \
    { const T vr = vv[8], vi = vv[9];   /* m=4 */ \
      s0r = s0r + vr*C4;  s0i = s0i + vi*C4; \
      s1r = s1r + vr*C5;  s1i = s1i + vi*C5; \
      s2r = s2r + vr*C6;  s2i = s2i + vi*C6; \
      s3r = s3r + vr*C7;  s3i = s3i + vi*C7; \
      s4r = s4r - vr*C0;  s4i = s4i - vi*C0; \
      s5r = s5r - vr*C1;  s5i = s5i - vi*C1; \
      s6r = s6r - vr*C2;  s6i = s6i - vi*C2; \
      s7r = s7r - vr*C3;  s7i = s7i - vi*C3; \
    } \
    { const T vr = vv[10], vi = vv[11]; /* m=5 */ \
      s0r = s0r + vr*C5;  s0i = s0i + vi*C5; \
      s1r = s1r + vr*C6;  s1i = s1i + vi*C6; \
      s2r = s2r + vr*C7;  s2i = s2i + vi*C7; \
      s3r = s3r - vr*C0;  s3i = s3i - vi*C0; \
      s4r = s4r - vr*C1;  s4i = s4i - vi*C1; \
      s5r = s5r - vr*C2;  s5i = s5i - vi*C2; \
      s6r = s6r - vr*C3;  s6i = s6i - vi*C3; \
      s7r = s7r - vr*C4;  s7i = s7i - vi*C4; \
    } \
    { const T vr = vv[12], vi = vv[13]; /* m=6 */ \
      s0r = s0r + vr*C6;  s0i = s0i + vi*C6; \
      s1r = s1r + vr*C7;  s1i = s1i + vi*C7; \
      s2r = s2r - vr*C0;  s2i = s2i - vi*C0; \
      s3r = s3r - vr*C1;  s3i = s3i - vi*C1; \
      s4r = s4r - vr*C2;  s4i = s4i - vi*C2; \
      s5r = s5r - vr*C3;  s5i = s5i - vi*C3; \
      s6r = s6r - vr*C4;  s6i = s6i - vi*C4; \
      s7r = s7r - vr*C5;  s7i = s7i - vi*C5; \
    } \
    { const T vr = vv[14], vi = vv[15]; /* m=7 */ \
      s0r = s0r + vr*C7;  s0i = s0i + vi*C7; \
      s1r = s1r - vr*C0;  s1i = s1i - vi*C0; \
      s2r = s2r - vr*C1;  s2i = s2i - vi*C1; \
      s3r = s3r - vr*C2;  s3i = s3i - vi*C2; \
      s4r = s4r - vr*C3;  s4i = s4i - vi*C3; \
      s5r = s5r - vr*C4;  s5i = s5i - vi*C4; \
      s6r = s6r - vr*C5;  s6i = s6i - vi*C5; \
      s7r = s7r - vr*C6;  s7i = s7i - vi*C6; \
    } \
    { const T tcr = cc[0], tci = cc[1]; \
      yr[1] = tcr + s0i;  yi[1] = tci - s0r; \
      yr[16] = tcr - s0i;  yi[16] = tci + s0r; } \
    { const T tcr = cc[2], tci = cc[3]; \
      yr[3] = tcr + s1i;  yi[3] = tci - s1r; \
      yr[14] = tcr - s1i;  yi[14] = tci + s1r; } \
    { const T tcr = cc[4], tci = cc[5]; \
      yr[8] = tcr - s2i;  yi[8] = tci + s2r; \
      yr[9] = tcr + s2i;  yi[9] = tci - s2r; } \
    { const T tcr = cc[6], tci = cc[7]; \
      yr[7] = tcr - s3i;  yi[7] = tci + s3r; \
      yr[10] = tcr + s3i;  yi[10] = tci - s3r; } \
    { const T tcr = cc[8], tci = cc[9]; \
      yr[4] = tcr - s4i;  yi[4] = tci + s4r; \
      yr[13] = tcr + s4i;  yi[13] = tci - s4r; } \
    { const T tcr = cc[10], tci = cc[11]; \
      yr[5] = tcr + s5i;  yi[5] = tci - s5r; \
      yr[12] = tcr - s5i;  yi[12] = tci + s5r; } \
    { const T tcr = cc[12], tci = cc[13]; \
      yr[2] = tcr - s6i;  yi[2] = tci + s6r; \
      yr[15] = tcr + s6i;  yi[15] = tci - s6r; } \
    { const T tcr = cc[14], tci = cc[15]; \
      yr[6] = tcr - s7i;  yi[6] = tci + s7r; \
      yr[11] = tcr + s7i;  yi[11] = tci - s7r; } \
    } \
}

/* The 8 distinct negacyclic sine constants s~(t) = "S column" of the skew-
 * circulant, natural signs, exactly the literals kernels A/B use. */
#define DECL_SC(T) \
    T C0 = BCAST(T, 3.61241666187152921e-01); \
    T C1 = BCAST(T, 8.95163291355062340e-01); \
    T C2 = BCAST(T,-1.83749517816570340e-01); \
    T C3 = BCAST(T,-5.26432162877355836e-01); \
    T C4 = BCAST(T,-9.95734176295034468e-01); \
    T C5 = BCAST(T, 9.61825643172819045e-01); \
    T C6 = BCAST(T,-6.73695643646557207e-01); \
    T C7 = BCAST(T,-7.98017227280239494e-01)

/* Make the constants opaque so gcc cannot fold them back into .LC memory
 * operands or rematerialise the broadcast inside the loop.  Only meaningful
 * (and only encodable as "v") when the EVEX register file exists. */
#if defined(__AVX512F__) && defined(__AVX512VL__)
#define OPAQUE_SC() __asm__("" : "+v"(C0),"+v"(C1),"+v"(C2),"+v"(C3),"+v"(C4),"+v"(C5),"+v"(C6),"+v"(C7))
#else
#define OPAQUE_SC() ((void)0)
#endif

#ifdef L17_DENSE_KERNEL
#define DEF_K17  DEF_K17_DENSE
#define DEF_K17B DEF_K17_DENSE
#else
#define DEF_K17  DEF_K17_A
#define DEF_K17B DEF_K17_B
#endif

DEF_K17(s,  double)     /* scalar, for the one spectator that does not fill a lane */
DEF_K17(a4, v4)
DEF_K17(a8, v8)
DEF_K17B(b4, v4)
DEF_K17B(b8, v8)
#ifndef L17_DENSE_KERNEL
DEF_K17_C(c4, v4)
DEF_K17_C(c8, v8)
#endif


static inline void tr8(v8 *a)
{
    const v8 t2_0 = SH8(a[0], a[4], 0,1,2,3,8,9,10,11);
    const v8 t2_4 = SH8(a[0], a[4], 4,5,6,7,12,13,14,15);
    const v8 t2_1 = SH8(a[1], a[5], 0,1,2,3,8,9,10,11);
    const v8 t2_5 = SH8(a[1], a[5], 4,5,6,7,12,13,14,15);
    const v8 t2_2 = SH8(a[2], a[6], 0,1,2,3,8,9,10,11);
    const v8 t2_6 = SH8(a[2], a[6], 4,5,6,7,12,13,14,15);
    const v8 t2_3 = SH8(a[3], a[7], 0,1,2,3,8,9,10,11);
    const v8 t2_7 = SH8(a[3], a[7], 4,5,6,7,12,13,14,15);
    const v8 t1_0 = SH8(t2_0, t2_2, 0,1,8,9,4,5,12,13);
    const v8 t1_2 = SH8(t2_0, t2_2, 2,3,10,11,6,7,14,15);
    const v8 t1_1 = SH8(t2_1, t2_3, 0,1,8,9,4,5,12,13);
    const v8 t1_3 = SH8(t2_1, t2_3, 2,3,10,11,6,7,14,15);
    const v8 t1_4 = SH8(t2_4, t2_6, 0,1,8,9,4,5,12,13);
    const v8 t1_6 = SH8(t2_4, t2_6, 2,3,10,11,6,7,14,15);
    const v8 t1_5 = SH8(t2_5, t2_7, 0,1,8,9,4,5,12,13);
    const v8 t1_7 = SH8(t2_5, t2_7, 2,3,10,11,6,7,14,15);
    a[0] = SH8(t1_0, t1_1, 0,8,2,10,4,12,6,14);
    a[1] = SH8(t1_0, t1_1, 1,9,3,11,5,13,7,15);
    a[2] = SH8(t1_2, t1_3, 0,8,2,10,4,12,6,14);
    a[3] = SH8(t1_2, t1_3, 1,9,3,11,5,13,7,15);
    a[4] = SH8(t1_4, t1_5, 0,8,2,10,4,12,6,14);
    a[5] = SH8(t1_4, t1_5, 1,9,3,11,5,13,7,15);
    a[6] = SH8(t1_6, t1_7, 0,8,2,10,4,12,6,14);
    a[7] = SH8(t1_6, t1_7, 1,9,3,11,5,13,7,15);
}

static inline void tr4(v4 *a)
{
    const v4 t1_0 = SH4(a[0], a[2], 0,1,4,5);
    const v4 t1_2 = SH4(a[0], a[2], 2,3,6,7);
    const v4 t1_1 = SH4(a[1], a[3], 0,1,4,5);
    const v4 t1_3 = SH4(a[1], a[3], 2,3,6,7);
    a[0] = SH4(t1_0, t1_1, 0,4,2,6);
    a[1] = SH4(t1_0, t1_1, 1,5,3,7);
    a[2] = SH4(t1_2, t1_3, 0,4,2,6);
    a[3] = SH4(t1_2, t1_3, 1,5,3,7);
}

static inline void tst8(const v8 *yr, const v8 *yi, double *dr, double *di,
                        const int32_t *b)
{
    v8 t[8];
    for (int k = 0; k < 2; ++k) {
        for (int i = 0; i < 8; ++i) t[i] = yr[k*8 + i];
        tr8(t);
        for (int j = 0; j < 8; ++j) *(v8u *)(dr + b[j] + k*8) = t[j];
        for (int i = 0; i < 8; ++i) t[i] = yi[k*8 + i];
        tr8(t);
        for (int j = 0; j < 8; ++j) *(v8u *)(di + b[j] + k*8) = t[j];
    }
    for (int j = 0; j < 8; ++j) { dr[b[j]+16] = yr[16][j]; di[b[j]+16] = yi[16][j]; }
}

static inline void tsto8(const v8 *yr, const v8 *yi, double *out, const int32_t *b)
{
    v8 tr_[8], ti_[8];
    for (int k = 0; k < 2; ++k) {
        for (int i = 0; i < 8; ++i) { tr_[i] = yr[k*8 + i]; ti_[i] = yi[k*8 + i]; }
        tr8(tr_); tr8(ti_);
        for (int j = 0; j < 8; ++j) {
            double *q = out + b[j] + k*16;
            *(v8u *)(q)     = SH8(tr_[j], ti_[j], 0,8,1,9,2,10,3,11);
            *(v8u *)(q + 8) = SH8(tr_[j], ti_[j], 4,12,5,13,6,14,7,15);
        }
    }
    for (int j = 0; j < 8; ++j) { out[b[j]+32] = yr[16][j]; out[b[j]+33] = yi[16][j]; }
}

static inline void tst4(const v4 *yr, const v4 *yi, double *dr, double *di,
                        const int32_t *b)
{
    v4 t[4];
    for (int k = 0; k < 4; ++k) {
        for (int i = 0; i < 4; ++i) t[i] = yr[k*4 + i];
        tr4(t);
        for (int j = 0; j < 4; ++j) *(v4u *)(dr + b[j] + k*4) = t[j];
        for (int i = 0; i < 4; ++i) t[i] = yi[k*4 + i];
        tr4(t);
        for (int j = 0; j < 4; ++j) *(v4u *)(di + b[j] + k*4) = t[j];
    }
    for (int j = 0; j < 4; ++j) { dr[b[j]+16] = yr[16][j]; di[b[j]+16] = yi[16][j]; }
}

static inline void tsto4(const v4 *yr, const v4 *yi, double *out, const int32_t *b)
{
    v4 tr_[4], ti_[4];
    for (int k = 0; k < 4; ++k) {
        for (int i = 0; i < 4; ++i) { tr_[i] = yr[k*4 + i]; ti_[i] = yi[k*4 + i]; }
        tr4(tr_); tr4(ti_);
        for (int j = 0; j < 4; ++j) {
            double *q = out + b[j] + k*8;
            *(v4u *)(q)     = SH4(tr_[j], ti_[j], 0,4,1,5);
            *(v4u *)(q + 4) = SH4(tr_[j], ti_[j], 2,6,3,7);
        }
    }
    for (int j = 0; j < 4; ++j) { out[b[j]+32] = yr[16][j]; out[b[j]+33] = yi[16][j]; }
}

#ifndef L17_DENSE_KERNEL
/* Blocked pass-1 stores for the fused variants: lane j's 17 kx values go to
 * the kx-BLOCKED layout -- kx < 16 in chunks of the vector width at
 * b[j] + (kx/w)*(17*w), kx = 16 to the separate tail region at t[j]. */
static inline void tst8f(const v8 *yr, const v8 *yi, double *dr, double *di,
                         const int32_t *b, const int32_t *t)
{
    v8 tmp[8];
    for (int k = 0; k < 2; ++k) {
        for (int i = 0; i < 8; ++i) tmp[i] = yr[k*8 + i];
        tr8(tmp);
        for (int j = 0; j < 8; ++j) *(v8u *)(dr + b[j] + k*136) = tmp[j];
        for (int i = 0; i < 8; ++i) tmp[i] = yi[k*8 + i];
        tr8(tmp);
        for (int j = 0; j < 8; ++j) *(v8u *)(di + b[j] + k*136) = tmp[j];
    }
    for (int j = 0; j < 8; ++j) { dr[t[j]] = yr[16][j]; di[t[j]] = yi[16][j]; }
}

static inline void tst4f(const v4 *yr, const v4 *yi, double *dr, double *di,
                         const int32_t *b, const int32_t *t)
{
    v4 tmp[4];
    for (int k = 0; k < 4; ++k) {
        for (int i = 0; i < 4; ++i) tmp[i] = yr[k*4 + i];
        tr4(tmp);
        for (int j = 0; j < 4; ++j) *(v4u *)(dr + b[j] + k*68) = tmp[j];
        for (int i = 0; i < 4; ++i) tmp[i] = yi[k*4 + i];
        tr4(tmp);
        for (int j = 0; j < 4; ++j) *(v4u *)(di + b[j] + k*68) = tmp[j];
    }
    for (int j = 0; j < 4; ++j) { dr[t[j]] = yr[16][j]; di[t[j]] = yi[16][j]; }
}
#endif /* !L17_DENSE_KERNEL */

static void pass1_a4(const double *in, double *dr, double *di, const int32_t *base)
{
    for (int g = 0; g < 72; ++g) {
        const double *p = in + (size_t)2*4*g;
        v4 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            const v4u lo = *(const v4u *)(p + (size_t)578*a);
            const v4u hi = *(const v4u *)(p + (size_t)578*a + 4);
            xr[a] = SH4(lo, hi, 0,2,4,6);
            xi[a] = SH4(lo, hi, 1,3,5,7);
        }
        k17_a4(xr, xi, yr, yi);
        tst4(yr, yi, dr, di, base + (size_t)4*g);
    }
}

static void pass2_a4(const double *sr, const double *si, double *dr, double *di,
                       const int32_t *base, const double *pf)
{
    for (int g = 0; g < 72; ++g) {
        if (pf)
            for (int k = 0; k < 17; ++k)
                __builtin_prefetch(pf + ((size_t)17*g + k)*8, 0, 2);
        v4 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            xr[a] = ((const v4 *)sr)[a*(SP/4) + g];
            xi[a] = ((const v4 *)si)[a*(SP/4) + g];
        }
        k17_a4(xr, xi, yr, yi);
        tst4(yr, yi, dr, di, base + (size_t)4*g);
    }
}

static void pass3_a4(const double *sr, const double *si, double *out,
                       const int32_t *base)
{
    for (int g = 0; g < 72; ++g) {
        v4 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            xr[a] = ((const v4 *)sr)[a*(SP/4) + g];
            xi[a] = ((const v4 *)si)[a*(SP/4) + g];
        }
        k17_a4(xr, xi, yr, yi);
        tsto4(yr, yi, out, base + (size_t)4*g);
    }
}

static void pass1_a8(const double *in, double *dr, double *di, const int32_t *base)
{
    for (int g = 0; g < 36; ++g) {
        const double *p = in + (size_t)2*8*g;
        v8 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            const v8u lo = *(const v8u *)(p + (size_t)578*a);
            const v8u hi = *(const v8u *)(p + (size_t)578*a + 8);
            xr[a] = SH8(lo, hi, 0,2,4,6,8,10,12,14);
            xi[a] = SH8(lo, hi, 1,3,5,7,9,11,13,15);
        }
        k17_a8(xr, xi, yr, yi);
        tst8(yr, yi, dr, di, base + (size_t)8*g);
    }
}

static void pass2_a8(const double *sr, const double *si, double *dr, double *di,
                       const int32_t *base, const double *pf)
{
    for (int g = 0; g < 36; ++g) {
        if (pf)
            for (int k = 0; k < 34; ++k)
                __builtin_prefetch(pf + ((size_t)34*g + k)*8, 0, 2);
        v8 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            xr[a] = ((const v8 *)sr)[a*(SP/8) + g];
            xi[a] = ((const v8 *)si)[a*(SP/8) + g];
        }
        k17_a8(xr, xi, yr, yi);
        tst8(yr, yi, dr, di, base + (size_t)8*g);
    }
}

static void pass3_a8(const double *sr, const double *si, double *out,
                       const int32_t *base)
{
    for (int g = 0; g < 36; ++g) {
        v8 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            xr[a] = ((const v8 *)sr)[a*(SP/8) + g];
            xi[a] = ((const v8 *)si)[a*(SP/8) + g];
        }
        k17_a8(xr, xi, yr, yi);
        tsto8(yr, yi, out, base + (size_t)8*g);
    }
}

static void pass1_b4(const double *in, double *dr, double *di, const int32_t *base)
{
    for (int g = 0; g < 72; ++g) {
        const double *p = in + (size_t)2*4*g;
        v4 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            const v4u lo = *(const v4u *)(p + (size_t)578*a);
            const v4u hi = *(const v4u *)(p + (size_t)578*a + 4);
            xr[a] = SH4(lo, hi, 0,2,4,6);
            xi[a] = SH4(lo, hi, 1,3,5,7);
        }
        k17_b4(xr, xi, yr, yi);
        tst4(yr, yi, dr, di, base + (size_t)4*g);
    }
}

static void pass2_b4(const double *sr, const double *si, double *dr, double *di,
                       const int32_t *base, const double *pf)
{
    for (int g = 0; g < 72; ++g) {
        if (pf)
            for (int k = 0; k < 17; ++k)
                __builtin_prefetch(pf + ((size_t)17*g + k)*8, 0, 2);
        v4 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            xr[a] = ((const v4 *)sr)[a*(SP/4) + g];
            xi[a] = ((const v4 *)si)[a*(SP/4) + g];
        }
        k17_b4(xr, xi, yr, yi);
        tst4(yr, yi, dr, di, base + (size_t)4*g);
    }
}

static void pass3_b4(const double *sr, const double *si, double *out,
                       const int32_t *base)
{
    for (int g = 0; g < 72; ++g) {
        v4 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            xr[a] = ((const v4 *)sr)[a*(SP/4) + g];
            xi[a] = ((const v4 *)si)[a*(SP/4) + g];
        }
        k17_b4(xr, xi, yr, yi);
        tsto4(yr, yi, out, base + (size_t)4*g);
    }
}

static void pass1_b8(const double *in, double *dr, double *di, const int32_t *base)
{
    for (int g = 0; g < 36; ++g) {
        const double *p = in + (size_t)2*8*g;
        v8 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            const v8u lo = *(const v8u *)(p + (size_t)578*a);
            const v8u hi = *(const v8u *)(p + (size_t)578*a + 8);
            xr[a] = SH8(lo, hi, 0,2,4,6,8,10,12,14);
            xi[a] = SH8(lo, hi, 1,3,5,7,9,11,13,15);
        }
        k17_b8(xr, xi, yr, yi);
        tst8(yr, yi, dr, di, base + (size_t)8*g);
    }
}

static void pass2_b8(const double *sr, const double *si, double *dr, double *di,
                       const int32_t *base, const double *pf)
{
    for (int g = 0; g < 36; ++g) {
        if (pf)
            for (int k = 0; k < 34; ++k)
                __builtin_prefetch(pf + ((size_t)34*g + k)*8, 0, 2);
        v8 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            xr[a] = ((const v8 *)sr)[a*(SP/8) + g];
            xi[a] = ((const v8 *)si)[a*(SP/8) + g];
        }
        k17_b8(xr, xi, yr, yi);
        tst8(yr, yi, dr, di, base + (size_t)8*g);
    }
}

static void pass3_b8(const double *sr, const double *si, double *out,
                       const int32_t *base)
{
    for (int g = 0; g < 36; ++g) {
        v8 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            xr[a] = ((const v8 *)sr)[a*(SP/8) + g];
            xi[a] = ((const v8 *)si)[a*(SP/8) + g];
        }
        k17_b8(xr, xi, yr, yi);
        tsto8(yr, yi, out, base + (size_t)8*g);
    }
}

#ifndef L17_DENSE_KERNEL
static void pass1_c4(const double *in, double *dr, double *di, const int32_t *base)
{
    DECL_SC(v4); OPAQUE_SC();
    for (int g = 0; g < 72; ++g) {
        const double *p = in + (size_t)2*4*g;
        v4 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            const v4u lo = *(const v4u *)(p + (size_t)578*a);
            const v4u hi = *(const v4u *)(p + (size_t)578*a + 4);
            xr[a] = SH4(lo, hi, 0,2,4,6);
            xi[a] = SH4(lo, hi, 1,3,5,7);
        }
        k17_c4(xr, xi, yr, yi, C0,C1,C2,C3,C4,C5,C6,C7);
        tst4(yr, yi, dr, di, base + (size_t)4*g);
    }
}

static void pass2_c4(const double *sr, const double *si, double *dr, double *di,
                       const int32_t *base, const double *pf)
{
    DECL_SC(v4); OPAQUE_SC();
    for (int g = 0; g < 72; ++g) {
        if (pf)
            for (int k = 0; k < 17; ++k)
                __builtin_prefetch(pf + ((size_t)17*g + k)*8, 0, 2);
        v4 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            xr[a] = ((const v4 *)sr)[a*(SP/4) + g];
            xi[a] = ((const v4 *)si)[a*(SP/4) + g];
        }
        k17_c4(xr, xi, yr, yi, C0,C1,C2,C3,C4,C5,C6,C7);
        tst4(yr, yi, dr, di, base + (size_t)4*g);
    }
}

static void pass3_c4(const double *sr, const double *si, double *out,
                       const int32_t *base)
{
    DECL_SC(v4); OPAQUE_SC();
    for (int g = 0; g < 72; ++g) {
        v4 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            xr[a] = ((const v4 *)sr)[a*(SP/4) + g];
            xi[a] = ((const v4 *)si)[a*(SP/4) + g];
        }
        k17_c4(xr, xi, yr, yi, C0,C1,C2,C3,C4,C5,C6,C7);
        tsto4(yr, yi, out, base + (size_t)4*g);
    }
}

static void pass1_c8(const double *in, double *dr, double *di, const int32_t *base)
{
    DECL_SC(v8); OPAQUE_SC();
    for (int g = 0; g < 36; ++g) {
        const double *p = in + (size_t)2*8*g;
        v8 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            const v8u lo = *(const v8u *)(p + (size_t)578*a);
            const v8u hi = *(const v8u *)(p + (size_t)578*a + 8);
            xr[a] = SH8(lo, hi, 0,2,4,6,8,10,12,14);
            xi[a] = SH8(lo, hi, 1,3,5,7,9,11,13,15);
        }
        k17_c8(xr, xi, yr, yi, C0,C1,C2,C3,C4,C5,C6,C7);
        tst8(yr, yi, dr, di, base + (size_t)8*g);
    }
}

static void pass2_c8(const double *sr, const double *si, double *dr, double *di,
                       const int32_t *base, const double *pf)
{
    DECL_SC(v8); OPAQUE_SC();
    for (int g = 0; g < 36; ++g) {
        if (pf)
            for (int k = 0; k < 34; ++k)
                __builtin_prefetch(pf + ((size_t)34*g + k)*8, 0, 2);
        v8 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            xr[a] = ((const v8 *)sr)[a*(SP/8) + g];
            xi[a] = ((const v8 *)si)[a*(SP/8) + g];
        }
        k17_c8(xr, xi, yr, yi, C0,C1,C2,C3,C4,C5,C6,C7);
        tst8(yr, yi, dr, di, base + (size_t)8*g);
    }
}

static void pass3_c8(const double *sr, const double *si, double *out,
                       const int32_t *base)
{
    DECL_SC(v8); OPAQUE_SC();
    for (int g = 0; g < 36; ++g) {
        v8 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            xr[a] = ((const v8 *)sr)[a*(SP/8) + g];
            xi[a] = ((const v8 *)si)[a*(SP/8) + g];
        }
        k17_c8(xr, xi, yr, yi, C0,C1,C2,C3,C4,C5,C6,C7);
        tsto8(yr, yi, out, base + (size_t)8*g);
    }
}

/* ---------- fused-pass-2+3 variants (f4 = 256-bit/kernel B, f8 = 512/kernel C)
 *
 * Pass 1 stores A in a kx-BLOCKED spectator order:
 *     (y, z, kx) at  y*SP + (kx/w)*(17*w) + z*w + kx%w     for kx < 16,
 *     (y, z, 16) at  y*SP + 272 + z
 * (w = vector width; 272 = 2*136 = 4*68 either way).  Pass 2 then works one
 * kx-block at a time with lanes = kx-in-block -- every load aligned -- and
 * pass 3 completes that block immediately out of an L1-resident [17][w*17]
 * mini-buffer.  This deletes the full-volume B scratch round trip (~157 KB of
 * L2 traffic per volume): panel_r2's verdict identified exactly this as the
 * highest-value L=17 move after L36_pfa gained 1.89x from the same class of
 * change.  The kernels and their accumulation order are unchanged, so the
 * result stays bit-identical to the a/b/c variants. */
static void pass1_f8(const double *in, double *dr, double *di,
                     const int32_t *b, const int32_t *t)
{
    DECL_SC(v8); OPAQUE_SC();
    for (int g = 0; g < 36; ++g) {
        const double *p = in + (size_t)2*8*g;
        v8 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            const v8u lo = *(const v8u *)(p + (size_t)578*a);
            const v8u hi = *(const v8u *)(p + (size_t)578*a + 8);
            xr[a] = SH8(lo, hi, 0,2,4,6,8,10,12,14);
            xi[a] = SH8(lo, hi, 1,3,5,7,9,11,13,15);
        }
        k17_c8(xr, xi, yr, yi, C0,C1,C2,C3,C4,C5,C6,C7);
        tst8f(yr, yi, dr, di, b + (size_t)8*g, t + (size_t)8*g);
    }
}

static void pass1_f4(const double *in, double *dr, double *di,
                     const int32_t *b, const int32_t *t)
{
    for (int g = 0; g < 72; ++g) {
        const double *p = in + (size_t)2*4*g;
        v4 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            const v4u lo = *(const v4u *)(p + (size_t)578*a);
            const v4u hi = *(const v4u *)(p + (size_t)578*a + 4);
            xr[a] = SH4(lo, hi, 0,2,4,6);
            xi[a] = SH4(lo, hi, 1,3,5,7);
        }
        k17_b4(xr, xi, yr, yi);
        tst4f(yr, yi, dr, di, b + (size_t)4*g, t + (size_t)4*g);
    }
}

/* Scalar pass-1 tail spectator (y,z) = (16,16), blocked-layout stores. */
static void tail1_f8(const double *in, double *dr, double *di)
{
    double xr[17], xi[17], yr[17], yi[17];
    for (int a = 0; a < 17; ++a) { xr[a] = in[2*(289*a + 288)]; xi[a] = in[2*(289*a + 288)+1]; }
    k17_s(xr, xi, yr, yi);
    for (int a = 0; a < 16; ++a) {
        const int o = 16*SP + (a/8)*136 + 16*8 + a%8;
        dr[o] = yr[a];  di[o] = yi[a];
    }
    dr[16*SP + 288] = yr[16];  di[16*SP + 288] = yi[16];
}

static void tail1_f4(const double *in, double *dr, double *di)
{
    double xr[17], xi[17], yr[17], yi[17];
    for (int a = 0; a < 17; ++a) { xr[a] = in[2*(289*a + 288)]; xi[a] = in[2*(289*a + 288)+1]; }
    k17_s(xr, xi, yr, yi);
    for (int a = 0; a < 16; ++a) {
        const int o = 16*SP + (a/4)*68 + 16*4 + a%4;
        dr[o] = yr[a];  di[o] = yi[a];
    }
    dr[16*SP + 288] = yr[16];  di[16*SP + 288] = yi[16];
}
#endif /* !L17_DENSE_KERNEL */

/* The one spectator that does not fill a vector: s = 288, i.e. (q,r) = (16,16).
 * Its destination run is contiguous, so no transpose is needed. */
#define TAIL_DST (16*SP + 16*17)
#define TAIL_OUT (2*(16*289 + 16*17))

static void tail1(const double *in, double *dr, double *di)
{
    double xr[17], xi[17], yr[17], yi[17];
    for (int a = 0; a < 17; ++a) { xr[a] = in[2*(578/2*a + 288)]; xi[a] = in[2*(578/2*a + 288)+1]; }
    k17_s(xr, xi, yr, yi);
    for (int a = 0; a < 17; ++a) { dr[TAIL_DST + a] = yr[a]; di[TAIL_DST + a] = yi[a]; }
}

static void tail2(const double *sr, const double *si, double *dr, double *di)
{
    double xr[17], xi[17], yr[17], yi[17];
    for (int a = 0; a < 17; ++a) { xr[a] = sr[a*SP + 288]; xi[a] = si[a*SP + 288]; }
    k17_s(xr, xi, yr, yi);
    for (int a = 0; a < 17; ++a) { dr[TAIL_DST + a] = yr[a]; di[TAIL_DST + a] = yi[a]; }
}

static void tail3(const double *sr, const double *si, double *out)
{
    double xr[17], xi[17], yr[17], yi[17];
    for (int a = 0; a < 17; ++a) { xr[a] = sr[a*SP + 288]; xi[a] = si[a*SP + 288]; }
    k17_s(xr, xi, yr, yi);
    for (int a = 0; a < 17; ++a) { out[TAIL_OUT + 2*a] = yr[a]; out[TAIL_OUT + 2*a+1] = yi[a]; }
}

struct fft3d_plan {
    int    batch;
    int    variant;            /* 0..NVAR-1, chosen by measurement in create() */
    int    pf_on;              /* cross-volume input prefetch, ditto          */
    double *buf;               /* 4 x 17*SP doubles: A.re A.im B.re B.im     */
    int32_t *base;             /* 288 scratch destination offsets            */
    int32_t *bout;             /* 288 interleaved-output destination offsets */
    int32_t *b8f, *b4f, *tf;   /* pass-1 store bases, kx-blocked layouts     */
    int32_t *bb8, *bb4;        /* fused pass-2 -> mini-buffer store bases    */
    int32_t *bo8, *bo4;        /* fused pass-3 -> out bases (block-local)    */
    int32_t *bt, *botail;      /* kx=16 tail-block tables                    */
    void   *raw_buf, *raw_base;
};

#ifndef L17_DENSE_KERNEL
/* Fused passes 2+3 for one volume, given A in the kx-blocked layout.  Per
 * kx-block: 17 pass-2 kernel groups (lanes = kx-in-block) write an L1-resident
 * [17 z][w*17 (kx,ky)] mini-buffer, then 17 pass-3 groups (lanes = consecutive
 * (kx,ky) spectators) read it back and store interleaved into out.  The kx=16
 * tail is its own 1-wide block, vectorised over z (pass 2) and ky (pass 3)
 * through a tiny 17x24-padded buffer; only two spectators per volume run the
 * scalar kernel (z=16 in pass 2, ky=16 in pass 3), same count as before.
 * The cross-volume prefetch of the NEXT volume's input is spread over the
 * pass-2 iterations exactly as in the unfused variants (1224 of 1229 lines). */
static void fused23_f8(const fft3d_plan *p, const double *ar, const double *ai,
                       double *out, const double *pf)
{
    DECL_SC(v8); OPAQUE_SC();
    double *br = p->buf + (size_t)2*17*SP, *bi = p->buf + (size_t)3*17*SP;
    double *btr = br + 2432, *bti = bi + 2432;
    int pfi = 0;
    for (int blk = 0; blk < 2; ++blk) {
        const double *sr = ar + 136*blk, *si = ai + 136*blk;
        for (int z = 0; z < 17; ++z) {
            if (pf) {
                for (int k = 0; k < 36; ++k)
                    __builtin_prefetch(pf + ((size_t)36*pfi + k)*8, 0, 2);
                ++pfi;
            }
            v8 xr[17], xi[17], yr[17], yi[17];
            for (int a = 0; a < 17; ++a) {
                xr[a] = *(const v8 *)(sr + (size_t)a*SP + 8*z);
                xi[a] = *(const v8 *)(si + (size_t)a*SP + 8*z);
            }
            k17_c8(xr, xi, yr, yi, C0,C1,C2,C3,C4,C5,C6,C7);
            tst8(yr, yi, br, bi, p->bb8 + (size_t)8*z);
        }
        double *o = out + (size_t)4624*blk;      /* 2*8*289 doubles per block */
        for (int h = 0; h < 17; ++h) {
            v8 xr[17], xi[17], yr[17], yi[17];
            for (int a = 0; a < 17; ++a) {
                xr[a] = *(const v8 *)(br + (size_t)a*136 + 8*h);
                xi[a] = *(const v8 *)(bi + (size_t)a*136 + 8*h);
            }
            k17_c8(xr, xi, yr, yi, C0,C1,C2,C3,C4,C5,C6,C7);
            tsto8(yr, yi, o, p->bo8 + (size_t)8*h);
        }
    }
    /* tail block, kx = 16 */
    for (int zg = 0; zg < 2; ++zg) {
        v8 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            xr[a] = *(const v8 *)(ar + (size_t)a*SP + 272 + 8*zg);
            xi[a] = *(const v8 *)(ai + (size_t)a*SP + 272 + 8*zg);
        }
        k17_c8(xr, xi, yr, yi, C0,C1,C2,C3,C4,C5,C6,C7);
        tst8(yr, yi, btr, bti, p->bt + (size_t)8*zg);
    }
    {
        double xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) { xr[a] = ar[(size_t)a*SP + 288]; xi[a] = ai[(size_t)a*SP + 288]; }
        k17_s(xr, xi, yr, yi);
        for (int a = 0; a < 17; ++a) { btr[16*24 + a] = yr[a]; bti[16*24 + a] = yi[a]; }
    }
    for (int kg = 0; kg < 2; ++kg) {
        v8 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            xr[a] = *(const v8 *)(btr + (size_t)a*24 + 8*kg);
            xi[a] = *(const v8 *)(bti + (size_t)a*24 + 8*kg);
        }
        k17_c8(xr, xi, yr, yi, C0,C1,C2,C3,C4,C5,C6,C7);
        tsto8(yr, yi, out, p->botail + (size_t)8*kg);
    }
    {
        double xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) { xr[a] = btr[(size_t)a*24 + 16]; xi[a] = bti[(size_t)a*24 + 16]; }
        k17_s(xr, xi, yr, yi);
        for (int a = 0; a < 17; ++a) { out[TAIL_OUT + 2*a] = yr[a]; out[TAIL_OUT + 2*a+1] = yi[a]; }
    }
}

static void fused23_f4(const fft3d_plan *p, const double *ar, const double *ai,
                       double *out, const double *pf)
{
    double *br = p->buf + (size_t)2*17*SP, *bi = p->buf + (size_t)3*17*SP;
    double *btr = br + 2432, *bti = bi + 2432;
    int pfi = 0;
    for (int blk = 0; blk < 4; ++blk) {
        const double *sr = ar + 68*blk, *si = ai + 68*blk;
        for (int z = 0; z < 17; ++z) {
            if (pf) {
                for (int k = 0; k < 18; ++k)
                    __builtin_prefetch(pf + ((size_t)18*pfi + k)*8, 0, 2);
                ++pfi;
            }
            v4 xr[17], xi[17], yr[17], yi[17];
            for (int a = 0; a < 17; ++a) {
                xr[a] = *(const v4 *)(sr + (size_t)a*SP + 4*z);
                xi[a] = *(const v4 *)(si + (size_t)a*SP + 4*z);
            }
            k17_b4(xr, xi, yr, yi);
            tst4(yr, yi, br, bi, p->bb4 + (size_t)4*z);
        }
        double *o = out + (size_t)2312*blk;      /* 2*4*289 doubles per block */
        for (int h = 0; h < 17; ++h) {
            v4 xr[17], xi[17], yr[17], yi[17];
            for (int a = 0; a < 17; ++a) {
                xr[a] = *(const v4 *)(br + (size_t)a*68 + 4*h);
                xi[a] = *(const v4 *)(bi + (size_t)a*68 + 4*h);
            }
            k17_b4(xr, xi, yr, yi);
            tsto4(yr, yi, o, p->bo4 + (size_t)4*h);
        }
    }
    /* tail block, kx = 16 */
    for (int zg = 0; zg < 4; ++zg) {
        v4 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            xr[a] = *(const v4 *)(ar + (size_t)a*SP + 272 + 4*zg);
            xi[a] = *(const v4 *)(ai + (size_t)a*SP + 272 + 4*zg);
        }
        k17_b4(xr, xi, yr, yi);
        tst4(yr, yi, btr, bti, p->bt + (size_t)4*zg);
    }
    {
        double xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) { xr[a] = ar[(size_t)a*SP + 288]; xi[a] = ai[(size_t)a*SP + 288]; }
        k17_s(xr, xi, yr, yi);
        for (int a = 0; a < 17; ++a) { btr[16*24 + a] = yr[a]; bti[16*24 + a] = yi[a]; }
    }
    for (int kg = 0; kg < 4; ++kg) {
        v4 xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) {
            xr[a] = *(const v4 *)(btr + (size_t)a*24 + 4*kg);
            xi[a] = *(const v4 *)(bti + (size_t)a*24 + 4*kg);
        }
        k17_b4(xr, xi, yr, yi);
        tsto4(yr, yi, out, p->botail + (size_t)4*kg);
    }
    {
        double xr[17], xi[17], yr[17], yi[17];
        for (int a = 0; a < 17; ++a) { xr[a] = btr[(size_t)a*24 + 16]; xi[a] = bti[(size_t)a*24 + 16]; }
        k17_s(xr, xi, yr, yi);
        for (int a = 0; a < 17; ++a) { out[TAIL_OUT + 2*a] = yr[a]; out[TAIL_OUT + 2*a+1] = yi[a]; }
    }
}
#endif /* !L17_DENSE_KERNEL */

#define RUN_VARIANT(TAG)                                           do {                                                               pass1_##TAG(in, ar, ai, p->base);                              tail1(in, ar, ai);                                             pass2_##TAG(ar, ai, br, bi, p->base, nextin);                  tail2(ar, ai, br, bi);                                         pass3_##TAG(br, bi, out, p->bout);                             tail3(br, bi, out);                                        } while (0)

/* The four variants differ only in SIMD width (256/512 bit) and in the
 * register-blocking of the kernel's A/B stage.  All four execute the same
 * arithmetic in the same order, so all four are bit-identical; which one is
 * fastest depends on the register file and on whether 512-bit code downclocks,
 * so fft3d_create() picks by measurement. */
/* nextin: base of the NEXT volume's input, prefetched into L2 during pass 2
 * (which touches no DRAM at all -- both its buffers are L2-resident scratch),
 * or NULL for the last volume / when the plan-time A/B said it does not pay.
 * Prefetches never change results, so this cannot affect the answer. */
static void one_volume(const fft3d_plan *p, const double *in, double *out,
                       const double *nextin)
{
    double *ar = p->buf, *ai = p->buf + 17*SP;
    double *br = p->buf + 2*17*SP, *bi = p->buf + 3*17*SP;
    switch (p->variant) {
    case 0:  RUN_VARIANT(a4); break;
    case 1:  RUN_VARIANT(a8); break;
    case 2:  RUN_VARIANT(b4); break;
#ifndef L17_DENSE_KERNEL
    case 3:  RUN_VARIANT(b8); break;
    case 4:  RUN_VARIANT(c4); break;
    case 5:  RUN_VARIANT(c8); break;
    case 6:
        pass1_f4(in, ar, ai, p->b4f, p->tf);
        tail1_f4(in, ar, ai);
        fused23_f4(p, ar, ai, out, nextin);
        break;
    default:
        pass1_f8(in, ar, ai, p->b8f, p->tf);
        tail1_f8(in, ar, ai);
        fused23_f8(p, ar, ai, out, nextin);
        break;
#else
    default: RUN_VARIANT(b8); break;
#endif
    }
}

static void run_vols(fft3d_plan *p, const double *ip, double *op, int nv, int pf_on)
{
    for (int b = 0; b < nv; ++b)
        one_volume(p, ip + (size_t)2*VOL*b, op + (size_t)2*VOL*b,
                   (pf_on && b + 1 < nv) ? ip + (size_t)2*VOL*(b+1) : NULL);
}

void fft3d_execute(fft3d_plan *p, const double _Complex *in, double _Complex *out)
{
    run_vols(p, (const double *)in, (double *)out, p->batch, p->pf_on);
}

const char *fft3d_name(void) { return "L17_winograd"; }

/* Updated by fft3d_create() so the leaderboard JSON reports which variant the
 * scoring machine's tuner actually picked (a4/a8 = split A/B stage, b = fused
 * A/B, c = + register-resident negacyclic constants, f = fused passes 2+3
 * over kx blocks, no full-volume B scratch; 4 = 256-bit, 8 = 512-bit). */
static char l17_desc[160] =
    "17-pt cyclic+negacyclic module (296 FP instr), 3 rotating passes, "
    "variant not yet tuned";
const char *fft3d_description(void) { return l17_desc; }
int fft3d_supports(int L) { return L == 17; }

static double nowsec(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (double)ts.tv_sec + 1e-9*(double)ts.tv_nsec;
}

fft3d_plan *fft3d_create(int L, int batch)
{
    if (L != 17 || batch <= 0) return NULL;
    fft3d_plan *p = calloc(1, sizeof *p);
    if (!p) return NULL;
    p->batch = batch;

    if (posix_memalign(&p->raw_buf, 64, (size_t)4*17*SP*sizeof(double)) != 0) { free(p); return NULL; }
    p->buf = (double *)p->raw_buf;
    memset(p->buf, 0, (size_t)4*17*SP*sizeof(double));

    /* int32 table arena: base 288 | bout 288 | b8f 288 | b4f 288 | tf 288 |
     * bb8 136 | bb4 68 | bo8 136 | bo4 68 | bt 17 | botail 17  = 1882 used  */
    if (posix_memalign(&p->raw_base, 64, (size_t)1920*sizeof(int32_t)) != 0) {
        free(p->raw_buf); free(p); return NULL;
    }
    {
        int32_t *ta = (int32_t *)p->raw_base;
        p->base = ta;         p->bout = ta + 288;
        p->b8f  = ta + 576;   p->b4f  = ta + 864;   p->tf = ta + 1152;
        p->bb8  = ta + 1440;  p->bb4  = ta + 1576;
        p->bo8  = ta + 1644;  p->bo4  = ta + 1780;
        p->bt   = ta + 1848;  p->botail = ta + 1865;
    }
    for (int s = 0; s < 288; ++s) {
        int q = s / 17, r = s % 17;
        p->base[s] = (int32_t)(q*SP + r*17);
        p->bout[s] = (int32_t)(2*(q*289 + r*17));
        p->b8f[s]  = (int32_t)(q*SP + r*8);      /* pass-1 store, blocked w=8 */
        p->b4f[s]  = (int32_t)(q*SP + r*4);      /* pass-1 store, blocked w=4 */
        p->tf[s]   = (int32_t)(q*SP + 272 + r);  /* pass-1 store, kx=16 tail  */
    }
    for (int z = 0; z < 17; ++z) {
        for (int j = 0; j < 8; ++j) p->bb8[z*8+j] = (int32_t)(z*136 + j*17);
        for (int j = 0; j < 4; ++j) p->bb4[z*4+j] = (int32_t)(z*68 + j*17);
        p->bt[z]     = (int32_t)(z*24);
        p->botail[z] = (int32_t)(2*(16*289 + z*17));
    }
    for (int sp = 0; sp < 136; ++sp) p->bo8[sp] = (int32_t)(2*((sp/17)*289 + (sp%17)*17));
    for (int sp = 0; sp <  68; ++sp) p->bo4[sp] = (int32_t)(2*((sp/17)*289 + (sp%17)*17));

    /* Pick the vector width by measurement: on a single-FMA-unit Cascade Lake
     * part a 512-bit kernel has the same peak FP throughput as a 256-bit one
     * and pays the AVX-512 licence frequency, so wider is not automatically
     * faster.  Both widths run identical arithmetic in identical order and
     * give bit-identical results, so this choice cannot change the answer. */
    p->variant = 0;
    p->pf_on   = 0;
    void *ti = NULL, *to = NULL;
    if (posix_memalign(&ti, 64, (size_t)2*VOL*sizeof(double)) == 0 &&
        posix_memalign(&to, 64, (size_t)2*VOL*sizeof(double)) == 0) {
        double *tin = (double *)ti;
        for (int i = 0; i < 2*VOL; ++i)
            tin[i] = (double)((i*2654435761u) % 1024) * 1e-3 - 0.5;
        double best[NVAR] = {0};
        for (int rep = 0; rep < 4; ++rep) {
            for (int v = 0; v < NVAR; ++v) {
                p->variant = v;
                /* Warm up long enough (>= ~1 ms) that the core has settled into
                 * this variant's frequency licence before timing.  Without this
                 * a 256-bit variant measured right after a 512-bit one is still
                 * inside the ~650 us AVX-512 licence dwell and looks slow
                 * (literature/04 section 8.2). */
                for (int i = 0; i < 60; ++i) one_volume(p, tin, (double *)to, NULL);
                double t0 = nowsec();
                for (int i = 0; i < 150; ++i) one_volume(p, tin, (double *)to, NULL);
                double dt = nowsec() - t0;
                if (best[v] == 0.0 || dt < best[v]) best[v] = dt;
            }
        }
        int bv = 0;
        for (int v = 1; v < NVAR; ++v) if (best[v] < best[bv]) bv = v;
        p->variant = bv;
    }
    free(ti); free(to);

    /* Stage 2 (batch >= 64 only): re-tune in the regime that will actually be
     * scored -- a working set past L3, where the streaming of in/out changes
     * which variant wins and whether the cross-volume prefetch pays.  Timed in
     * consecutive BLOCKS per candidate, never interleaved run-by-run: an A/B
     * of anything that changes cache or licence state mis-ranks by tens of
     * percent otherwise (borrowed from L17_matrixsimd's record, items 11-12).
     * All candidates are bit-identical, so the choice cannot change results. */
    if (batch >= 64) {
        const int nv = batch < 384 ? batch : 384;   /* up to ~60 MB in+out: past
                                                       L3 on the node (22 MB) AND
                                                       on wallaby (60 MB), so the
                                                       tune sees real streaming */
        void *bi_ = NULL, *bo_ = NULL;
        if (posix_memalign(&bi_, 64, (size_t)2*VOL*nv*sizeof(double)) == 0 &&
            posix_memalign(&bo_, 64, (size_t)2*VOL*nv*sizeof(double)) == 0) {
            double *bin = (double *)bi_, *bout = (double *)bo_;
            for (size_t i = 0; i < (size_t)2*VOL*nv; ++i)
                bin[i] = (double)((i*2654435761u) % 1024) * 1e-3 - 0.5;
            double best[NVAR][2];
            for (int v = 0; v < NVAR; ++v) best[v][0] = best[v][1] = 0.0;
            for (int rep = 0; rep < 3; ++rep) {
                for (int v = 0; v < NVAR; ++v) {
                    for (int pf = 0; pf < 2; ++pf) {
                        p->variant = v;
                        run_vols(p, bin, bout, nv, pf);          /* warm/licence */
                        double t0 = nowsec();
                        run_vols(p, bin, bout, nv, pf);
                        run_vols(p, bin, bout, nv, pf);
                        double dt = nowsec() - t0;
                        if (best[v][pf] == 0.0 || dt < best[v][pf]) best[v][pf] = dt;
                    }
                }
            }
            int bv = 0, bp = 0;
            for (int v = 0; v < NVAR; ++v)
                for (int pf = 0; pf < 2; ++pf)
                    if (best[v][pf] < best[bv][bp]) { bv = v; bp = pf; }
            p->variant = bv;
            p->pf_on = bp;
        }
        free(bi_); free(bo_);
    }
#ifdef L17_FORCE_VARIANT
    p->variant = L17_FORCE_VARIANT;
#endif
#ifdef L17_FORCE_PF
    p->pf_on = L17_FORCE_PF;
#endif
    {
        static const char *vn[8] = {"a4","a8","b4","b8","c4","c8","f4","f8"};
        const char *base = "17-pt cyclic+negacyclic module (296 FP instr), 3 rotating passes";
        size_t n = 0;
        while (base[n] && n < sizeof l17_desc - 32) { l17_desc[n] = base[n]; ++n; }
        l17_desc[n++] = ',';  l17_desc[n++] = ' ';
        l17_desc[n++] = 'v';  l17_desc[n++] = 'a';  l17_desc[n++] = 'r';
        l17_desc[n++] = '=';
        l17_desc[n++] = vn[p->variant][0];  l17_desc[n++] = vn[p->variant][1];
        l17_desc[n++] = ',';  l17_desc[n++] = ' ';
        l17_desc[n++] = 'p';  l17_desc[n++] = 'f';  l17_desc[n++] = '=';
        l17_desc[n++] = (char)('0' + p->pf_on);
        l17_desc[n] = '\0';
    }
    return p;
}

void fft3d_destroy(fft3d_plan *p)
{
    if (!p) return;
    free(p->raw_buf);
    free(p->raw_base);
    free(p);
}
